//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AVAsset {
    Class _field1;
    id _field2;
};

struct Attachment {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field9;
};

struct CATransform3D {
    double m11;
    double m12;
    double m13;
    double m14;
    double m21;
    double m22;
    double m23;
    double m24;
    double m31;
    double m32;
    double m33;
    double m34;
    double m41;
    double m42;
    double m43;
    double m44;
};

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct Contour {
    vector_d46ea067 _field1;
    _Bool _field2;
    _Bool _field3;
};

struct Document {
    CDUnknownFunctionPointerType *_vptr$MessageLite;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _unknown_fields_;
    unsigned int _has_bits_[1];
    int _cached_size_;
    struct NoteDocument *notedocument_;
    struct LegacyNoteDocument *legacynotedocument_;
};

struct ICDeviceHardwareInfo {
    unsigned long long modelName;
    long long version;
    long long subVersion;
};

struct Identity {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field7;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field8;
};

struct Invite {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
};

struct InviteReply {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    _Bool _field6;
};

struct KeepAlive {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
};

struct LegacyNoteDocument;

struct Media {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
};

struct Note {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct Document *_field6;
};

struct NoteAccountObject {
    Class _field1;
    int _field2;
    unsigned long long _field3;
    id _field4;
    id _field5;
    id _field6;
    id _field7;
    unsigned long long _field8;
    id _field9;
    id *_field10;
    unsigned long long _field11;
    id _field12;
    id _field13;
};

struct NoteContext {
    Class _field1;
    id _field2;
    id _field3;
    id _field4;
    id _field5;
    id _field6;
    id _field7;
    struct __CXIndex *_field8;
    id _field9;
    int _field10;
    _Bool _field11;
    id _field12;
    id _field13;
    id _field14;
    id _field15;
    id _field16;
    unsigned long long _field17;
    _Bool _field18;
    _Bool _field19;
    _Bool _field20;
    _Bool _field21;
    id _field22;
};

struct NoteDocument;

struct PeerNetworkMessage {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct Note *_field5;
    struct RequestNote *_field6;
    struct Attachment *_field7;
    struct RequestAttachment *_field8;
    struct RequestMedia *_field9;
    struct UnavailableMedia *_field10;
    struct Identity *_field11;
    struct Invite *_field12;
    struct InviteReply *_field13;
    struct ShareInfo *_field14;
    struct Media *_field15;
    struct KeepAlive *_field16;
    unsigned int _field17;
};

struct RepeatedPtrField<peernetworking::Identity> {
    void **_field1;
    int _field2;
    int _field3;
    int _field4;
};

struct RequestAttachment {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field6;
};

struct RequestMedia {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
};

struct RequestNote {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
};

struct ShareInfo {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
    struct RepeatedPtrField<peernetworking::Identity> _field6;
    unsigned int _field7;
};

struct StrokeVertex {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
};

struct UIColor {
    Class _field1;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct UIFont {
    Class _field1;
};

struct UIImage {
    Class _field1;
};

struct UIImageView {
    Class _field1;
};

struct UIView {
    Class _field1;
};

struct UnavailableMedia {
    CDUnknownFunctionPointerType *_field1;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> _field2;
    unsigned int _field3[1];
    int _field4;
    struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> *_field5;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

struct __wrap_iter<const ICDrawingOutputPoint *> {
    CDStruct_183601bc *_field1;
};

struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> {
    struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *__data_;
                    unsigned long long __size_;
                    unsigned long long __cap_;
                } __l;
                struct __short {
                    char __data_[23];
                    struct {
                        unsigned char __size_;
                    } ;
                } __s;
                struct __raw {
                    unsigned long long __words[3];
                } __r;
            } ;
        } __first_;
    } __r_;
};

struct vector<ICDrawingOutputPoint, std::__1::allocator<ICDrawingOutputPoint>> {
    CDStruct_183601bc *_field1;
    CDStruct_183601bc *_field2;
    struct __compressed_pair<ICDrawingOutputPoint *, std::__1::allocator<ICDrawingOutputPoint>> {
        CDStruct_183601bc *_field1;
    } _field3;
};

#pragma mark Typedef'd Structures

typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct {
    float x;
    float y;
    float z;
    float w;
} CDStruct_f2e236b6;

typedef struct {
    float x;
    float y;
    float z;
} CDStruct_03942939;

typedef struct {
    float x;
    float y;
} CDStruct_6e3f967a;

typedef struct {
    int arcType;
    _Bool before;
    double snapAngle;
} CDStruct_cfd08fee;

typedef struct {
    long long value;
    int timescale;
    unsigned int flags;
    long long epoch;
} CDStruct_1b6d18a9;

typedef struct CDStruct_183601bc;

typedef struct {
    int _field1;
    unsigned long long _field2;
    _Bool _field3;
    char *_field4;
    unsigned long long _field5;
    unsigned long long _field6;
    unsigned long long _field7;
    _Bool _field8;
    struct _NSRange _field9;
    unsigned long long _field10;
} CDStruct_c6084d62;

typedef struct {
    struct CGPoint _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    _Bool _field8;
    _Bool _field9;
    double _field10;
} CDStruct_ad01986a;

// Template types
typedef struct __wrap_iter<const ICDrawingOutputPoint *> {
    CDStruct_183601bc *_field1;
} __wrap_iter_6ff8c631;

typedef struct vector<ICDrawingOutputPoint, std::__1::allocator<ICDrawingOutputPoint>> {
    CDStruct_183601bc *_field1;
    CDStruct_183601bc *_field2;
    struct __compressed_pair<ICDrawingOutputPoint *, std::__1::allocator<ICDrawingOutputPoint>> {
        CDStruct_183601bc *_field1;
    } _field3;
} vector_d46ea067;

