//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOMNode.h"

@interface DOMNode (Summarization)
- (_Bool)containsValuableContent;
- (_Bool)isBreakingTag;
- (_Bool)isSeparatingTag;
- (_Bool)isStyleTag;
@end

