//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNoteBaseActivityItemSource.h"

#import "UIActivityItemSource.h"

@class NSString;

@interface ICAirDropNoteActivityItemSource : ICNoteBaseActivityItemSource <UIActivityItemSource>
{
    id <ICAirDropDocument> _airDropDocument;
    id _item;
}

- (void).cxx_destruct;
- (id)activityViewController:(id)arg1 dataTypeIdentifierForActivityType:(id)arg2;
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
- (id)activityViewControllerPlaceholderItem:(id)arg1;
@property(retain, nonatomic) id <ICAirDropDocument> airDropDocument; // @synthesize airDropDocument=_airDropDocument;
- (id)initWithTitle:(id)arg1 airDropDocument:(id)arg2;
@property(retain, nonatomic) id item; // @synthesize item=_item;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

