//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICAirDropDocument.h"

@class NSString;

@interface ICAirDropDocument : NSObject <ICAirDropDocument>
{
    struct Document _document;
}

+ (id)documentAtURL:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) id activityItem;
@property(readonly, copy, nonatomic) NSString *dataTypeIdentifier;
- (struct Document *)document;
@property(readonly, nonatomic) _Bool hasDocumentForLegacyNote;
@property(readonly, nonatomic) _Bool hasDocumentForNote;
- (id)initWithData:(id)arg1;

@end

