//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAirDropDocument.h"

@interface ICAirDropDocument (Legacy)
+ (_Bool)canAirDropImportIntoAccount:(struct NoteAccountObject *)arg1 context:(struct NoteContext *)arg2;
+ (id)legacyNoteAirDropDocumentWithWebArchive:(id)arg1;
- (id)webArchiveFromLegacyNoteDocument;
@end

