//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ICAnalyticsReporterBase : NSObject
{
}

+ (double)roundDoubleValue:(double)arg1;
+ (long long)roundIntegerValue:(long long)arg1;
- (void)addValue:(long long)arg1 forScalarKey:(id)arg2;
- (id)instrumentationKeyForKey:(id)arg1;
- (void)pushValue:(double)arg1 toDistributionKey:(id)arg2;
- (void)setValue:(long long)arg1 forScalarKey:(id)arg2;

@end

