//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAppDelegate.h"

@interface ICAppDelegate (ICTesting)
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;
- (void)bringUpKeyboard;
- (void)didEditorBeginEditing;
- (void)didEditorPresentActivityViewController;
- (void)didFinishExtendedLaunch;
- (void)didShowFolderList;
- (void)didShowNoteEditor;
- (void)didShowNotesList;
- (void)dismissKeyboard;
- (void)dismissMigrationScreenCompletionBlock:(CDUnknownBlockType)arg1;
- (_Bool)isScrollingTest:(id)arg1;
- (void)legacyBringUpKeyboard;
- (void)legacyDismissKeyboard;
- (_Bool)selectFirstNoteInTableView:(id)arg1 errorString:(id *)arg2;
- (void)showAccountsList;
- (void)showAccountsListAnimated:(_Bool)arg1;
- (void)showNoteWithAccountSelectionBlock:(CDUnknownBlockType)arg1 noteSelectionBlock:(CDUnknownBlockType)arg2 readyBlock:(CDUnknownBlockType)arg3 errorBlock:(CDUnknownBlockType)arg4;
- (void)showNotesListWithAccountSelectionBlock:(CDUnknownBlockType)arg1 readyBlock:(CDUnknownBlockType)arg2;
- (void)startICKeyboardBringUpAndDismissal:(id)arg1;
- (void)startICKeyboardRotation:(id)arg1;
- (void)startICKeyboardSplitAndMerge:(id)arg1;
- (void)startICNewNoteFromNoteViewTest:(id)arg1;
- (void)startICNewNoteFromNotesListTest:(id)arg1;
- (void)startICScrollAccountsListTest:(id)arg1;
- (void)startICScrollNoteTest:(id)arg1;
- (void)startICScrollNotesListTest:(id)arg1;
- (void)startICShowAccountsListTest:(id)arg1;
- (void)startICShowNoteTest:(id)arg1;
- (void)startICShowNotesListTest:(id)arg1;
- (void)startICShowShareSheetFromNoteViewTest:(id)arg1;
- (void)startMNKeyboardBringUpAndDismissal:(id)arg1;
- (void)startMNKeyboardRotation:(id)arg1;
- (void)startMNKeyboardSplitAndMerge:(id)arg1;
- (void)startMNScrollNoteTest:(id)arg1;
- (void)startMNScrollNotesListTest:(id)arg1;
- (void)startMNShowAccountsListTest:(id)arg1;
- (void)startMNShowNoteTest:(id)arg1;
- (void)startMNShowNotesListTest:(id)arg1;
- (void)willShowNoteEditor;
@end

