//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "ICArchivedUIStateDelegate.h"
#import "ICAudioCaptureSessionObserver.h"
#import "ICSplitViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIApplicationDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UISplitViewControllerDelegate.h"

@class ICArchivedUIState, ICAttachmentPresenter, ICCloudNoteController, ICFolderListViewController, ICNoteEditorViewController, ICNotesListViewController, ICOverlayWindowPresenter, ICReachability, ICSplitViewController, NSString, NSTimer, NSURL, NSUndoManager, NSUserActivity, UINavigationController, UIWindow;

@interface ICAppDelegate : UIResponder <UINavigationControllerDelegate, ICSplitViewControllerDelegate, ICArchivedUIStateDelegate, UIApplicationDelegate, UISplitViewControllerDelegate, UIAlertViewDelegate, ICAudioCaptureSessionObserver>
{
    NSString *_lastDisplayedCaptureSessionDurationString;
    unsigned long long _backgroundTaskIdentifier;
    _Bool _canUseDoubleHeightStatusBar;
    _Bool _recordingActiveOrPaused;
    _Bool _isActive;
    _Bool _searchIndexerDisabled;
    _Bool _pendingUserActivityContinuation;
    _Bool _refreshAccountsInFolderViewOnActivate;
    _Bool _shouldShowWelcomeScreenWhenInternetIsReachable;
    _Bool _shouldShowWelcomeScreenWhenLoggingInToUnmigratedICloudAccount;
    ICArchivedUIState *_archivedUIState;
    UIWindow *_window;
    ICSplitViewController *_splitViewController;
    UINavigationController *_masterNavigationController;
    ICFolderListViewController *_folderListViewController;
    ICNotesListViewController *_notesListViewController;
    ICNoteEditorViewController *_noteEditorViewController;
    ICReachability *_reachability;
    ICAttachmentPresenter *_currentAttachmentPresenter;
    ICAttachmentPresenter *_currentPreviewAttachmentPresenter;
    UINavigationController *_noteEditorNavigationViewController;
    NSTimer *_pendingUserActivityContinuationTimer;
    NSUserActivity *_userActivityPendingContinuation;
    NSUndoManager *_appUndoManager;
    ICCloudNoteController *_cloudNoteController;
    CDUnknownBlockType _reply;
    NSTimer *_repetitiveLoggingTimer;
    ICOverlayWindowPresenter *_startupPresenter;
    double _storedTextViewScrollPosition;
    NSURL *_launchURL;
    struct _NSRange _storedTextViewRange;
    struct CGSize _storedWindowSize;
}

- (void).cxx_destruct;
- (void)_audioCaptureSessionChangedNotification:(id)arg1;
- (void)_audioRecordingDurationChangedNotification:(id)arg1;
- (void)_beginLockScreenCaptureSession:(id)arg1;
- (void)_endLockScreenCaptureSession:(id)arg1;
- (void)_handleDidPauseCaptureSession:(id)arg1;
- (void)_handleDidResumeCaptureSession:(id)arg1;
- (void)_hideDoubleHeightStatusBar;
- (void)_showDoubleHeightStatusBarIfNecessary;
- (void)_updateRecordingStateForCaptureSession:(id)arg1 force:(_Bool)arg2;
- (void)abortUserActivityContinuation;
- (void)accountWillBeDeleted:(id)arg1;
- (void)accountsDidChange:(id)arg1;
- (void)actionForShortcutItem:(id)arg1;
- (void)addNote:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSUndoManager *appUndoManager; // @synthesize appUndoManager=_appUndoManager;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationSignificantTimeChange:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
@property(readonly, nonatomic) ICArchivedUIState *archivedUIState; // @synthesize archivedUIState=_archivedUIState;
- (void)attemptToContinuePendingUserActivity;
- (void)captureSession:(id)arg1 destinationFragmentDurationDidChangeToDuration:(double)arg2;
- (void)captureSession:(id)arg1 didFinishWithSuccess:(_Bool)arg2;
- (void)captureSession:(id)arg1 rateDidChangeToRate:(float)arg2;
@property(retain, nonatomic) ICCloudNoteController *cloudNoteController; // @synthesize cloudNoteController=_cloudNoteController;
- (void)composeNewNoteAndStartEditing:(_Bool)arg1;
- (void)composeNewNoteWithImage;
- (void)composeNewNoteWithSketch;
@property(retain, nonatomic) ICAttachmentPresenter *currentAttachmentPresenter; // @synthesize currentAttachmentPresenter=_currentAttachmentPresenter;
@property(readonly, copy, nonatomic) NSString *currentFolderIdentifier;
@property(readonly, copy, nonatomic) NSString *currentNoteContainerIdentifier;
@property(readonly, copy, nonatomic) NSString *currentNoteIdentifier;
@property(retain, nonatomic) ICAttachmentPresenter *currentPreviewAttachmentPresenter; // @synthesize currentPreviewAttachmentPresenter=_currentPreviewAttachmentPresenter;
@property(readonly, nonatomic) UINavigationController *detailNavigationController;
- (void)didReceiveTouchAffectingPendingActivityContinuation:(id)arg1;
- (_Bool)didUpdateNoteContainerForNewNote;
- (void)finishActivityContinuation;
- (void)finishLaunching;
@property(retain, nonatomic) ICFolderListViewController *folderListViewController; // @synthesize folderListViewController=_folderListViewController;
- (void)handleDarwinNotificationName:(id)arg1;
- (void)hideNavigationControllerHairlinesIfNecessary;
- (void)icSplitViewController:(id)arg1 didShowNoteEditorController:(id)arg2;
- (_Bool)icSplitViewController:(id)arg1 shouldCollapseNoteEditorController:(id)arg2;
- (_Bool)isAnyViewControllerFromOldApp;
@property(nonatomic, getter=isPendingUserActivityContinuation) _Bool pendingUserActivityContinuation; // @synthesize pendingUserActivityContinuation=_pendingUserActivityContinuation;
- (_Bool)isViewControllerFromOldApp:(id)arg1;
- (_Bool)isWelcomeScreenVisible;
- (id)keyCommands;
- (void)launchLegacySearchIndexableObjectFromCoreSpotlight:(id)arg1;
- (void)launchSearchIndexableObjectFromCoreSpotlight:(id)arg1;
@property(copy, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(retain, nonatomic) UINavigationController *masterNavigationController; // @synthesize masterNavigationController=_masterNavigationController;
- (void)migrationStateDidChange:(id)arg1;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (id)noteCurrentlyBeingEdited;
- (_Bool)noteEditorHasVisibleContent;
@property(retain, nonatomic) UINavigationController *noteEditorNavigationViewController; // @synthesize noteEditorNavigationViewController=_noteEditorNavigationViewController;
@property(retain, nonatomic) ICNoteEditorViewController *noteEditorViewController; // @synthesize noteEditorViewController=_noteEditorViewController;
@property(retain, nonatomic) ICNotesListViewController *notesListViewController; // @synthesize notesListViewController=_notesListViewController;
- (void)openArchive:(id)arg1;
- (_Bool)openURL:(id)arg1 verifyOnly:(_Bool)arg2;
- (void)openWelcomeScreenWhenInternetIsReachable;
- (void)openWelcomeScreenWhenLoggingInToUnmigratedICloudAccount;
@property(retain, nonatomic) NSTimer *pendingUserActivityContinuationTimer; // @synthesize pendingUserActivityContinuationTimer=_pendingUserActivityContinuationTimer;
@property(retain, nonatomic) ICReachability *reachability; // @synthesize reachability=_reachability;
- (void)reachabilityChanged:(id)arg1;
@property(nonatomic) _Bool refreshAccountsInFolderViewOnActivate; // @synthesize refreshAccountsInFolderViewOnActivate=_refreshAccountsInFolderViewOnActivate;
@property(retain) NSTimer *repetitiveLoggingTimer; // @synthesize repetitiveLoggingTimer=_repetitiveLoggingTimer;
@property(copy) CDUnknownBlockType reply; // @synthesize reply=_reply;
- (_Bool)resetMigrationStateForInternalSettingsAndShowMigrationScreenIfNecessary;
- (void)resumeIndexingAfterDelay;
@property(nonatomic) _Bool searchIndexerDisabled; // @synthesize searchIndexerDisabled=_searchIndexerDisabled;
- (void)setCanUseDoubleHeightStatusBar:(_Bool)arg1;
@property(nonatomic) _Bool shouldShowWelcomeScreenWhenInternetIsReachable; // @synthesize shouldShowWelcomeScreenWhenInternetIsReachable=_shouldShowWelcomeScreenWhenInternetIsReachable;
@property(nonatomic) _Bool shouldShowWelcomeScreenWhenLoggingInToUnmigratedICloudAccount; // @synthesize shouldShowWelcomeScreenWhenLoggingInToUnmigratedICloudAccount=_shouldShowWelcomeScreenWhenLoggingInToUnmigratedICloudAccount;
@property(retain, nonatomic) ICSplitViewController *splitViewController; // @synthesize splitViewController=_splitViewController;
@property(retain, nonatomic) ICOverlayWindowPresenter *startupPresenter; // @synthesize startupPresenter=_startupPresenter;
@property(nonatomic) struct _NSRange storedTextViewRange; // @synthesize storedTextViewRange=_storedTextViewRange;
@property(nonatomic) double storedTextViewScrollPosition; // @synthesize storedTextViewScrollPosition=_storedTextViewScrollPosition;
@property(nonatomic) struct CGSize storedWindowSize; // @synthesize storedWindowSize=_storedWindowSize;
@property(retain, nonatomic) NSUserActivity *userActivityPendingContinuation; // @synthesize userActivityPendingContinuation=_userActivityPendingContinuation;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)setupBarAppearances;
- (void)setupReachability;
- (void)setupWindow;
- (void)showCurrentNote;
- (void)showLegacyNote:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)showMigrationScreen;
- (_Bool)showMigrationStartupScreenIfNecessary;
- (void)showNote:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)showNote:(id)arg1 scrollToAttachment:(id)arg2;
- (void)showStartupWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)showStartupWithMovingViewOnly:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)undoManager;
- (void)updateDoubleHeightStatusBarForForegroundState;
- (void)updateViewByReloadingAccountsForUpdatedInternalSettings;
- (void)updateViewControllersToShowFolderList;
- (void)updateViewControllersToShowLegacyNote:(id)arg1 animated:(_Bool)arg2;
- (void)updateViewControllersToShowNote:(id)arg1;
- (void)updateViewControllersToShowNote:(id)arg1 noteContainer:(id)arg2 showDetailViewController:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)userActivityContinuationTimedOut:(id)arg1;
- (void)validateNoteEditorControllerType;
- (void)wrapUpIndexingIfNecessary;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

