//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface ICArchivedUIState : NSObject
{
    id <ICArchivedUIStateDelegate> _delegate;
    NSDictionary *_state;
}

- (void).cxx_destruct;
- (_Bool)attachmentBrowserOpen;
- (void)clearSavedState;
@property(readonly, copy, nonatomic) NSString *currentFolderIdentifier;
- (id)currentNote;
- (id)currentNoteContainer;
@property(readonly, copy, nonatomic) NSString *currentNoteContainerIdentifier;
@property(readonly, copy, nonatomic) NSString *currentNoteIdentifier;
@property(nonatomic) __weak id <ICArchivedUIStateDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)folderListHidden;
- (_Bool)hasArchivedState;
- (id)initWithDelegate:(id)arg1;
- (void)loadState;
- (id)noteEditorTextViewScrollPosition;
- (_Bool)notesListWasOnViewStack;
- (_Bool)primaryControllerHidden;
@property(copy, nonatomic) NSDictionary *state; // @synthesize state=_state;
- (_Bool)showingLegacyUI;
- (_Bool)showingNoteEditor;
- (id)singleNoteWindows;
- (void)updateAndSaveState;
- (void)updateState;

@end

