//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol ICArchivedUIStateDelegate
@property(readonly, copy, nonatomic) NSString *currentFolderIdentifier;
@property(readonly, copy, nonatomic) NSString *currentNoteContainerIdentifier;
@property(readonly, copy, nonatomic) NSString *currentNoteIdentifier;
@end

