//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAttachmentView.h"

@interface ICAttachmentView (ICAccessibility_iOS)
- (_Bool)_accessibilitySupportsActivateAction;
- (_Bool)accessibilityActivate;
- (_Bool)accessibilityElementsHidden;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (id)accessibilityValue;
- (_Bool)isAccessibilityElement;
@end

