//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAttachmentBrickView.h"

#import "ICAttachmentBrickAudioPlayerViewDelegate.h"

@class ICAttachmentBrickAudioPlayerView, NSString;

@interface ICAttachmentBrickWithAudioPlayerView : ICAttachmentBrickView <ICAttachmentBrickAudioPlayerViewDelegate>
{
    ICAttachmentBrickAudioPlayerView *_audioPlayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ICAttachmentBrickAudioPlayerView *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
- (void)audioPlayerView:(id)arg1 updateTime:(double)arg2;
- (void)audioPlayerViewStopped:(id)arg1;
- (void)dealloc;
- (struct UIView *)iconView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)refreshTime:(id)arg1;
- (void)registerForNotifications;
- (void)updateContentFromAttachment;
- (void)updateSubtitleString:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

