//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAttachmentBrickView.h"

@class UIImageView, UIView;

@interface ICAttachmentBrickWithImageView : ICAttachmentBrickView
{
    _Bool _showAsFileIcon;
    struct UIView *_imageContainerView;
    struct UIImageView *_imageView;
}

+ (struct UIColor *)imageBorderColor;
+ (id)thumbnailCache;
- (void).cxx_destruct;
- (void)attachmentPreviewImagesDidUpdate:(id)arg1;
- (void)dealloc;
- (void)didMoveToWindow;
- (struct UIView *)iconView;
@property(retain, nonatomic) UIView *imageContainerView; // @synthesize imageContainerView=_imageContainerView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setIconImage:(struct UIImage *)arg1;
- (void)setIconImage:(struct UIImage *)arg1 contentMode:(unsigned long long)arg2;
- (void)setImageInset:(double)arg1;
@property(nonatomic) _Bool showAsFileIcon; // @synthesize showAsFileIcon=_showAsFileIcon;
- (void)updateContentFromAttachment;
- (void)updateImageOutline;

@end

