//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ICAttachment, ICAttachmentBrickTitleView, ICSearchResult, NSAttributedString, NSLayoutConstraint, NSString;

@interface ICAttachmentBrickView : UIView
{
    _Bool _selected;
    _Bool _iconHidden;
    ICAttachment *_attachment;
    ICSearchResult *_searchResult;
    unsigned long long _brickLayout;
    ICAttachmentBrickTitleView *_titleView;
    long long _fileSizeCache;
    NSString *_fileSizeStringCache;
    NSLayoutConstraint *_textTrailingToSuperviewConstraint;
    NSLayoutConstraint *_textTrailingToIconConstraint;
    NSLayoutConstraint *_iconTrailingToSuperviewConstraint;
}

- (void).cxx_destruct;
@property(nonatomic) __weak ICAttachment *attachment; // @synthesize attachment=_attachment;
- (void)attachmentDidLoad:(id)arg1;
- (void)attachmentPreviewImagesDidUpdate:(id)arg1;
@property(nonatomic) unsigned long long brickLayout; // @synthesize brickLayout=_brickLayout;
- (void)contentSizeCategoryDidChange;
- (void)dealloc;
@property(nonatomic) long long fileSizeCache; // @synthesize fileSizeCache=_fileSizeCache;
@property(copy, nonatomic) NSString *fileSizeStringCache; // @synthesize fileSizeStringCache=_fileSizeStringCache;
@property(retain, nonatomic) NSLayoutConstraint *iconTrailingToSuperviewConstraint; // @synthesize iconTrailingToSuperviewConstraint=_iconTrailingToSuperviewConstraint;
@property(readonly, nonatomic) UIView *iconView;
- (void)initContents;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isIconHidden) _Bool iconHidden; // @synthesize iconHidden=_iconHidden;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
- (void)mediaDidLoad:(id)arg1;
- (struct UIColor *)outlineColor;
@property(nonatomic) __weak ICSearchResult *searchResult; // @synthesize searchResult=_searchResult;
- (struct UIColor *)selectedOutlineColor;
- (void)setAttachment:(id)arg1 withSearchResult:(id)arg2;
- (void)setBrickMarginLeading:(double)arg1 trailing:(double)arg2 top:(double)arg3 bottom:(double)arg4;
@property(copy, nonatomic) NSAttributedString *subtitleAttributedString;
@property(copy, nonatomic) NSString *subtitleString;
@property(retain, nonatomic) NSLayoutConstraint *textTrailingToIconConstraint; // @synthesize textTrailingToIconConstraint=_textTrailingToIconConstraint;
@property(retain, nonatomic) NSLayoutConstraint *textTrailingToSuperviewConstraint; // @synthesize textTrailingToSuperviewConstraint=_textTrailingToSuperviewConstraint;
@property(copy, nonatomic) NSAttributedString *titleAttributedString;
@property(copy, nonatomic) NSString *titleString;
@property(retain, nonatomic) ICAttachmentBrickTitleView *titleView; // @synthesize titleView=_titleView;
@property(nonatomic) double trailingMargin; // @dynamic trailingMargin;
- (void)setupRoundedOutline:(_Bool)arg1;
@property(readonly, nonatomic) NSString *textForSubtitle;
@property(readonly, nonatomic) NSString *textForTitle;
- (void)updateContentFromAttachment;
- (void)updateSearchHighlighting;
- (void)updateTextFromAttachment;

@end

