//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICAttachmentPresentationDelegate.h"
#import "ICImageAttachmentPresentationDelegate.h"
#import "QLPreviewControllerDataSource.h"
#import "QLPreviewControllerDelegate.h"

@class ICAttachment, NSString, UIBarButtonItem, UIView, UIViewController;

@interface ICAttachmentPresenter : NSObject <QLPreviewControllerDataSource, QLPreviewControllerDelegate, ICAttachmentPresentationDelegate, ICImageAttachmentPresentationDelegate>
{
    _Bool _showGoToNote;
    _Bool _editable;
    ICAttachment *_attachment;
    UIView *_viewToPresentFrom;
    UIViewController *_presentedViewController;
    UIViewController *_presentingViewController;
    UIBarButtonItem *_goToNoteButton;
}

+ (_Bool)presentAttachment:(id)arg1 fromView:(id)arg2 showGoToNote:(_Bool)arg3;
+ (_Bool)presentAttachment:(id)arg1 fromView:(id)arg2 showGoToNote:(_Bool)arg3 editable:(_Bool)arg4 presentingViewController:(id)arg5;
+ (id)previewViewControllerForAttachment:(id)arg1 fromView:(id)arg2 isFromAttachmentBrowser:(_Bool)arg3;
- (void).cxx_destruct;
@property(retain) ICAttachment *attachment; // @synthesize attachment=_attachment;
- (void)attachmentViewControllerDidDismiss:(id)arg1;
- (void)attachmentWillBeDeletedNotification:(id)arg1;
- (void)dealloc;
- (void)dismiss:(id)arg1;
- (void)goToNote:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *goToNoteButton; // @synthesize goToNoteButton=_goToNoteButton;
- (struct UIImage *)image;
- (id)initWithAttachment:(id)arg1;
@property(getter=isEditable) _Bool editable; // @synthesize editable=_editable;
- (long long)numberOfPreviewItemsInPreviewController:(id)arg1;
- (void)openURL:(id)arg1;
- (_Bool)prefersStatusBarHidden;
- (void)presentAttachment;
- (void)presentAttachmentViewController:(id)arg1;
- (void)presentDrawing;
- (void)presentImage;
- (void)presentMovie;
- (void)presentQuickLook;
- (void)presentURL;
@property(retain) UIViewController *presentedViewController; // @synthesize presentedViewController=_presentedViewController;
@property(retain) UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (struct CGRect)previewController:(id)arg1 frameForPreviewItem:(id)arg2 inSourceView:(id *)arg3;
- (id)previewController:(id)arg1 previewItemAtIndex:(long long)arg2;
- (id)previewController:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(struct CGRect *)arg3;
- (void)previewControllerDidDismiss:(id)arg1;
- (id)previewMenuItemsForAttachment;
@property _Bool showGoToNote; // @synthesize showGoToNote=_showGoToNote;
@property(retain) UIView *viewToPresentFrom; // @synthesize viewToPresentFrom=_viewToPresentFrom;
- (struct UIView *)viewToPresentAttachmentFrom;
- (id)viewToPresentFromForQuickLook;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

