//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAudioPlayPauseView.h"

@class ICArcLayer;

@interface ICAttachmentBrickAudioPlayerView : ICAudioPlayPauseView
{
    id <ICAttachmentBrickAudioPlayerViewDelegate> _delegate;
    ICArcLayer *_progressCircleLayer;
}

- (void).cxx_destruct;
- (void)createBackgroundLayer;
- (void)createPlayPauseViews;
- (void)createProgressCircleLayer;
@property(nonatomic) id <ICAttachmentBrickAudioPlayerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didMoveToWindow;
- (struct CGSize)intrinsicContentSize;
@property(retain, nonatomic) ICArcLayer *progressCircleLayer; // @synthesize progressCircleLayer=_progressCircleLayer;
- (void)setBounds:(struct CGRect)arg1;
- (void)sharedInit;
- (void)showDisabled:(_Bool)arg1;
- (void)showPressed:(_Bool)arg1;
- (void)showStopped;
- (id)tintColor;
- (void)updateTime:(double)arg1 duration:(double)arg2;

@end

