//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICAttachmentBrickAudioPlayerView;

@protocol ICAttachmentBrickAudioPlayerViewDelegate <NSObject>
- (void)audioPlayerView:(ICAttachmentBrickAudioPlayerView *)arg1 updateTime:(double)arg2;
- (void)audioPlayerViewStopped:(ICAttachmentBrickAudioPlayerView *)arg1;
@end

