//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class CALayer, UIColor;

@interface ICAudioRecorderStateButton : UIButton
{
    UIColor *_outerColor;
    CALayer *_innerLayer;
    UIColor *_innerColor;
    long long _AVCaptureState;
}

- (void).cxx_destruct;
@property(nonatomic) long long AVCaptureState; // @synthesize AVCaptureState=_AVCaptureState;
- (double)_currentStateInnerDrawingAlpha;
- (double)_currentStateTopLevelDrawingAlpha;
- (void)_drawOuterCircle;
- (void)drawRect:(struct CGRect)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setEnabled:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

