//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class ICNote, NSLayoutConstraint, UIButton;

@interface ICAudioBarViewController : UIViewController
{
    id <ICAudioBarViewControllerDelegate> _delegate;
    ICNote *_note;
    UIViewController *_addedToViewController;
    NSLayoutConstraint *_topConstraint;
}

- (void).cxx_destruct;
- (void)addConstraintsToSuperview;
- (void)addToViewController:(id)arg1;
@property(nonatomic) __weak UIViewController *addedToViewController; // @synthesize addedToViewController=_addedToViewController;
- (void)adjustTextViewContentInsetWhenAddingView:(_Bool)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <ICAudioBarViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didRotate:(id)arg1;
- (void)done:(id)arg1;
@property(readonly, nonatomic) UIButton *doneButton;
- (_Bool)hasTranslucentNavigationBar;
@property(nonatomic) double height; // @dynamic height;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic) __weak ICNote *note; // @synthesize note=_note;
- (void)noteWillBeDeletedNotification:(id)arg1;
@property(retain, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
- (double)topConstraintConstant;

@end

