//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICAudioCaptureSessionObserver.h"

@class AVPlayer, ICAttachment, ICAudioCaptureSession, NSString;

@interface ICAudioController : NSObject <ICAudioCaptureSessionObserver>
{
    long long _AVCaptureState;
    AVPlayer *_currentPlayer;
    ICAttachment *_currentAttachment;
    ICAudioCaptureSession *_currentCaptureSession;
    NSObject *_playbackTimeObserver;
}

+ (void)pauseIfPlaying;
+ (id)sharedAudioController;
- (void).cxx_destruct;
@property(nonatomic) long long AVCaptureState; // @synthesize AVCaptureState=_AVCaptureState;
- (void)attachmentWillBeDeletedNotification:(id)arg1;
- (void)captureSession:(id)arg1 destinationFragmentDurationDidChangeToDuration:(double)arg2;
- (void)captureSession:(id)arg1 didFinishWithSuccess:(_Bool)arg2;
- (void)captureSession:(id)arg1 rateDidChangeToRate:(float)arg2;
- (void)closeRecordingSession;
@property(retain, nonatomic) ICAttachment *currentAttachment; // @synthesize currentAttachment=_currentAttachment;
@property(retain, nonatomic) ICAudioCaptureSession *currentCaptureSession; // @synthesize currentCaptureSession=_currentCaptureSession;
@property(retain, nonatomic) AVPlayer *currentPlayer; // @synthesize currentPlayer=_currentPlayer;
- (void)dealloc;
- (id)finalizedRecordingAssetURL;
- (void)finishRecording;
- (id)init;
@property(readonly, nonatomic) _Bool isPlaying;
- (void)notifyPaused;
- (void)notifyPlaying;
- (void)notifyStopped;
- (void)pause;
- (void)pauseRecording;
- (void)play;
- (void)play:(id)arg1;
@property(retain, nonatomic) NSObject *playbackTimeObserver; // @synthesize playbackTimeObserver=_playbackTimeObserver;
- (long long)remotePause:(id)arg1;
- (long long)remotePlay:(id)arg1;
- (long long)remoteSkipBackward:(id)arg1;
- (long long)remoteSkipForward:(id)arg1;
- (long long)remoteStop:(id)arg1;
- (long long)remoteTogglePlayPause:(id)arg1;
- (void)seekToTime:(double)arg1;
- (void)skipAheadByInterval:(double)arg1;
- (void)skipBackByInterval:(double)arg1;
- (void)startOrResumeRecording;
- (void)stop;
- (void)togglePlayPause;
- (void)updateNowPlayingInfo;
- (void)updateRecordingDuration:(id)arg1;
- (void)updateTime:(double)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

