//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAudioSample.h"

@class NSArray;

@interface ICAudioSampleGroup : ICAudioSample
{
    _Bool _needToRegeneratePowerLevel;
    NSArray *_samples;
}

- (void).cxx_destruct;
- (void)addSample:(id)arg1;
- (id)init;
@property _Bool needToRegeneratePowerLevel; // @synthesize needToRegeneratePowerLevel=_needToRegeneratePowerLevel;
- (double)powerLevel;
- (void)regeneratePowerLevel;
@property(retain) NSArray *samples; // @synthesize samples=_samples;

@end

