//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

#import "ICBrowseAttachmentsHeaderViewDelegate.h"
#import "NSFetchedResultsControllerDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class ICBrowseAttachmentsIconCell, NSFetchedResultsController, NSMutableArray, NSString, NotesTextureBackgroundView, UILabel, UIView;

@interface ICBrowseAttachmentsCollectionController : UICollectionViewController <NSFetchedResultsControllerDelegate, UICollectionViewDelegateFlowLayout, ICBrowseAttachmentsHeaderViewDelegate>
{
    NSMutableArray *_sectionChanges;
    NSMutableArray *_itemChanges;
    ICBrowseAttachmentsIconCell *_defaultSizingIconCell;
    struct CGSize _brickCellSize;
    _Bool _updatingAccounts;
    _Bool _scrollViewDecelerating;
    short _attachmentSection;
    CDUnknownBlockType _browserDidCloseHandler;
    UIView *_emptyView;
    UILabel *_noAttachmentsLabel;
    UILabel *_emptyDetailsLabel;
    NSFetchedResultsController *_fetchedResultsController;
    NotesTextureBackgroundView *_textureBackgroundView;
    NotesTextureBackgroundView *_topTextureView;
}

+ (id)separatorColor;
- (void).cxx_destruct;
- (void)accountsDidChange;
- (void)accountsWillChange;
@property(nonatomic) short attachmentSection; // @synthesize attachmentSection=_attachmentSection;
@property(copy, nonatomic) CDUnknownBlockType browserDidCloseHandler; // @synthesize browserDidCloseHandler=_browserDidCloseHandler;
- (unsigned long long)cellsPerRow;
- (_Bool)collectionView:(id)arg1 canPerformAction:(SEL)arg2 forItemAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 performAction:(SEL)arg2 forItemAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)collectionView:(id)arg1 shouldShowMenuForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionViewAtPosition:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (id)collectionViewCellAtPosition:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (void)commitPreviewViewController:(id)arg1 committedViewController:(id)arg2;
- (void)configureCell:(id)arg1 withBrick:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)contentSizeCategoryDidChange;
- (void)controllerDidChangeContent:(id)arg1;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
@property(readonly, nonatomic) _Bool displayAllSections;
- (void)doneAction:(id)arg1;
@property(retain, nonatomic) UILabel *emptyDetailsLabel; // @synthesize emptyDetailsLabel=_emptyDetailsLabel;
@property(retain, nonatomic) UIView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (id)headerViewAtPosition:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (void)icaxDismissAttachmentBrowser;
- (id)init;
- (id)initWithAttachmentSection:(short)arg1;
@property(retain, nonatomic) UILabel *noAttachmentsLabel; // @synthesize noAttachmentsLabel=_noAttachmentsLabel;
- (void)notesContextRefreshNotification:(id)arg1;
- (long long)numberOfItemsToDisplayInSection:(long long)arg1 withTraitCollection:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (_Bool)presentAttachment:(id)arg1 fromCell:(id)arg2;
- (id)previewViewControllerForLocation:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (void)respondToTapGesture:(id)arg1;
@property(nonatomic) _Bool scrollViewDecelerating; // @synthesize scrollViewDecelerating=_scrollViewDecelerating;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) NotesTextureBackgroundView *textureBackgroundView; // @synthesize textureBackgroundView=_textureBackgroundView;
@property(retain, nonatomic) NotesTextureBackgroundView *topTextureView; // @synthesize topTextureView=_topTextureView;
@property(nonatomic) _Bool updatingAccounts; // @synthesize updatingAccounts=_updatingAccounts;
- (void)showAllForAttachmentSection:(short)arg1;
- (id)titleForAttachmentSection:(short)arg1;
- (void)updateEmptyView;
- (id)viewControllerForAttachmentSection:(short)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willPresentPreviewViewController:(id)arg1 forLocation:(struct CGPoint)arg2 inSourceView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

