//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class ICAttachment, ICBrowseAttachmentsCollectionController;

@interface ICBrowseAttachmentsBaseCell : UICollectionViewCell
{
    ICAttachment *_attachment;
    ICBrowseAttachmentsCollectionController *_collectionController;
}

+ (void)initialize;
+ (void)setupMenuController;
- (void).cxx_destruct;
@property(retain, nonatomic) ICAttachment *attachment; // @synthesize attachment=_attachment;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
@property(nonatomic) __weak ICBrowseAttachmentsCollectionController *collectionController; // @synthesize collectionController=_collectionController;
- (void)goToNote:(id)arg1;

@end

