//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICCloudContextDelegate.h"

@class NSDate, NSString, UIAlertController;

@interface ICCloudNoteController : NSObject <ICCloudContextDelegate>
{
    NSDate *_overQuotaAlertLastShown;
    UIAlertController *_overQuotaAlertController;
}

- (void).cxx_destruct;
- (void)accountsDidChange:(id)arg1;
- (void)cloudContext:(id)arg1 didFetchUserRecordID:(id)arg2;
- (void)cloudContext:(id)arg1 receivedZoneNotFound:(id)arg2;
- (void)cloudContext:(id)arg1 userDidDeleteRecordZoneWithID:(id)arg2;
- (void)dealloc;
- (_Bool)deleteCloudObjectIfFullyPushed:(id)arg1;
- (void)didFailPushingExceededStorageQuotaForContext:(id)arg1;
- (id)init;
@property(retain, nonatomic) UIAlertController *overQuotaAlertController; // @synthesize overQuotaAlertController=_overQuotaAlertController;
@property(retain, nonatomic) NSDate *overQuotaAlertLastShown; // @synthesize overQuotaAlertLastShown=_overQuotaAlertLastShown;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

