//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKRecordID, CKRecordZoneID, ICCloudContext;

@protocol ICCloudContextDelegate <NSObject>
- (void)cloudContext:(ICCloudContext *)arg1 didFetchUserRecordID:(CKRecordID *)arg2;
- (void)cloudContext:(ICCloudContext *)arg1 receivedZoneNotFound:(CKRecordZoneID *)arg2;
- (void)cloudContext:(ICCloudContext *)arg1 userDidDeleteRecordZoneWithID:(CKRecordZoneID *)arg2;
- (void)didFailPushingExceededStorageQuotaForContext:(ICCloudContext *)arg1;
@end

