//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface ICDeviceInfo : NSObject <NSCopying>
{
    NSString *_name;
    NSString *_model;
    NSString *_modelDisplayName;
    NSString *_softwareVersion;
    struct ICDeviceHardwareInfo _hardwareInfo;
}

+ (void)logDeviceList:(id)arg1;
- (void).cxx_destruct;
- (id)attributedStringWithAttributes:(id)arg1 asteriskColor:(struct UIColor *)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(readonly, nonatomic) struct ICDeviceHardwareInfo hardwareInfo; // @synthesize hardwareInfo=_hardwareInfo;
- (struct ICDeviceHardwareInfo)hardwareInfoFromModelId:(id)arg1;
- (unsigned long long)hardwareInfoNameFromString:(id)arg1;
- (id)init;
- (id)initWithName:(id)arg1 model:(id)arg2 modelDisplayName:(id)arg3 softwareVersion:(id)arg4;
- (_Bool)isHardwareInfoUpgradable:(struct ICDeviceHardwareInfo)arg1;
@property(readonly, nonatomic) _Bool isOSXDevice;
- (id)loggableDescription;
@property(readonly, nonatomic) NSString *model; // @synthesize model=_model;
@property(readonly, nonatomic) NSString *modelDisplayName; // @synthesize modelDisplayName=_modelDisplayName;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *softwareVersion; // @synthesize softwareVersion=_softwareVersion;
@property(readonly, nonatomic) _Bool upgradable;
@property(readonly, nonatomic) _Bool upgraded;

@end

