//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ICDebugUtilities : NSObject
{
}

+ (void)addAttachment:(id)arg1 toString:(id)arg2 prefix:(id)arg3;
+ (void)addFolder:(id)arg1 toString:(id)arg2 prefix:(id)arg3;
+ (void)addNote:(id)arg1 toString:(id)arg2 prefix:(id)arg3;
+ (void)deleteEverythingWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)deleteInvalidObjects;
+ (void)deleteMigratedDuplicatesWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)deleteZonesWithZoneIDs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (_Bool)handleDebugURL:(id)arg1;
+ (id)loggingSeparator;
+ (void)purgeEverythingWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)pushEverythingToCloud;
+ (void)showAlertForError:(id)arg1 title:(id)arg2;
+ (void)showAlertWithTitle:(id)arg1 description:(id)arg2;
+ (void)startFreshWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (id)stateOfTheWorld;

@end

