//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIWindow;

@interface ICDebugSpinner : NSObject
{
    UIWindow *_window;
}

- (void).cxx_destruct;
- (void)hide;
@property(retain) UIWindow *window; // @synthesize window=_window;
- (void)show;

@end

