//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIDocumentPickerDelegate.h"

@class NSArray, NSString;

@interface ICDebuggingViewController : UITableViewController <UIDocumentPickerDelegate>
{
    NSArray *_sectionDictionaries;
}

- (void).cxx_destruct;
- (id)URLsForTestDataDirectories;
- (void)addSomeRandomNotes:(id)arg1;
- (id)allBackupURLs;
- (void)clearAllBackups:(id)arg1;
- (void)clearAllLogs:(id)arg1;
- (void)crashThisApp:(id)arg1;
- (void)createSectionDictionaries;
- (void)deleteEverything:(id)arg1;
- (void)deleteMigratedDuplicates:(id)arg1;
- (void)deletePreviews:(id)arg1;
- (void)deleteSearchIndex:(id)arg1;
- (void)deleteServerChangeTokens:(id)arg1;
- (void)documentPicker:(id)arg1 didPickDocumentAtURL:(id)arg2;
- (void)importTestDataFromDirectoryAtURL:(id)arg1;
- (id)initWithStyle:(long long)arg1;
- (void)loadArchiveFromICloudDrive:(id)arg1;
- (void)loadBackup:(id)arg1;
- (void)loadTestData:(id)arg1;
- (void)logStateOfTheWorld:(id)arg1;
- (void)migrateICloudAccount:(id)arg1;
- (void)migrateLocalAccount:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)purgeEverything:(id)arg1;
- (void)pushEverythingToCloud:(id)arg1;
- (void)resetLocalAccountMigration:(id)arg1;
- (void)resetWelcomeScreenState:(id)arg1;
- (void)saveBackup:(id)arg1;
@property(retain) NSArray *sectionDictionaries; // @synthesize sectionDictionaries=_sectionDictionaries;
- (void)sendAllLogs:(id)arg1;
- (void)sendArchive:(id)arg1;
- (void)sendCurrentLog:(id)arg1;
- (void)sendLogsAtURLs:(id)arg1 fromSender:(id)arg2;
- (void)sendStateOfTheWorld:(id)arg1;
- (void)setCloudConfiguration:(id)arg1;
- (void)setDefaultLogLevel:(id)arg1;
- (void)startFresh:(id)arg1;
- (void)syncLocalWithCloud:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)toggleNonContiguousLayout:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

