//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

@class UIAlertAction;

@interface ICDismissableAlertController : UIAlertController
{
    UIAlertAction *_dismissAction;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIAlertAction *dismissAction; // @synthesize dismissAction=_dismissAction;
- (void)dismissWhenPossible;

@end

