//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ICDrawingContour : NSObject
{
    long long _drawFromIndex;
    long long _contourLength;
    long long _immutableIndex;
    struct Contour *_currentPath;
    _Bool _recordRawData;
    vector_d46ea067 *_verticies;
    vector_d46ea067 *_raw;
}

- (void)addVerticies:(const vector_d46ea067 *)arg1 fromIndex:(unsigned long long)arg2 withSegmentBlock:(CDUnknownBlockType)arg3;
- (struct CGRect)bounds;
- (void)calcRawPath:(struct _NSRange)arg1 into:(struct Contour *)arg2;
- (void)calcSplinePathInRange:(struct _NSRange)arg1 into:(struct Contour *)arg2;
- (void)clear;
- (void)clearCurrentPath;
@property(readonly, nonatomic) struct Contour *currentPath;
- (void)dealloc;
- (id)init;
@property(readonly, nonatomic) vector_d46ea067 *raw; // @synthesize raw=_raw;
@property(nonatomic) _Bool recordRawData; // @synthesize recordRawData=_recordRawData;
- (struct Contour)segment;
- (struct Contour)segmentWithDelta:(int)arg1;
- (unsigned long long)size;
@property(readonly, nonatomic) vector_d46ea067 *verticies; // @synthesize verticies=_verticies;

@end

