//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICDrawingInputControllerDelegate.h"

@class CAEAGLLayer, ICDrawingInputController, ICDrawingRenderer, ICGLContext, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString;

@interface ICDrawingRendererController : NSObject <ICDrawingInputControllerDelegate>
{
    NSObject<OS_dispatch_queue> *_renderQueue;
    unsigned long long _immutableCountProvided;
    NSObject<OS_dispatch_semaphore> *_queuedRendersSemaphore;
    ICGLContext *_context;
    unsigned int _resolveFramebuffer;
    unsigned int _resolveColorRenderbuffer;
    int renderbufferWidth;
    int renderbufferHeight;
    CAEAGLLayer *_presentationLayer;
    _Bool _cancelRendering;
    _Bool _drawingCommands;
    ICDrawingInputController *_inputController;
    long long _renderCount;
    long long _missedRenderCount;
    ICDrawingRenderer *_renderer;
    struct CGSize _renderSize;
    struct CGAffineTransform _transform;
    struct CGAffineTransform _renderTransform;
}

+ (id)sharedRendererController;
- (void).cxx_destruct;
- (void)_createFramebuffer;
- (void)_deleteFramebuffer;
- (void)_discard;
- (void)_present;
- (void)_render;
- (void)_renderDrawPoints;
@property _Bool cancelRendering; // @synthesize cancelRendering=_cancelRendering;
- (void)changeRenderSize;
- (void)clear;
- (void)dealloc;
- (void)drawCommands:(id)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2 completion:(CDUnknownBlockType)arg3;
- (void)drawCommands:(id)arg1 renderIntermediateSteps:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)drawCommandsAfterClear:(id)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2 completion:(CDUnknownBlockType)arg3;
- (void)drawImage:(struct CGImage *)arg1;
- (void)drawImage:(struct CGImage *)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2;
- (void)drawingBeganWithCommand:(id)arg1;
- (void)drawingCancelled;
@property _Bool drawingCommands; // @synthesize drawingCommands=_drawingCommands;
- (void)drawingEnded;
- (void)flushMemoryIfPossible;
- (struct CGRect)getContentsBoundsInCommandSpace;
- (id)init;
@property(readonly, nonatomic) ICDrawingInputController *inputController; // @synthesize inputController=_inputController;
@property(readonly, nonatomic) long long missedRenderCount; // @synthesize missedRenderCount=_missedRenderCount;
- (struct CGImage *)newCGImage;
- (void)performAsyncBlockOnRenderQueue:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) long long renderCount; // @synthesize renderCount=_renderCount;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *renderQueue; // @synthesize renderQueue=_renderQueue;
@property(nonatomic) struct CGSize renderSize; // @synthesize renderSize=_renderSize;
@property struct CGAffineTransform renderTransform; // @synthesize renderTransform=_renderTransform;
- (void)renderWithTransform:(struct CGAffineTransform)arg1;
@property(retain, nonatomic) ICDrawingRenderer *renderer; // @synthesize renderer=_renderer;
- (void)resetRenderCounts;
- (void)setPresentationLayer:(id)arg1;
@property struct CGAffineTransform transform; // @synthesize transform=_transform;
- (void)setup;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

