//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class CALayer, ICDrawingColorInfiniteScrollView, ICDrawingView, ICPageIndicatorView, NSArray, NSMutableDictionary, NSString, UIButton, UIColor, UIImage;

@interface ICDrawingToolsView : UIView <UIScrollViewDelegate>
{
    _Bool _showColors;
    _Bool _rulerSelected;
    unsigned int _state;
    UIImage *_selectedToolImage;
    UIView *_toolsView;
    UIView *_dockView;
    UIView *_aboveDockView;
    CALayer *_navigationBarLayer;
    NSArray *_colors;
    NSArray *_toolButtons;
    UIButton *_eraseButton;
    UIButton *_collapsedColorButton;
    NSArray *_colorButtons;
    ICDrawingColorInfiniteScrollView *_colorScrollView;
    ICPageIndicatorView *_pageIndicatorView;
    NSMutableDictionary *_colorButtonImages;
    NSMutableDictionary *_colorSelectedButtonImages;
    NSMutableDictionary *_toolDockMaskImages;
    ICDrawingView *_drawingView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *aboveDockView; // @synthesize aboveDockView=_aboveDockView;
- (id)accessibilityLabel;
- (_Bool)accessibilityScroll:(long long)arg1;
- (unsigned long long)accessibilityTraits;
- (double)allToolsWidth;
- (void)animateIn;
- (void)animateOut;
- (id)buttonImageForColor:(id)arg1 selected:(_Bool)arg2;
- (void)changeColor:(id)arg1;
- (void)changeTool:(id)arg1;
- (void)changeToolType:(unsigned int)arg1;
@property(retain, nonatomic) UIButton *collapsedColorButton; // @synthesize collapsedColorButton=_collapsedColorButton;
- (double)collapsedColorYOrigin;
@property(retain, nonatomic) NSMutableDictionary *colorButtonImages; // @synthesize colorButtonImages=_colorButtonImages;
@property(retain, nonatomic) NSArray *colorButtons; // @synthesize colorButtons=_colorButtons;
- (id)colorForIndex:(unsigned long long)arg1;
@property(retain, nonatomic) ICDrawingColorInfiniteScrollView *colorScrollView; // @synthesize colorScrollView=_colorScrollView;
@property(retain, nonatomic) NSMutableDictionary *colorSelectedButtonImages; // @synthesize colorSelectedButtonImages=_colorSelectedButtonImages;
@property(retain, nonatomic) NSArray *colors; // @synthesize colors=_colors;
- (id)dockColor;
@property(readonly, nonatomic) _Bool dockHasBorder;
@property(nonatomic) _Bool dockHidden;
@property(retain, nonatomic) UIView *dockView; // @synthesize dockView=_dockView;
@property(nonatomic) __weak ICDrawingView *drawingView; // @synthesize drawingView=_drawingView;
- (double)embossAlphaForColor:(id)arg1;
- (void)erase:(id)arg1;
@property(retain, nonatomic) UIButton *eraseButton; // @synthesize eraseButton=_eraseButton;
- (void)hideAllColors;
@property(readonly, nonatomic) struct CGSize idealSize;
- (id)imageNamed:(id)arg1 small:(_Bool)arg2;
- (id)initInDrawingView:(id)arg1 state:(unsigned int)arg2;
@property(readonly, nonatomic) _Bool isCollapsed;
- (_Bool)navigationBackgroundHidden;
@property(retain, nonatomic) CALayer *navigationBarLayer; // @synthesize navigationBarLayer=_navigationBarLayer;
@property(retain, nonatomic) ICPageIndicatorView *pageIndicatorView; // @synthesize pageIndicatorView=_pageIndicatorView;
- (double)paletteSpacing;
- (double)paletteTotalWidth;
- (void)positionToolsOffscreen;
- (unsigned int)previousTool;
@property(nonatomic) _Bool rulerSelected; // @synthesize rulerSelected=_rulerSelected;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) UIColor *selectedColor;
- (unsigned long long)selectedColorIndex;
@property(readonly, nonatomic) unsigned int selectedTool;
@property(retain, nonatomic) UIImage *selectedToolImage; // @synthesize selectedToolImage=_selectedToolImage;
- (void)setFrame:(struct CGRect)arg1;
- (void)setNavigationBackgroundHidden:(_Bool)arg1;
- (void)setPreviousTool:(unsigned int)arg1;
- (void)setSelectedColorIndex:(unsigned long long)arg1;
- (void)setSelectedTool:(unsigned int)arg1;
@property(nonatomic) _Bool showColors; // @synthesize showColors=_showColors;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(retain, nonatomic) NSArray *toolButtons; // @synthesize toolButtons=_toolButtons;
@property(retain, nonatomic) NSMutableDictionary *toolDockMaskImages; // @synthesize toolDockMaskImages=_toolDockMaskImages;
@property(retain, nonatomic) UIView *toolsView; // @synthesize toolsView=_toolsView;
- (void)setupColors;
- (void)setupDock;
- (void)setupTools;
@property(readonly, nonatomic) _Bool shouldUseLargeTools;
- (void)showAllColors:(id)arg1;
- (void)shrinkColorButtons;
- (unsigned long long)swatchFromIndex:(unsigned long long)arg1;
- (double)swatchHeight;
- (double)swatchTotalWidth;
- (double)swatchWidth;
- (void)toggleRuler:(id)arg1;
- (id)toolDockMaskImage:(unsigned long long)arg1;
- (double)toolHeight;
- (id)toolImage:(unsigned long long)arg1;
- (double)toolNotSelectedYOrigin;
- (void)toolPressed:(id)arg1;
- (double)toolSelectedYOrigin;
- (double)toolSpacing;
- (double)toolToSwatchSpacing;
- (void)toolUnpressed:(id)arg1;
- (void)updateColorButtons;
- (void)updateColorScrollView;
- (void)updateRulerButtonAccessibilityLabel;
- (void)updateToolButtons:(CDUnknownBlockType)arg1;
- (_Bool)useLargeColorsForState:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

