//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICAttachment, ICDrawingInputController, ICDrawingRendererController, ICDrawingView, NSMutableOrderedSet, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>;

@interface ICDrawingController : NSObject
{
    ICDrawingRendererController *_rendererController;
    ICAttachment *_attachment;
    _Bool _liveDrawing;
    unsigned long long _liveInteraction;
    ICDrawingView *_drawingView;
    NSObject<OS_dispatch_queue> *_previewQueue;
    _Bool _previewsSuspended;
    NSObject<OS_dispatch_queue> *_interactQueue;
    NSObject<OS_dispatch_semaphore> *_drawingSemaphore;
    NSObject<OS_dispatch_semaphore> *_interactSemaphore;
    NSMutableOrderedSet *_renderedCommands;
    long long _drawingOrientation;
    _Bool _cachedImageValid;
    struct CGImage *_cachedImage;
    _Bool _imageNeedsSave;
    _Bool _cancelRendering;
}

+ (id)sharedDrawingController;
- (void).cxx_destruct;
- (struct CGImage *)CGImage;
- (void)addNewRenderedCommand:(id)arg1;
- (struct CGImage *)cachedImage;
@property _Bool cancelRendering; // @synthesize cancelRendering=_cancelRendering;
- (void)claimForLiveDrawingWithAttachment:(id)arg1 inView:(id)arg2 finishedSetup:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)clearCachedImage;
- (void)dealloc;
- (void)didEndLiveInteraction;
- (void)didMergeDrawingAttachment:(id)arg1;
- (void)didRenderCommands:(id)arg1;
- (void)didStartLiveInteraction;
- (id)drawing;
- (void)drawingChanged;
- (void)handleImageState:(long long)arg1 forAttachment:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (id)image;
@property(nonatomic) _Bool imageNeedsSave; // @synthesize imageNeedsSave=_imageNeedsSave;
- (id)init;
@property(readonly, nonatomic) ICDrawingInputController *inputController;
- (void)interactRenderCommands:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)interactRenderImage:(struct CGImage *)arg1 forRenderedCommands:(id)arg2 thenRenderCommands:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)interactRenderImage:(struct CGImage *)arg1 forRenderedCommands:(id)arg2 thenRenderCommands:(id)arg3 inCommandSpaceClipRect:(struct CGRect)arg4 completion:(CDUnknownBlockType)arg5;
- (void)interactUpdateDrawing;
- (void)interactUpdateOrientation:(long long)arg1;
- (void)loadAttachmentImageCompletion:(CDUnknownBlockType)arg1;
- (void)performAsyncInteractBlock:(CDUnknownBlockType)arg1;
- (void)releaseClaimForLiveDrawingWithAttachment:(id)arg1 inView:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)renderAllInCommandSpaceRect:(struct CGRect)arg1 completion:(CDUnknownBlockType)arg2;
- (void)renderCommands:(id)arg1 clippedToCommandSpaceRect:(struct CGRect)arg2 completion:(CDUnknownBlockType)arg3;
- (void)renderCommands:(id)arg1 renderIntermediateSteps:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)renderImage:(struct UIImage *)arg1;
@property(readonly, nonatomic) NSMutableOrderedSet *renderedCommands; // @synthesize renderedCommands=_renderedCommands;
@property(readonly, nonatomic) ICDrawingRendererController *rendererController; // @synthesize rendererController=_rendererController;
- (void)resumeDrawing;
- (void)saveImageIfNeededUpdateChangeCount:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)saveImageImmediatelyIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)setAttachment:(id)arg1 loadedImage:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setAttachmentSaveImage:(id)arg1 loadedImage:(CDUnknownBlockType)arg2 waitForImageSave:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setCachedImage:(struct CGImage *)arg1;
- (void)sortRenderedCommands;
- (void)suspendDrawing;
- (void)updateDrawing:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updatePreviewsForAttachment:(id)arg1;
- (void)waitForPreviewsToFinish;

@end

