//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFreeTransformableAttachmentView.h"

#import "ICAttachmentPresentationDelegate.h"

@class CALayer, NSString, UIImage, UIViewController;

@interface ICDrawingLightView : ICFreeTransformableAttachmentView <ICAttachmentPresentationDelegate>
{
    UIViewController *_viewController;
    CALayer *_imageLayer;
}

- (void).cxx_destruct;
- (_Bool)canBecomeFirstResponder;
- (void)done;
@property(readonly, nonatomic) struct CGPoint drawingCenterOffset;
- (struct CGPoint)drawingCenterOffsetForSize:(struct CGSize)arg1;
- (struct CGRect)frameForFullscreenDrawing;
- (void)freeTransformGesture:(id)arg1;
@property(readonly, nonatomic) UIImage *image;
@property(readonly, nonatomic) struct CGRect imageFrame;
@property(retain, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setAttachment:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (id)undoManager;
- (void)updateLayerImageFrame;
- (struct UIView *)viewToPresentAttachmentFrom;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

