//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFreeTransformableViewController.h"

#import "UIDocumentInteractionControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class ICDrawingLightView, ICDrawingView, ICFreeTransformGestureRecognizer, ICSelectorDelayer, NSString, UIActivityIndicatorView, UIBarButtonItem;

@interface ICDrawingViewController : ICFreeTransformableViewController <UIGestureRecognizerDelegate, UIDocumentInteractionControllerDelegate>
{
    _Bool _editable;
    _Bool _pinchingFromSmallestState;
    _Bool _pinchValid;
    _Bool _didDismissViewController;
    UIBarButtonItem *_goToNoteButton;
    CDUnknownBlockType _endedDrawing;
    ICFreeTransformGestureRecognizer *_pinchGestureReconizer;
    UIBarButtonItem *_undoButton;
    UIBarButtonItem *_redoButton;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_fixedSpaceButtonRight;
    UIBarButtonItem *_fixedSpaceButtonLeft;
    UIBarButtonItem *_fixedSpaceButtonUndoRedo;
    UIBarButtonItem *_eraseAllButton;
    ICSelectorDelayer *_updateUndoRedoButtonsDelayer;
    UIBarButtonItem *_rotateButton;
    UIBarButtonItem *_sharrowButton;
    UIBarButtonItem *_loadingView;
    UIActivityIndicatorView *_activityView;
    ICDrawingLightView *_lightDrawingView;
    ICDrawingView *_drawingView;
    struct CGAffineTransform _pinchStartAffineTransform;
}

- (void).cxx_destruct;
- (_Bool)accessibilityPerformEscape;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
- (void)becomeActive;
- (_Bool)contentHidden;
- (void)dealloc;
@property(nonatomic) _Bool didDismissViewController; // @synthesize didDismissViewController=_didDismissViewController;
- (void)didReceiveMemoryWarning;
- (void)doneAction:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) ICDrawingView *drawingView; // @synthesize drawingView=_drawingView;
- (void)drawingViewIsReady;
- (void)drawingViewWillAppear;
- (void)endDrawingCallEndBlockIfNotInserting:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (struct CGAffineTransform)endTransform:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType endedDrawing; // @synthesize endedDrawing=_endedDrawing;
- (void)eraseAllAction:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *eraseAllButton; // @synthesize eraseAllButton=_eraseAllButton;
@property(retain, nonatomic) UIBarButtonItem *fixedSpaceButtonLeft; // @synthesize fixedSpaceButtonLeft=_fixedSpaceButtonLeft;
@property(retain, nonatomic) UIBarButtonItem *fixedSpaceButtonRight; // @synthesize fixedSpaceButtonRight=_fixedSpaceButtonRight;
@property(retain, nonatomic) UIBarButtonItem *fixedSpaceButtonUndoRedo; // @synthesize fixedSpaceButtonUndoRedo=_fixedSpaceButtonUndoRedo;
- (struct CGRect)frameForFullscreenAttachment;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
@property(retain, nonatomic) UIBarButtonItem *goToNoteButton; // @synthesize goToNoteButton=_goToNoteButton;
- (id)imageForTransition;
@property(nonatomic, getter=isEditable) _Bool editable; // @synthesize editable=_editable;
@property(retain, nonatomic) ICDrawingLightView *lightDrawingView; // @synthesize lightDrawingView=_lightDrawingView;
- (void)loadDrawingView;
- (void)loadView;
@property(retain, nonatomic) UIBarButtonItem *loadingView; // @synthesize loadingView=_loadingView;
- (id)newInteractiveTransition;
- (void)pinchGesture:(id)arg1;
@property(retain, nonatomic) ICFreeTransformGestureRecognizer *pinchGestureReconizer; // @synthesize pinchGestureReconizer=_pinchGestureReconizer;
@property(nonatomic) struct CGAffineTransform pinchStartAffineTransform; // @synthesize pinchStartAffineTransform=_pinchStartAffineTransform;
- (struct CGAffineTransform)pinchTransform:(id)arg1;
@property(nonatomic) _Bool pinchValid; // @synthesize pinchValid=_pinchValid;
@property(nonatomic) _Bool pinchingFromSmallestState; // @synthesize pinchingFromSmallestState=_pinchingFromSmallestState;
- (long long)preferredStatusBarUpdateAnimation;
- (_Bool)prefersStatusBarHidden;
- (void)redoAction:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *redoButton; // @synthesize redoButton=_redoButton;
- (void)resignActive;
- (void)rotateAction:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *rotateButton; // @synthesize rotateButton=_rotateButton;
- (void)setAttachment:(id)arg1;
- (void)setContentHidden:(_Bool)arg1;
@property(retain, nonatomic) UIBarButtonItem *sharrowButton; // @synthesize sharrowButton=_sharrowButton;
@property(retain, nonatomic) UIBarButtonItem *undoButton; // @synthesize undoButton=_undoButton;
@property(retain, nonatomic) ICSelectorDelayer *updateUndoRedoButtonsDelayer; // @synthesize updateUndoRedoButtonsDelayer=_updateUndoRedoButtonsDelayer;
- (void)shareAction:(id)arg1;
- (_Bool)shouldInsertDrawing;
@property(readonly, nonatomic) ICDrawingLightView *targetDrawingView;
- (void)traitCollectionDidChange:(id)arg1;
- (struct CGPoint)translationOffsetForTransform:(struct CGAffineTransform)arg1;
- (void)undoAction:(id)arg1;
- (id)undoManager;
- (void)undoStackDidChange:(id)arg1;
- (void)updateGLViewAccessibilityFrame;
- (void)updateLeftBarButtonItems;
- (void)updateRightBarButtonItems;
- (void)updateUndoRedoButtons;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

