//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICImagesAndMoviesBaseCell.h"

@interface ICDrawingCollectionViewCell : ICImagesAndMoviesBaseCell
{
}

- (_Bool)canBecomeFirstResponder;
- (unsigned long long)computedThumbnailLayout;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)respondToLongPressGesture:(id)arg1;
- (void)setAttachment:(id)arg1;

@end

