//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath;

@interface ICFetchedResultsControllerChange : NSObject
{
    id _object;
    unsigned long long _type;
    NSIndexPath *_indexPath;
    NSIndexPath *_theNewIndexPath;
}

- (void).cxx_destruct;
@property(retain) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain) id object; // @synthesize object=_object;
@property(retain) NSIndexPath *theNewIndexPath; // @synthesize theNewIndexPath=_theNewIndexPath;
@property unsigned long long type; // @synthesize type=_type;

@end

