//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ICFolderListViewController, NSString, UILabel;

@interface ICFolderListTableViewCell : UITableViewCell
{
    _Bool _needsToUpdateViews;
    ICFolderListViewController *_icaxParentFolderListViewController;
    UILabel *_titleLabel;
    UILabel *_noteCountLabel;
    NSString *_contentSizeCategory;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UILabel *_icaxNoteCountLabel;
@property(nonatomic) __weak ICFolderListViewController *_icaxParentFolderListViewController; // @synthesize _icaxParentFolderListViewController;
@property(readonly, nonatomic) UILabel *_icaxTitleLabel;
@property(copy, nonatomic) NSString *contentSizeCategory; // @synthesize contentSizeCategory=_contentSizeCategory;
- (void)contentSizeCategoryDidChange;
- (_Bool)hasTrashFolder;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) _Bool needsToUpdateViews; // @synthesize needsToUpdateViews=_needsToUpdateViews;
@property(retain, nonatomic) UILabel *noteCountLabel; // @synthesize noteCountLabel=_noteCountLabel;
- (void)prepareForReuse;
- (void)resetFolderNoteCountLabel;
- (void)setSelectionStyle:(long long)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)updateFonts;
- (void)updateLetterpress;
- (void)updateViewsForCurrentFolder;
- (void)updateViewsForCurrentFolderIfNecessary;
- (void)willMoveToWindow:(id)arg1;

@end

