//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ICFolderListViewController, NoteCollectionObject;

@protocol ICFolderListDelegate
- (void)folderList:(ICFolderListViewController *)arg1 didSelectNoteCollection:(NoteCollectionObject *)arg2 cellFrame:(struct CGRect)arg3;
- (void)folderList:(ICFolderListViewController *)arg1 didSelectNoteContainer:(id <ICNoteContainer>)arg2;
- (void)folderListDidCancel:(ICFolderListViewController *)arg1;
@end

