//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICScrollViewDelegateViewController.h"

#import "ICFolderListDelegate.h"
#import "ICNoteContainerCellDelegate.h"
#import "ICProgressIndicatorTrackerDelegate.h"
#import "NSFetchedResultsControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AccountUtilities, ICListTableView, ICNotesListViewController, ICProgressIndicatorTracker, NSArray, NSFetchedResultsController, NSMutableArray, NSString, NoteCollectionListController, NotesBackgroundView, UIAlertController, UIBarButtonItem, UITableView;

@interface ICFolderListViewController : ICScrollViewDelegateViewController <NSFetchedResultsControllerDelegate, UITableViewDataSource, UITableViewDelegate, ICFolderListDelegate, ICNoteContainerCellDelegate, ICProgressIndicatorTrackerDelegate>
{
    _Bool _hideLegacyAccounts;
    _Bool _needTableViewReload;
    _Bool _recreateFetchedResultsControllerOnReload;
    _Bool _legacyAccountsAreSortedOnTop;
    _Bool _blockIncrementalUpdates;
    _Bool _viewSetupDeferred;
    _Bool _observingLegacyNoteContext;
    unsigned long long _folderListMode;
    id <ICFolderListDelegate> _delegate;
    NSArray *_notesBeingMoved;
    ICNotesListViewController *_notesListViewController;
    NoteCollectionListController *_legacyNoteCollectionListController;
    NSFetchedResultsController *_fetchedResultsController;
    UIBarButtonItem *_addFolderButton;
    UIBarButtonItem *_editButton;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_flexibleSpaceItem;
    UIBarButtonItem *_trashButton;
    UIBarButtonItem *_cancelButton;
    UIBarButtonItem *_debugButton;
    ICListTableView *_tableView;
    unsigned long long _beginTableViewUpdatesCount;
    NSMutableArray *_legacyStoreHierarchy;
    AccountUtilities *_accountUtilities;
    UIAlertController *_editTitleAlert;
    ICProgressIndicatorTracker *_progressIndicatorTracker;
}

+ (_Bool)legacyAccountsShouldBeOnTop;
+ (id)visibleLegacyAccounts;
+ (id)visibleLegacyAccountsCheckDisabled:(_Bool)arg1;
- (void).cxx_destruct;
- (void)_icaxAnnounceCreatedFolder:(id)arg1;
- (void)_icaxAnnounceDeletedFolders:(id)arg1;
- (_Bool)_icaxDeleteSelectedFolders;
- (void)_icaxNoteContainerCellTitleWasTapped:(id)arg1;
@property(readonly, nonatomic) UITableView *_icaxTableView;
- (_Bool)accessibilityPerformEscape;
@property(nonatomic) __weak AccountUtilities *accountUtilities; // @synthesize accountUtilities=_accountUtilities;
- (void)accountsDidChange:(id)arg1;
- (void)accountsUpdated:(id)arg1;
- (void)addFolder:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *addFolderButton; // @synthesize addFolderButton=_addFolderButton;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)attachPalette;
@property(readonly, nonatomic) NotesBackgroundView *backgroundView;
@property(nonatomic) unsigned long long beginTableViewUpdatesCount; // @synthesize beginTableViewUpdatesCount=_beginTableViewUpdatesCount;
@property(nonatomic) _Bool blockIncrementalUpdates; // @synthesize blockIncrementalUpdates=_blockIncrementalUpdates;
- (_Bool)canBecomeFirstResponder;
- (void)cancel:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
- (id)cellForNewFolder;
- (id)cellForNoteContainerAtIndexPath:(id)arg1;
- (id)cloudKitAccountFromTableViewSectionIndex:(unsigned long long)arg1;
- (id)cloudKitManagedObjectContext;
- (id)cloudKitNoteContainerAtTableViewIndexPath:(id)arg1;
- (unsigned long long)cloudKitSectionForFetchedResultsFromTableViewSection:(unsigned long long)arg1;
- (id)cloudKitSectionInfoFromTableViewSectionIndex:(unsigned long long)arg1;
- (id)contentScrollView;
- (void)contentSizeCategoryDidChange;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controllerWillChangeContent:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) UIBarButtonItem *debugButton; // @synthesize debugButton=_debugButton;
@property(retain) id <ICFolderListDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteFolders:(id)arg1;
- (void)deleteFolders:(id)arg1 movingNotesToUnsortedFolder:(_Bool)arg2;
- (void)deleteSelectedFolders:(id)arg1;
- (void)deselectAll:(_Bool)arg1;
- (void)didStartCopyingLegacyAccountToCloudKit:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) UIBarButtonItem *editButton; // @synthesize editButton=_editButton;
@property(nonatomic) __weak UIAlertController *editTitleAlert; // @synthesize editTitleAlert=_editTitleAlert;
- (void)editTitleTextFieldChanged:(id)arg1;
- (void)endEditMode:(id)arg1;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
@property(retain, nonatomic) UIBarButtonItem *flexibleSpaceItem; // @synthesize flexibleSpaceItem=_flexibleSpaceItem;
- (void)folderList:(id)arg1 didSelectNoteCollection:(id)arg2 cellFrame:(struct CGRect)arg3;
- (void)folderList:(id)arg1 didSelectNoteContainer:(id)arg2;
- (void)folderListDidCancel:(id)arg1;
@property(nonatomic) unsigned long long folderListMode; // @synthesize folderListMode=_folderListMode;
- (void)handleAccessibilityDarkenColorsChangedNotification:(id)arg1;
@property(nonatomic) _Bool hideLegacyAccounts; // @synthesize hideLegacyAccounts=_hideLegacyAccounts;
- (id)indexPathForFolderInTableViewFromFetchedResultsControllerIndexPath:(id)arg1 managedObjectContext:(id)arg2;
- (id)init;
- (id)legacyAccountForTableViewSection:(unsigned long long)arg1;
@property(nonatomic) _Bool legacyAccountsAreSortedOnTop; // @synthesize legacyAccountsAreSortedOnTop=_legacyAccountsAreSortedOnTop;
- (id)legacyManagedObjectContext;
- (id)legacyNoteCollectionAtTableViewIndexPath:(id)arg1;
@property(retain) NoteCollectionListController *legacyNoteCollectionListController; // @synthesize legacyNoteCollectionListController=_legacyNoteCollectionListController;
- (void)legacyNotesChanged;
- (unsigned long long)legacySectionIndexFromTableViewSection:(unsigned long long)arg1;
- (id)legacySectionInfoDictFromTableViewSectionIndex:(unsigned long long)arg1;
@property(retain, nonatomic) NSMutableArray *legacyStoreHierarchy; // @synthesize legacyStoreHierarchy=_legacyStoreHierarchy;
- (void)migrationStateDidChange:(id)arg1;
- (void)migrationStateWillChange:(id)arg1;
- (void)modernNotesChanged:(id)arg1;
@property(nonatomic) _Bool needTableViewReload; // @synthesize needTableViewReload=_needTableViewReload;
- (void)noteCollectionCellTitleWasTapped:(id)arg1;
- (void)noteContainerCellTitleWasTapped:(id)arg1;
@property(retain, nonatomic) NSArray *notesBeingMoved; // @synthesize notesBeingMoved=_notesBeingMoved;
- (void)notesContextRefreshNotification:(id)arg1;
@property(retain) ICNotesListViewController *notesListViewController; // @synthesize notesListViewController=_notesListViewController;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(nonatomic) _Bool observingLegacyNoteContext; // @synthesize observingLegacyNoteContext=_observingLegacyNoteContext;
@property(retain, nonatomic) ICProgressIndicatorTracker *progressIndicatorTracker; // @synthesize progressIndicatorTracker=_progressIndicatorTracker;
- (void)progressIndicatorTrackerStartAnimation;
- (void)progressIndicatorTrackerStopAnimation;
- (void)promptToAddFolderToAccount:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)promptToAddFolderWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)promptToChooseAccountToAddFolderWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)promptToDeleteNonEmptyFolders:(id)arg1;
- (void)promptToEditTitle:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)promptToEditTitleForFolder:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (void)recreateFetchedResultsController;
@property(nonatomic) _Bool recreateFetchedResultsControllerOnReload; // @synthesize recreateFetchedResultsControllerOnReload=_recreateFetchedResultsControllerOnReload;
- (void)recreateLegacyHierarchy;
- (void)reloadDataAfterLegacyChanges;
- (void)reloadDataMaintainingSelection;
- (unsigned long long)sectionIndexFromButtonView:(id)arg1;
- (void)selectFirstLegacyAccount;
- (void)selectFirstModernAccount;
@property(retain, nonatomic) ICListTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIBarButtonItem *trashButton; // @synthesize trashButton=_trashButton;
@property(nonatomic) _Bool viewSetupDeferred; // @synthesize viewSetupDeferred=_viewSetupDeferred;
- (_Bool)shouldAutorotate;
- (_Bool)shouldDisableSelectionForNoteContainer:(id)arg1;
- (_Bool)shouldEnableEditButton;
- (_Bool)shouldShowNewFolderItem;
- (_Bool)shouldShowPalette;
- (_Bool)shouldShowUpdateOrCopyButtonForLegacyAccount:(id)arg1 outIsPrimaryAccount:(_Bool *)arg2;
- (void)showDebugMenu:(id)arg1;
- (void)showNoteCollection:(id)arg1;
- (void)showNoteContainer:(id)arg1;
- (void)showSingleButtonAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)splitViewControllerDidChangeHorizontalSizeClass:(id)arg1;
- (void)startEditMode:(id)arg1;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tearDownFetchedResultsController;
- (id)undoManager;
- (void)updateAccessoryViewForCellAtIndexPath:(id)arg1;
- (void)updateActivityIndicatorInAllSectionHeaderViews;
- (void)updateActivityIndicatorInSectionHeaderView:(id)arg1 section:(unsigned long long)arg2;
- (void)updateAllSectionHeaderViews;
- (void)updateBarButtonsAnimated:(_Bool)arg1;
- (void)updateNavigationTitle;
- (void)updateOrCopyLegacyAccount:(id)arg1;
- (void)updateSectionHeaderView:(id)arg1 section:(unsigned long long)arg2;
- (void)updateTitleForSectionHeaderView:(id)arg1 section:(unsigned long long)arg2;
- (void)updateViewByReloadingAccounts;
- (void)viewControllerWillStartEditModeNotification:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

