//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFolderListTableViewCell.h"

@interface ICFolderListTableViewCell (ICAccessibility_iOS)
- (_Bool)_accessibilitySupportsActivateAction;
- (_Bool)accessibilityActivate;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (void)icaxToggleCellSelection;
- (_Bool)isAccessibilityElement;
- (id)tableTextAccessibleLabel:(id)arg1;
@end

