//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIImageView, UILabel;

@interface ICFolderSelectorPaletteView : UIView
{
    NSArray *_notes;
    UILabel *_headingLabel;
    UILabel *_subheadingLabel;
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(retain) UILabel *headingLabel; // @synthesize headingLabel=_headingLabel;
- (id)headingStringForNotes:(id)arg1;
@property(retain) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)init;
- (id)initFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSArray *notes; // @synthesize notes=_notes;
- (id)previewImageForNotes:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(retain) UILabel *subheadingLabel; // @synthesize subheadingLabel=_subheadingLabel;
- (id)subheadingStringForNotes:(id)arg1;
- (void)updateImageAndLabels;

@end

