//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFolder.h"

#import "ICFolderUndoSupport.h"

@class NSArray, NSString;

@interface ICFolder (UndoSupport) <ICFolderUndoSupport>
@property(readonly, copy, nonatomic) NSArray *notesForCopying;
@property(readonly, copy, nonatomic) NSArray *subfoldersForCopying;
@property(readonly, copy, nonatomic) NSString *titleForCopying;
- (void)undoablySetParentFolder:(id)arg1;
- (void)undoablySetTitle:(id)arg1;
- (void)updateChangeCountRecursively;
@end

