//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerInteractiveTransitioning.h"

@class CALayer, NSString, UIView;

@interface ICFreeTransformInteractiveTransition : NSObject <UIViewControllerAnimatedTransitioning, UIViewControllerInteractiveTransitioning>
{
    _Bool _autoFinish;
    _Bool _postitionLayerUnderTopViewController;
    id <UIViewControllerContextTransitioning> _transitionContext;
    CALayer *_animatedImageLayer;
    CALayer *_animatedImageContentsLayer;
    CALayer *_inlineImageLayer;
    CALayer *_inlineImageContentsLayer;
    CALayer *_scrimLayer;
    long long _imageOrientation;
    UIView *_viewWithUserInteractionDisabled;
    struct CGPoint _originalOrigin;
}

- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
@property(retain, nonatomic) CALayer *animatedImageContentsLayer; // @synthesize animatedImageContentsLayer=_animatedImageContentsLayer;
@property(retain, nonatomic) CALayer *animatedImageLayer; // @synthesize animatedImageLayer=_animatedImageLayer;
- (void)animationEnded:(_Bool)arg1;
@property(nonatomic) _Bool autoFinish; // @synthesize autoFinish=_autoFinish;
- (void)cancelInteractiveTransition;
- (double)fadeDuration;
- (void)finishInteractiveTransition;
@property(nonatomic) long long imageOrientation; // @synthesize imageOrientation=_imageOrientation;
@property(retain, nonatomic) CALayer *inlineImageContentsLayer; // @synthesize inlineImageContentsLayer=_inlineImageContentsLayer;
@property(retain, nonatomic) CALayer *inlineImageLayer; // @synthesize inlineImageLayer=_inlineImageLayer;
@property(readonly, nonatomic) _Bool isTransitioningToFullscreen;
@property(nonatomic) struct CGPoint originalOrigin; // @synthesize originalOrigin=_originalOrigin;
- (void)performFinishAnimation;
- (void)performStartAnimation;
@property(nonatomic) _Bool postitionLayerUnderTopViewController; // @synthesize postitionLayerUnderTopViewController=_postitionLayerUnderTopViewController;
@property(retain, nonatomic) CALayer *scrimLayer; // @synthesize scrimLayer=_scrimLayer;
@property(nonatomic) __weak id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(nonatomic) __weak UIView *viewWithUserInteractionDisabled; // @synthesize viewWithUserInteractionDisabled=_viewWithUserInteractionDisabled;
- (void)setupImageOrientationForContentsRect:(struct CGRect)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)updateInteractiveTransition:(struct CGAffineTransform)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

