//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGestureRecognizer.h"

@class NSMapTable, NSMutableOrderedSet;

@interface ICFreeTransformGestureRecognizer : UIGestureRecognizer
{
    _Bool _allowSingleTouchDrag;
    _Bool _axisAligned;
    _Bool _canBegin;
    _Bool _isScaling;
    double _startThreshold;
    double _scaleThreshold;
    double _cancelThreshold;
    double _minScale;
    double _maxScale;
    double _scaleDamping;
    double _previousScale;
    NSMutableOrderedSet *_touches;
    double _deltaScale;
    NSMapTable *_touchStartLocations;
    NSMapTable *_actualTouchStartLocations;
    struct CGAffineTransform _accumulatedTransform;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGAffineTransform accumulatedTransform; // @synthesize accumulatedTransform=_accumulatedTransform;
@property(retain, nonatomic) NSMapTable *actualTouchStartLocations; // @synthesize actualTouchStartLocations=_actualTouchStartLocations;
@property(nonatomic) _Bool allowSingleTouchDrag; // @synthesize allowSingleTouchDrag=_allowSingleTouchDrag;
@property(nonatomic) _Bool axisAligned; // @synthesize axisAligned=_axisAligned;
@property(nonatomic) _Bool canBegin; // @synthesize canBegin=_canBegin;
@property(nonatomic) double cancelThreshold; // @synthesize cancelThreshold=_cancelThreshold;
- (struct CGAffineTransform)clampTransform:(struct CGAffineTransform)arg1 minScale:(double)arg2 maxScale:(double)arg3;
- (void)clearTouches;
@property(nonatomic) double deltaScale; // @synthesize deltaScale=_deltaScale;
@property(readonly, nonatomic) struct CGAffineTransform freeTransform;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
@property(nonatomic) _Bool isScaling; // @synthesize isScaling=_isScaling;
- (struct CGPoint)locationInView:(id)arg1;
@property(nonatomic) double maxScale; // @synthesize maxScale=_maxScale;
@property(nonatomic) double minScale; // @synthesize minScale=_minScale;
@property(nonatomic) double previousScale; // @synthesize previousScale=_previousScale;
- (void)reset;
- (void)resetAndAccumulateTransform;
- (void)resetStartingTouches;
@property(readonly, nonatomic) double scale;
@property(nonatomic) double scaleDamping; // @synthesize scaleDamping=_scaleDamping;
@property(readonly, nonatomic) _Bool scaleIsGrowing;
@property(readonly, nonatomic) _Bool scaleIsShrinking;
@property(nonatomic) double scaleThreshold; // @synthesize scaleThreshold=_scaleThreshold;
@property(nonatomic) double startThreshold; // @synthesize startThreshold=_startThreshold;
@property(retain, nonatomic) NSMapTable *touchStartLocations; // @synthesize touchStartLocations=_touchStartLocations;
@property(readonly, nonatomic) NSMutableOrderedSet *touches; // @synthesize touches=_touches;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (_Bool)touchesMovedPastScaleThreshold:(double)arg1;
- (_Bool)touchesMovedPastThreshold:(double)arg1;
@property(readonly, nonatomic) struct CGAffineTransform unscaledFreeTransform;

@end

