//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAttachmentView.h"

@class ICFreeTransformGestureRecognizer, ICFreeTransformableViewController;

@interface ICFreeTransformableAttachmentView : ICAttachmentView
{
    ICFreeTransformGestureRecognizer *_freeTransformGestureRecognizer;
    ICFreeTransformableViewController *_freeTransformableViewController;
}

- (void).cxx_destruct;
- (void)didTapAttachment:(id)arg1;
- (void)freeTransformGesture:(id)arg1;
@property(retain, nonatomic) ICFreeTransformGestureRecognizer *freeTransformGestureRecognizer; // @synthesize freeTransformGestureRecognizer=_freeTransformGestureRecognizer;
@property(nonatomic) __weak ICFreeTransformableViewController *freeTransformableViewController; // @synthesize freeTransformableViewController=_freeTransformableViewController;
- (id)newNavigationController;
- (void)setupFreeTransformGesture;
- (_Bool)supportsFreeTransformGesture;

@end

