//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICPeerInputStreamDelegate.h"
#import "ICPeerMessageControllerDelegate.h"

@class ICPeerInputStream, ICPeerMessageController, ICPeerOutputStream, NSString;

@interface ICHandoffController : NSObject <ICPeerMessageControllerDelegate, ICPeerInputStreamDelegate>
{
    ICPeerInputStream *_inputStream;
    ICPeerOutputStream *_outputStream;
    ICPeerMessageController *_peerController;
}

+ (id)sharedController;
- (void).cxx_destruct;
- (void)didDisconnectInputStream:(id)arg1;
- (void)didReceiveInputStream:(id)arg1 outputStream:(id)arg2;
- (void)handleMessage:(id)arg1 fromInputStream:(id)arg2;
- (id)init;
@property(retain) ICPeerInputStream *inputStream;
- (void)noteContext:(id)arg1 sendDeltasForNote:(id)arg2;
@property(retain) ICPeerOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain) ICPeerMessageController *peerController; // @synthesize peerController=_peerController;
- (void)requestNoteWithIdentifier:(id)arg1 folderIdentifier:(id)arg2 folderName:(id)arg3;
- (void)sendMedia:(id)arg1 toSource:(id)arg2;
- (_Bool)sendMessage:(id)arg1 toSource:(id)arg2 error:(id *)arg3;
- (void)setDevice:(id)arg1 forSource:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

