//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSFetchedResultsController, NSMutableArray, NSString, NotesTextureBackgroundView, UICollectionView, UICollectionViewFlowLayout, UIViewController;

@interface ICImagesAndMoviesScrollView : UIView <NSFetchedResultsControllerDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    _Bool _scrollViewDecelerating;
    short _attachmentSection;
    UIViewController *_viewController;
    UICollectionView *_collectionView;
    NotesTextureBackgroundView *_textureBackgroundView;
    NotesTextureBackgroundView *_topTextureView;
    NSFetchedResultsController *_fetchedResultsController;
    NSMutableArray *_changesFromFetchedResultsController;
}

- (void).cxx_destruct;
- (void)accountsDidChange:(id)arg1;
@property(nonatomic) short attachmentSection; // @synthesize attachmentSection=_attachmentSection;
@property(retain, nonatomic) NSMutableArray *changesFromFetchedResultsController; // @synthesize changesFromFetchedResultsController=_changesFromFetchedResultsController;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (_Bool)collectionView:(id)arg1 canPerformAction:(SEL)arg2 forItemAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 performAction:(SEL)arg2 forItemAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)collectionView:(id)arg1 shouldShowMenuForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
@property(readonly, nonatomic) UICollectionViewFlowLayout *collectionViewFlowLayout;
- (void)commonInitForAttachmentSection:(short)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (id)initForAttachmentSection:(short)arg1;
- (id)initWithFrame:(struct CGRect)arg1 forAttachmentSection:(short)arg2;
- (void)layoutSubviews;
- (void)notesContextRefreshNotification:(id)arg1;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)recreateFetchedResultsController;
- (void)respondToTapGesture:(id)arg1;
@property(nonatomic) long long scrollDirection;
@property(nonatomic) _Bool scrollViewDecelerating; // @synthesize scrollViewDecelerating=_scrollViewDecelerating;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(retain, nonatomic) NotesTextureBackgroundView *textureBackgroundView; // @synthesize textureBackgroundView=_textureBackgroundView;
- (void)setTexturedBackground;
@property(retain, nonatomic) NotesTextureBackgroundView *topTextureView; // @synthesize topTextureView=_topTextureView;
@property(nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
- (unsigned long long)thumbnailLayout;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateCollectionViewItemSizeAndFrame;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

