//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIViewControllerPreviewingDelegate_Deprecated.h"

@class ICImagesAndMoviesScrollView, NSString;

@interface ICImagesAndMoviesBrowserController : UIViewController <UIViewControllerPreviewingDelegate_Deprecated>
{
    short _attachmentSection;
    ICImagesAndMoviesScrollView *_scrollView;
}

- (void).cxx_destruct;
@property(nonatomic) short attachmentSection; // @synthesize attachmentSection=_attachmentSection;
- (id)collectionViewCellAtPosition:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (void)commitPreviewViewController:(id)arg1 committedViewController:(id)arg2;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (id)initWithAttachmentSection:(short)arg1;
- (void)loadView;
- (id)previewViewControllerForLocation:(struct CGPoint)arg1 inSourceView:(id)arg2;
@property(retain, nonatomic) ICImagesAndMoviesScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)viewDidLoad;
- (void)willPresentPreviewViewController:(id)arg1 forLocation:(struct CGPoint)arg2 inSourceView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

