//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class ICFolder, NSArray;

@interface ICImportLegacyNotesOperation : NSOperation
{
    _Bool _deleteLegacyNotesAfterImport;
    ICFolder *_destinationFolder;
    NSArray *_legacyNotes;
}

- (void).cxx_destruct;
- (void)cancelIfNecessary;
@property(nonatomic) _Bool deleteLegacyNotesAfterImport; // @synthesize deleteLegacyNotesAfterImport=_deleteLegacyNotesAfterImport;
- (id)description;
@property(retain, nonatomic) ICFolder *destinationFolder; // @synthesize destinationFolder=_destinationFolder;
- (id)ensureLegacyNoteIsValid:(id)arg1;
- (id)init;
- (id)initWithLegacyNotes:(id)arg1 destinationFolder:(id)arg2 deleteLegacyNotesAfterImport:(_Bool)arg3;
- (id)legacyManagedObjectContext;
@property(copy, nonatomic) NSArray *legacyNotes; // @synthesize legacyNotes=_legacyNotes;
- (void)main;

@end

