//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAttachmentNavigationController.h"

@class ICImageViewController;

@interface ICImageNavigationController : ICAttachmentNavigationController
{
    id <ICImageAttachmentPresentationDelegate> _imageAttachmentPresentationDelegate;
    ICImageViewController *_imageViewController;
}

- (void).cxx_destruct;
- (struct CGRect)contentsRectForInlineAttachment;
- (struct CGRect)frameForFullscreenAttachmentInView:(id)arg1;
- (id)freeTransformableViewController;
@property(nonatomic) __weak id <ICImageAttachmentPresentationDelegate> imageAttachmentPresentationDelegate; // @synthesize imageAttachmentPresentationDelegate=_imageAttachmentPresentationDelegate;
- (id)imageForTransition;
@property(retain, nonatomic) ICImageViewController *imageViewController; // @synthesize imageViewController=_imageViewController;
- (id)initWithImageAttachmentPresentationDelegate:(id)arg1;
- (id)scrimColor;
- (_Bool)shouldHideStatusBar;

@end

