//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFreeTransformableViewController.h"

#import "UIDocumentInteractionControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class ICFreeTransformGestureRecognizer, ICNoTransformImageView, NSString, NotesBackgroundView, UIImage, UIScrollView;

@interface ICImageViewController : ICFreeTransformableViewController <UIScrollViewDelegate, UIGestureRecognizerDelegate, UIDocumentInteractionControllerDelegate>
{
    _Bool _inSizeChange;
    _Bool _inDoubleTapZoom;
    _Bool _imageIsSmallerThanView;
    _Bool _didUpdatePinchGestureRecognizer;
    _Bool _pinchingFromSmallestState;
    _Bool _didDismissViewController;
    UIImage *_image;
    ICNoTransformImageView *_imageView;
    id <ICAttachmentPresentationDelegate> _attachmentPresentationDelegate;
    UIScrollView *_scrollView;
    double _minZoomScale;
    double _maxZoomScale;
    double _pinchMaxZoomScale;
    ICFreeTransformGestureRecognizer *_freeTransformGestureRecognizer;
}

- (void).cxx_destruct;
@property __weak id <ICAttachmentPresentationDelegate> attachmentPresentationDelegate; // @synthesize attachmentPresentationDelegate=_attachmentPresentationDelegate;
- (id)backgroundTextureView;
@property(readonly, nonatomic) NotesBackgroundView *backgroundView;
- (_Bool)contentHidden;
- (void)dealloc;
@property(nonatomic) _Bool didDismissViewController; // @synthesize didDismissViewController=_didDismissViewController;
- (void)didReceiveMemoryWarning;
@property(nonatomic) _Bool didUpdatePinchGestureRecognizer; // @synthesize didUpdatePinchGestureRecognizer=_didUpdatePinchGestureRecognizer;
- (void)dismiss;
- (void)doneAction:(id)arg1;
@property(retain, nonatomic) ICFreeTransformGestureRecognizer *freeTransformGestureRecognizer; // @synthesize freeTransformGestureRecognizer=_freeTransformGestureRecognizer;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void)imageDoubleTapGesture:(id)arg1;
@property(nonatomic) _Bool imageIsSmallerThanView; // @synthesize imageIsSmallerThanView=_imageIsSmallerThanView;
@property(retain, nonatomic) ICNoTransformImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool inDoubleTapZoom; // @synthesize inDoubleTapZoom=_inDoubleTapZoom;
@property(nonatomic) _Bool inSizeChange; // @synthesize inSizeChange=_inSizeChange;
- (void)loadView;
- (void)markupAction:(id)arg1;
@property(nonatomic) double maxZoomScale; // @synthesize maxZoomScale=_maxZoomScale;
- (double)maxZoomScaleForImageSize:(struct CGSize)arg1;
@property(nonatomic) double minZoomScale; // @synthesize minZoomScale=_minZoomScale;
- (void)pinchGesture:(id)arg1;
@property(nonatomic) double pinchMaxZoomScale; // @synthesize pinchMaxZoomScale=_pinchMaxZoomScale;
@property(nonatomic) _Bool pinchingFromSmallestState; // @synthesize pinchingFromSmallestState=_pinchingFromSmallestState;
- (_Bool)prefersStatusBarHidden;
- (void)resetScaleToMinimum;
- (void)resetZoomScale;
- (id)scrimColor;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)setContentHidden:(_Bool)arg1;
- (void)shareAction:(id)arg1;
- (void)singleTapGesture:(id)arg1;
- (void)toggleNavigationBarHidden;
- (void)updateToolbars;
- (void)updateZoomScales;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (struct CGRect)zoomRectForScale:(double)arg1 withCenter:(struct CGPoint)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

