//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ICLabel, NSLayoutConstraint, NSMutableDictionary, UIColor, UIImage, UIImageView;

@interface ICImageAndMovieThumbnailView : UIView
{
    _Bool _showAsMovie;
    _Bool _hairlineWidthUnitIsInPoint;
    _Bool _showMovieDuration;
    unsigned long long _imageScaling;
    struct UIColor *_borderColor;
    unsigned long long _hairlineEdges;
    unsigned long long _edgesToRemoveStartPoint;
    unsigned long long _edgesToRemoveEndPoint;
    struct UIImageView *_imageView;
    NSLayoutConstraint *_imageViewLeftLayoutConstraint;
    NSLayoutConstraint *_imageViewRightLayoutConstraint;
    NSLayoutConstraint *_imageViewBottomLayoutConstraint;
    NSLayoutConstraint *_imageViewTopLayoutConstraint;
    struct UIImageView *_movieFooter;
    ICLabel *_movieDurationLabel;
    NSMutableDictionary *_hairlineLayers;
    NSMutableDictionary *_hairlineColors;
    CDStruct_1b6d18a9 _movieDuration;
}

- (void).cxx_destruct;
- (double)backingScale;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
- (void)commonInit;
@property(nonatomic) double cornerRadius; // @dynamic cornerRadius;
@property(nonatomic) unsigned long long edgesToRemoveEndPoint; // @synthesize edgesToRemoveEndPoint=_edgesToRemoveEndPoint;
@property(nonatomic) unsigned long long edgesToRemoveStartPoint; // @synthesize edgesToRemoveStartPoint=_edgesToRemoveStartPoint;
- (struct CGRect)frameByApplyingHorizontalReductionTo:(struct CGRect)arg1 edge:(unsigned long long)arg2;
- (struct CGRect)frameByApplyingVerticalReductionTo:(struct CGRect)arg1 edge:(unsigned long long)arg2;
@property(retain, nonatomic) NSMutableDictionary *hairlineColors; // @synthesize hairlineColors=_hairlineColors;
@property(nonatomic) unsigned long long hairlineEdges; // @synthesize hairlineEdges=_hairlineEdges;
- (id)hairlineLayerForEdge:(unsigned long long)arg1;
@property(retain, nonatomic) NSMutableDictionary *hairlineLayers; // @synthesize hairlineLayers=_hairlineLayers;
- (double)hairlineWidthInPoint;
@property(nonatomic) _Bool hairlineWidthUnitIsInPoint; // @synthesize hairlineWidthUnitIsInPoint=_hairlineWidthUnitIsInPoint;
@property(retain, nonatomic) UIImage *image; // @dynamic image;
@property(nonatomic) double imageInset; // @dynamic imageInset;
@property(nonatomic) unsigned long long imageScaling; // @synthesize imageScaling=_imageScaling;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSLayoutConstraint *imageViewBottomLayoutConstraint; // @synthesize imageViewBottomLayoutConstraint=_imageViewBottomLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *imageViewLeftLayoutConstraint; // @synthesize imageViewLeftLayoutConstraint=_imageViewLeftLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *imageViewRightLayoutConstraint; // @synthesize imageViewRightLayoutConstraint=_imageViewRightLayoutConstraint;
@property(retain, nonatomic) NSLayoutConstraint *imageViewTopLayoutConstraint; // @synthesize imageViewTopLayoutConstraint=_imageViewTopLayoutConstraint;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 showMovieDuration:(_Bool)arg2;
@property(nonatomic) CDStruct_1b6d18a9 movieDuration; // @synthesize movieDuration=_movieDuration;
@property(retain, nonatomic) ICLabel *movieDurationLabel; // @synthesize movieDurationLabel=_movieDurationLabel;
@property(retain, nonatomic) UIImageView *movieFooter; // @synthesize movieFooter=_movieFooter;
- (double)pixelWidth;
- (void)setBounds:(struct CGRect)arg1;
- (void)setHairlineColor:(struct UIColor *)arg1 forEdges:(unsigned long long)arg2;
@property(nonatomic) _Bool showAsMovie; // @synthesize showAsMovie=_showAsMovie;
@property(nonatomic) _Bool showMovieDuration; // @synthesize showMovieDuration=_showMovieDuration;
- (id)setupMovieFooter;
- (void)updateDurationLabel;
- (void)updateHairline;
- (void)updateHairlineFrames;
- (_Bool)usesSeparateLayerForHairlineEdge:(unsigned long long)arg1;
- (_Bool)usesSeparateLayersForHairlines;

@end

