//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICBrowseAttachmentsBaseCell.h"

@class NSArray, UIView;

@interface ICImagesAndMoviesBaseCell : ICBrowseAttachmentsBaseCell
{
    UIView *_thumbnailView;
    unsigned long long _thumbnailLayout;
    NSArray *_ourConstraints;
    double _aspectRatio;
}

- (void).cxx_destruct;
@property(nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
- (unsigned long long)computedThumbnailLayout;
- (void)dealloc;
- (void)didMoveToWindow;
- (id)initWithThumbnailView:(id)arg1 frame:(struct CGRect)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(copy, nonatomic) NSArray *ourConstraints; // @synthesize ourConstraints=_ourConstraints;
- (void)setAttachment:(id)arg1;
@property(nonatomic) unsigned long long thumbnailLayout; // @synthesize thumbnailLayout=_thumbnailLayout;
@property(retain, nonatomic) UIView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void)updateAspectRatio;
- (void)updateConstraints;

@end

