//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class ICAccount, ICNoteContext, NSMutableDictionary, NSString;

@interface ICImportLegacyAccountOperation : NSOperation
{
    _Bool _randomizeImportOrder;
    _Bool _copyingPrimaryAccount;
    _Bool _renameFolders;
    ICAccount *_destinationAccount;
    NSString *_legacyAccountIdentifier;
    ICNoteContext *_noteContext;
    NSMutableDictionary *_legacyNoteIntegerIdToNoteIdentifierDict;
}

+ (void)ensurePermanentObjectIDForObject:(id)arg1;
- (void).cxx_destruct;
- (void)cancelIfAccountWasDeleted;
- (void)copyChangesForDefaultFolder;
@property(retain, nonatomic) ICAccount *destinationAccount; // @synthesize destinationAccount=_destinationAccount;
- (id)ensureLegacyNoteIsValid:(id)arg1;
- (id)existingImportedNoteForLegacyNote:(id)arg1 withContentHash:(id)arg2 identifier:(id)arg3;
- (id)hashFromAttributedString:(id)arg1;
- (long long)importChoiceForLegacyNote:(id)arg1 withContentHash:(id)arg2 identifier:(id)arg3 existingImportedNote:(id)arg4;
- (id)importFolderForLegacyFolder:(id)arg1;
- (id)importLegacyNote:(id)arg1 deviceMigrationIdentifier:(id)arg2 inGroup:(id)arg3;
- (id)initWithLegacyAccount:(id)arg1 destinationAccount:(id)arg2 renameFolders:(_Bool)arg3;
@property(nonatomic, getter=isCopyingPrimaryAccount) _Bool copyingPrimaryAccount; // @synthesize copyingPrimaryAccount=_copyingPrimaryAccount;
- (_Bool)isLegacyNoteADuplicate:(id)arg1;
@property(readonly, nonatomic) id <ICLegacyAccount> legacyAccount;
@property(retain, nonatomic) NSString *legacyAccountIdentifier; // @synthesize legacyAccountIdentifier=_legacyAccountIdentifier;
- (id)legacyManagedObjectContext;
@property(retain, nonatomic) NSMutableDictionary *legacyNoteIntegerIdToNoteIdentifierDict; // @synthesize legacyNoteIntegerIdToNoteIdentifierDict=_legacyNoteIntegerIdToNoteIdentifierDict;
- (void)main;
@property(retain, nonatomic) ICNoteContext *noteContext; // @synthesize noteContext=_noteContext;
@property(nonatomic) _Bool randomizeImportOrder; // @synthesize randomizeImportOrder=_randomizeImportOrder;
@property(nonatomic) _Bool renameFolders; // @synthesize renameFolders=_renameFolders;

@end

