//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutManager.h"

#import "ICTrackedAttributeDelegate.h"

@class ICTextController, NSMutableDictionary, NSTextContainer, UITextView;

@interface ICLayoutManager : NSLayoutManager <ICTrackedAttributeDelegate>
{
    _Bool _shouldManuallyRenderSeparateSubviews;
    _Bool _needsClearRemovedAttachments;
    _Bool _layoutIsDrawingText;
    NSLayoutManager *_layoutManagerForRenderingSeparateSubviews;
    UITextView *_textView;
    NSMutableDictionary *_todoButtonsByTrackingUUID;
    struct CGPoint _cachedOrigin;
    struct _NSRange _lastVisibleRange;
    struct CGSize _cachedTextContainerSize;
}

- (void).cxx_destruct;
- (void)_clearRemovedAttachments;
- (void)attachmentDidLoad:(id)arg1;
@property(nonatomic) struct CGPoint cachedOrigin; // @synthesize cachedOrigin=_cachedOrigin;
@property(nonatomic) struct CGSize cachedTextContainerSize; // @synthesize cachedTextContainerSize=_cachedTextContainerSize;
- (void)clearAllAttachments;
- (void)clearAllTodos;
- (void)clearRemovedAttachmentsIfNeeded;
- (void)contentSizeCategoryDidChange;
- (void)dealloc;
- (void)didPressTodoButton:(id)arg1;
- (void)drawBulletsForListRange:(struct _NSRange)arg1 paragraphStyle:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)drawGlyphsForGlyphRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (void)drawGlyphsForGlyphRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2 updateAttachments:(_Bool)arg3;
- (void)drawListStylesForCharacterRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (void)drawTodoViewForListRange:(struct _NSRange)arg1 paragraphStyle:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)ensureViewIsAddedForAttachment:(id)arg1 inCharacterRange:(struct _NSRange)arg2;
- (void)enumerateAttachmentViewsInRange:(struct _NSRange)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)icReplaceTextStorage:(id)arg1;
- (id)icTextView;
- (id)icaxTodoButtonForParagraphStyle:(id)arg1;
- (id)init;
- (void)invalidateLastVisibleRange;
- (void)invalidateLayoutForAttachment:(id)arg1;
@property(nonatomic) struct _NSRange lastVisibleRange; // @synthesize lastVisibleRange=_lastVisibleRange;
@property(nonatomic) _Bool layoutIsDrawingText; // @synthesize layoutIsDrawingText=_layoutIsDrawingText;
@property(nonatomic) __weak NSLayoutManager *layoutManagerForRenderingSeparateSubviews; // @synthesize layoutManagerForRenderingSeparateSubviews=_layoutManagerForRenderingSeparateSubviews;
- (struct CGRect)lineFragmentRectForGlyphAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
- (struct CGRect)lineRectForRange:(struct _NSRange)arg1;
- (void)manuallyRenderSubviewsForCharacterRange:(struct _NSRange)arg1;
- (void)mediaDidLoad:(id)arg1;
@property(nonatomic) _Bool needsClearRemovedAttachments; // @synthesize needsClearRemovedAttachments=_needsClearRemovedAttachments;
- (void)processEditingForTextStorage:(id)arg1 edited:(unsigned long long)arg2 range:(struct _NSRange)arg3 changeInLength:(long long)arg4 invalidatedRange:(struct _NSRange)arg5;
- (struct _NSRange)rangeForAttachment:(id)arg1 withTextAttachment:(id *)arg2;
- (void)removeAllTodoButtonsFromSuperview;
- (void)restoreSavedSubviews:(id)arg1;
- (id)savedSeparateSubviewsForCharacterRange:(struct _NSRange)arg1;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) _Bool shouldManuallyRenderSeparateSubviews; // @synthesize shouldManuallyRenderSeparateSubviews=_shouldManuallyRenderSeparateSubviews;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSMutableDictionary *todoButtonsByTrackingUUID; // @synthesize todoButtonsByTrackingUUID=_todoButtonsByTrackingUUID;
@property(readonly, nonatomic) NSTextContainer *textContainer;
- (void)textContainerChangedGeometry:(id)arg1;
- (id)textContainerForGlyphAtIndex:(unsigned long long)arg1 effectiveRange:(struct _NSRange *)arg2;
@property(readonly, nonatomic) ICTextController *textController;
- (void)textController:(id)arg1 addedTrackedAttribute:(id)arg2;
- (void)textController:(id)arg1 removedTrackedAttribute:(id)arg2;
- (void)textController:(id)arg1 updatedTrackedAttribute:(id)arg2;
- (void)textStorageDidEndEditingNotification:(id)arg1;
- (void)updateFrameOfViewForAttachment:(id)arg1 inCharacterRange:(struct _NSRange)arg2 atPoint:(struct CGPoint)arg3;
- (void)updateFramesOfAttachments;
- (void)updateSubviewsForCharacterRange:(struct _NSRange)arg1;
- (void)updateSubviewsForCharacterRange:(struct _NSRange)arg1 atPoint:(struct CGPoint)arg2;
- (void)updateVisibleAttachmentViews;
- (struct CGRect)usedLineRectForRange:(struct _NSRange)arg1;

@end

