//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class UITapGestureRecognizer, UIViewController;

@interface ICLearnMoreTextView : UITextView
{
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIViewController *_parentViewController;
}

- (void).cxx_destruct;
- (_Bool)_accessibilityHasTextOperations;
- (_Bool)accessibilityActivate;
- (id)accessibilityHint;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (void)dealloc;
- (void)didTapLearnMore;
@property(nonatomic) __weak UIViewController *parentViewController; // @synthesize parentViewController=_parentViewController;
- (void)resetTextView;
- (void)setAttributedText:(id)arg1 font:(id)arg2 lineSpacing:(double)arg3 addLearnMore:(_Bool)arg4;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
- (void)setText:(id)arg1 font:(id)arg2 color:(id)arg3 lineSpacing:(double)arg4 addLearnMore:(_Bool)arg5;
- (void)tapGesture:(id)arg1;

@end

