//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface ICLegacyImportManager : NSObject
{
    NSOperationQueue *_operationQueue;
}

+ (id)sharedLegacyImportManager;
- (void).cxx_destruct;
- (_Bool)hasPendingOperations;
- (id)init;
- (void)moveLegacyNotes:(id)arg1 toFolder:(id)arg2;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;

@end

