//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectContext, NSManagedObjectID, NSSet, NSString;

@protocol ICLegacyAccount <NSObject>
- (NSString *)accountIdentifier;
- (id <ICLegacyFolder>)defaultFolder;
- (NSString *)emailAddress;
- (NSSet *)folders;
- (NSManagedObjectContext *)managedObjectContext;
- (NSString *)name;
- (NSManagedObjectID *)objectID;
- (NSString *)objectIdentifier;
- (_Bool)supportsAttachments;
@end

