//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNoteBaseActivityItemSource.h"

#import "UIActivityItemSource.h"

@class NSString;

@interface ICLegacyNoteStringActivityItemSource : ICNoteBaseActivityItemSource <UIActivityItemSource>
{
    NSString *_content;
    NSString *_plainText;
}

- (void).cxx_destruct;
- (id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
- (id)activityViewControllerPlaceholderItem:(id)arg1;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (id)initWithTitle:(id)arg1 content:(id)arg2 plainText:(id)arg3;
@property(copy, nonatomic) NSString *plainText; // @synthesize plainText=_plainText;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

