//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MKMapViewDelegate.h"

@class MKLocalSearch, MKMapItem, MKMapView, NSString, _MKPlaceViewController;

@interface ICMapViewController : UIViewController <MKMapViewDelegate>
{
    id <MKAnnotation> _annotation;
    MKMapView *_mapView;
    MKMapItem *_mapItem;
    _MKPlaceViewController *_mapViewController;
    MKLocalSearch *_localSearch;
}

- (void)_toolbarItemPressed:(id)arg1;
@property(retain, nonatomic) id <MKAnnotation> annotation; // @synthesize annotation=_annotation;
- (void)dealloc;
- (id)initWithAnnotation:(id)arg1;
- (void)loadView;
@property(retain, nonatomic) MKLocalSearch *localSearch; // @synthesize localSearch=_localSearch;
@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
@property(retain, nonatomic) _MKPlaceViewController *mapViewController; // @synthesize mapViewController=_mapViewController;
- (id)previewMenuItems;
- (void)selectPin;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)wantsFullScreenLayout;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

