//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSOperationQueue, NSTimer;

@interface ICMigrationController : NSObject
{
    NSOperationQueue *_operationQueue;
    NSMutableDictionary *_numberOfRetriesBySelector;
    NSTimer *_repeatingImportTimer;
}

+ (struct NoteAccountObject *)accountForAccountIdentifier:(id)arg1;
+ (void)continueMigrationIfNecessary;
+ (short)currentMigrationState;
+ (_Bool)didChooseToMigrateLocalAccount;
+ (_Bool)didMigrateLocalAccount;
+ (struct NoteAccountObject *)ensureLegacyAccountIsValid:(struct NoteAccountObject *)arg1;
+ (void)initialize;
+ (struct NoteContext *)legacyAccountContext;
+ (struct NoteAccountObject *)legacyAccountForPrimaryICloudAccount;
+ (id)legacyAccountNameForPrimaryICloudAccount;
+ (id)legacyAccountsBeingCopied;
+ (id)legacyLocalAccount;
+ (void)migrateLocalAccountIfNecessary;
+ (id)migrationDeviceIdentifier;
+ (void)pushMigrationStateToCloud;
+ (void)setCurrentMigrationState:(short)arg1;
+ (void)setDidChooseToMigrateLocalAccount:(_Bool)arg1;
+ (void)setDidMigrateLocalAccount:(_Bool)arg1;
+ (id)sharedController;
+ (_Bool)sharedControllerExists;
+ (_Bool)shouldHideICloudIMAPAccount;
+ (id)stringFromMigrationState:(short)arg1;
- (void).cxx_destruct;
- (void)accountsDidChange:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)cancelAllOperationsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)clearRetryCountForSelector:(SEL)arg1;
- (void)continueMigrationForICloudAccount;
- (void)copyNotesFromLegacyAccount:(struct NoteAccountObject *)arg1 toAccount:(id)arg2;
- (id)database;
- (void)dealloc;
- (void)disableLegacyAccount:(id)arg1;
- (void)disableNotesForACAccount:(id)arg1 inStore:(id)arg2;
- (void)handleDarwinNotificationName:(id)arg1;
- (id)importLegacyNotesForICloudAccountWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)importNotesFromLegacyAccount:(id)arg1 toAccount:(id)arg2 renameFolders:(_Bool)arg3 isPrimaryAccount:(_Bool)arg4 withCompletionHandler:(CDUnknownBlockType)arg5;
- (id)init;
- (_Bool)isInternetReachable;
- (id)legacyAccountIdentifiersBeingCopied;
- (void)migrationStateDidChange:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *numberOfRetriesBySelector; // @synthesize numberOfRetriesBySelector=_numberOfRetriesBySelector;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)performFinalImportForICloudAccount;
- (void)performFinalPushToCloudKit;
- (void)performFinalRefreshForICloudAccount;
- (void)reachabilityChanged:(id)arg1;
- (void)refreshFolderContentsForICloudAccount;
- (void)refreshFolderListForICloudAccount;
@property(retain, nonatomic) NSTimer *repeatingImportTimer; // @synthesize repeatingImportTimer=_repeatingImportTimer;
- (void)resetNotificationObservers;
- (void)retryRefreshFolderContentsForICloudAccount;
- (void)retryRefreshFolderListForICloudAccount;
- (void)retrySelector:(SEL)arg1;
- (void)startICloudImportOperationIfNecessary;
- (void)startMigrationForICloudAccount;
- (void)startRepeatingImportTimer;
- (void)stopRepeatingImportTimer;

@end

