//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICImageCollectionViewCell.h"

#import "AVPlayerViewControllerDelegate.h"

@class CAGradientLayer, NSString, UILabel, UIView;

@interface ICMovieCollectionViewCell : ICImageCollectionViewCell <AVPlayerViewControllerDelegate>
{
    UIView *_bottomView;
    CAGradientLayer *_bottomGradient;
    UILabel *_timeLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CAGradientLayer *bottomGradient; // @synthesize bottomGradient=_bottomGradient;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setAttachment:(id)arg1;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void)updateConstraints;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

