//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSOperationQueue;

@interface ICMoveModernNotesToLegacyAccountController : NSObject
{
    NSOperationQueue *_operationQueue;
    NSMutableArray *_notesToDelete;
    NSMutableArray *_createdLegacyNotes;
}

+ (id)localizedAlertMessageForCopyingNotesForAccount:(id)arg1;
+ (id)localizedAlertMessageForMovingNotesForAccount:(id)arg1;
+ (id)localizedAlertTitle;
- (void).cxx_destruct;
- (void)addOperationToCopyOrMoveNotes:(id)arg1 toFolder:(id)arg2 copyOnly:(_Bool)arg3;
- (void)asyncFinishCopyOnly:(_Bool)arg1;
- (void)cancel;
@property(retain, nonatomic) NSMutableArray *createdLegacyNotes; // @synthesize createdLegacyNotes=_createdLegacyNotes;
- (void)finishAfterCopyingNotesCopyOnly:(_Bool)arg1;
- (id)init;
@property(retain, nonatomic) NSMutableArray *notesToDelete; // @synthesize notesToDelete=_notesToDelete;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)waitUntilFinishedWithDispatchTimeout:(unsigned long long)arg1;

@end

