//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class ICDDevice, ICNote, NSMutableSet;

@interface ICMultipeerResourceRequest : NSOperation
{
    _Bool _isSuccessful;
    _Bool _isExecuting;
    _Bool _isFinished;
    ICNote *_note;
    ICDDevice *_device;
    NSMutableSet *_failedDevices;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ICDDevice *device; // @synthesize device=_device;
- (void)didFinish:(id)arg1;
@property(retain, nonatomic) NSMutableSet *failedDevices; // @synthesize failedDevices=_failedDevices;
- (id)init;
- (_Bool)isConcurrent;
@property(nonatomic) _Bool isExecuting; // @synthesize isExecuting=_isExecuting;
@property(nonatomic) _Bool isFinished; // @synthesize isFinished=_isFinished;
@property _Bool isSuccessful; // @synthesize isSuccessful=_isSuccessful;
@property(readonly) ICNote *note; // @synthesize note=_note;
- (void)startRequest;

@end

