//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNoteBaseUserActivityState.h"

@class NSData, NSDate, NSString;

@interface ICNoteUserActivityState : ICNoteBaseUserActivityState
{
    _Bool _editing;
    _Bool _wantsContinuationStreams;
    NSString *_noteID;
    NSDate *_modificationDate;
    NSDate *_creationDate;
    NSString *_title;
    NSString *_content;
    NSString *_folderID;
    NSString *_folderName;
    NSData *_visibleRangeData;
    NSData *_selectionRangeData;
    struct _NSRange _visibleRange;
    struct _NSRange _selectionRange;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSDate *creationDate; // @synthesize creationDate=_creationDate;
@property(copy, nonatomic) NSString *folderID; // @synthesize folderID=_folderID;
@property(copy, nonatomic) NSString *folderName; // @synthesize folderName=_folderName;
- (id)initWithNote:(id)arg1;
@property(nonatomic, getter=isEditing) _Bool editing; // @synthesize editing=_editing;
@property(copy, nonatomic) NSDate *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(copy, nonatomic) NSString *noteID; // @synthesize noteID=_noteID;
@property(nonatomic) struct _NSRange selectionRange; // @synthesize selectionRange=_selectionRange;
@property(copy, nonatomic) NSData *selectionRangeData; // @synthesize selectionRangeData=_selectionRangeData;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) struct _NSRange visibleRange; // @synthesize visibleRange=_visibleRange;
@property(copy, nonatomic) NSData *visibleRangeData; // @synthesize visibleRangeData=_visibleRangeData;
@property(nonatomic) _Bool wantsContinuationStreams; // @synthesize wantsContinuationStreams=_wantsContinuationStreams;
- (void)updateUserActivity:(id)arg1;

@end

