//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNoteContainerTableViewCell.h"

@interface ICNoteContainerTableViewCell (ICAccessibility_iOS)
- (_Bool)_icaxIsEditTitleActionAvailable;
- (_Bool)_icaxPerformEditTitleAction;
- (id)accessibilityCustomActions;
- (id)accessibilityHint;
- (id)tableTextAccessibleLabel:(id)arg1;
@end

