//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer;

@interface ICNoteEditorToolbarPlusView : UIView
{
    CAShapeLayer *_backgroundLayer;
    CAShapeLayer *_plusLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CAShapeLayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
@property(retain, nonatomic) CAShapeLayer *plusLayer; // @synthesize plusLayer=_plusLayer;

@end

