//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFolderListTableViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, NoteCollectionObject;

@interface ICNoteCollectionTableViewCell : ICFolderListTableViewCell <UIGestureRecognizerDelegate>
{
    NoteCollectionObject *_noteCollection;
}

- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)folderNoteCount;
- (id)folderTitle;
- (id)identifier;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (_Bool)isSmartFolder;
@property(retain, nonatomic) NoteCollectionObject *noteCollection; // @synthesize noteCollection=_noteCollection;
- (id)noteContext;
- (void)notesContextRefreshNotification:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)prepareForReuse;
- (void)setNoteCollection:(id)arg1 resetFolderNoteCountLabel:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

