//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNotesListTableViewCell.h"

@interface ICNotesListTableViewCell (ICAccessibility_iOS)
- (_Bool)_icaxDeleteSelectedNotes;
- (_Bool)_icaxMoveSelectedNotes;
- (id)_icaxParentNotesListViewController;
- (id)_icaxParentTableView;
- (id)accessibilityCustomActions;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
@end

