//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache, NSDictionary, UITableView, UIViewController;

@interface ICNotesListCellHandler : NSObject
{
    _Bool _supportCompact;
    UIViewController *_viewController;
    UITableView *_tableView;
    double _imageHeight;
    NSDictionary *_identifierNibDictionary;
    NSDictionary *_sizingCells;
    NSCache *_thumbnailCache;
}

- (void).cxx_destruct;
- (void)addIdentifierNibToDictionary:(id)arg1;
- (Class)cellClassForNote:(id)arg1;
- (id)cellForNote:(id)arg1 searchResult:(id)arg2 atIndexPath:(id)arg3;
- (void)copySizingInfoToCell:(id)arg1;
- (id)createCellWithImageView:(id)arg1 forNote:(id)arg2 atIndexPath:(id)arg3 searchResult:(id)arg4;
- (id)dequeueReusableSizingUpdatedCellWithIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (id)emptyCellForIndexPath:(id)arg1;
@property(copy, nonatomic) NSDictionary *identifierNibDictionary; // @synthesize identifierNibDictionary=_identifierNibDictionary;
@property(nonatomic) double imageHeight; // @synthesize imageHeight=_imageHeight;
- (id)initWithViewController:(id)arg1 tableView:(id)arg2 supportCompact:(_Bool)arg3;
- (void)invalidateAllCachedThumbnails;
- (void)invalidateCachedThumbnailForNote:(id)arg1;
- (id)newIdentifierNibDictionary;
- (id)newSizingCells;
- (void)registerNibsForTableView:(id)arg1;
- (double)rowHeightForCellClass:(Class)arg1;
- (double)screenScale;
@property(copy, nonatomic) NSDictionary *sizingCells; // @synthesize sizingCells=_sizingCells;
@property(nonatomic) _Bool supportCompact; // @synthesize supportCompact=_supportCompact;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSCache *thumbnailCache; // @synthesize thumbnailCache=_thumbnailCache;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(readonly, nonatomic) _Bool showCompact;
- (id)sizingCellForCellClass:(Class)arg1;
- (Class)uniformRowHeightCellClass;
- (void)updateForContentSizeCategoryChange;
- (void)updateTableViewRowHeight;
- (void)updateThumbnailForNote:(id)arg1 inCell:(id)arg2 atIndexPath:(id)arg3;

@end

