//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface ICNoTransformImageView : UIImageView
{
    _Bool _disableSettingTransform;
}

@property(nonatomic) _Bool disableSettingTransform; // @synthesize disableSettingTransform=_disableSettingTransform;
- (void)setTransform:(struct CGAffineTransform)arg1;

@end

