//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICSpotlightAttributeSet, NSDictionary;

@interface ICNoteBaseUserActivityState : NSObject
{
    NSDictionary *_contentAttributes;
    ICSpotlightAttributeSet *_attributeSet;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ICSpotlightAttributeSet *attributeSet; // @synthesize attributeSet=_attributeSet;
@property(readonly, copy, nonatomic) NSDictionary *contentAttributes; // @synthesize contentAttributes=_contentAttributes;
- (id)initWithNote:(id)arg1;
- (void)updateUserActivity:(id)arg1;

@end

