//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICFolderListTableViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class ICNoteContainer, NSString, UITapGestureRecognizer;

@interface ICNoteContainerTableViewCell : ICFolderListTableViewCell <UIGestureRecognizerDelegate>
{
    _Bool _allowsEditingTitle;
    ICNoteContainer *_noteContainer;
    id <ICNoteContainerCellDelegate> _delegate;
    UITapGestureRecognizer *_editTitleGestureRecognizer;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool _icaxNoteContainerHasEditableTitle;
- (void)addNoteContainerObservers;
@property _Bool allowsEditingTitle; // @synthesize allowsEditingTitle=_allowsEditingTitle;
- (void)dealloc;
@property __weak id <ICNoteContainerCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTapCell:(id)arg1;
@property(retain) UITapGestureRecognizer *editTitleGestureRecognizer; // @synthesize editTitleGestureRecognizer=_editTitleGestureRecognizer;
- (unsigned long long)folderNoteCount;
- (id)folderTitle;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)hasTrashFolder;
- (id)identifier;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (_Bool)isSmartFolder;
- (_Bool)isTrashFolder;
@property(retain, nonatomic) ICNoteContainer *noteContainer; // @synthesize noteContainer=_noteContainer;
- (_Bool)noteContainerHasEditableTitle;
- (void)noteWillBeDeletedOrUndeleted:(id)arg1;
- (void)notesContextRefreshNotification:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)prepareForReuse;
- (void)removeNoteContainerObservers;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

