//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNotesListTableViewCellNoImageView.h"

@class ICImageAndMovieThumbnailView;

@interface ICNotesListTableViewCellWithImageView : ICNotesListTableViewCellNoImageView
{
    ICImageAndMovieThumbnailView *_thumbnailView;
}

+ (id)thumbnailBackgroundColor;
+ (id)thumbnailBorderColor;
+ (double)thumbnailCornerRadius;
- (void).cxx_destruct;
- (double)computeRowHeight;
- (void)prepareForReuse;
@property(nonatomic) __weak ICImageAndMovieThumbnailView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void)updateSizingInfoForTableFrame:(struct CGRect)arg1;

@end

