//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ICNoteEditorToolbarDisclosureView, NSLayoutConstraint, NotesTextureBackgroundView, UIToolbar;

@interface ICNoteEditorInputAccessoryView : UIView
{
    float _disclosureViewCloseTrailingOffset;
    UIToolbar *_toolbar;
    ICNoteEditorToolbarDisclosureView *_disclosureView;
    NSLayoutConstraint *_disclosureViewTrailingConstraint;
    NSLayoutConstraint *_disclosureViewBottomConstraint;
    NotesTextureBackgroundView *_backgroundView;
    NSLayoutConstraint *_toolbarTopConstraint;
}

- (void).cxx_destruct;
- (id)accessibilityElements;
- (_Bool)areButtonsHidden;
@property(retain, nonatomic) NotesTextureBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)disclosureTapRecognizer:(id)arg1;
@property(retain, nonatomic) ICNoteEditorToolbarDisclosureView *disclosureView; // @synthesize disclosureView=_disclosureView;
@property(retain, nonatomic) NSLayoutConstraint *disclosureViewBottomConstraint; // @synthesize disclosureViewBottomConstraint=_disclosureViewBottomConstraint;
@property(nonatomic) float disclosureViewCloseTrailingOffset; // @synthesize disclosureViewCloseTrailingOffset=_disclosureViewCloseTrailingOffset;
@property(retain, nonatomic) NSLayoutConstraint *disclosureViewTrailingConstraint; // @synthesize disclosureViewTrailingConstraint=_disclosureViewTrailingConstraint;
- (void)hide;
- (void)hideButtons;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setScrollViewContentOffset:(struct CGPoint)arg1;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) NSLayoutConstraint *toolbarTopConstraint; // @synthesize toolbarTopConstraint=_toolbarTopConstraint;
- (void)showWithDelay:(double)arg1;
- (void)toggleDisclosureViewCloseState;
- (void)updateLayoutWithSize:(struct CGSize)arg1;

@end

