//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNote.h"

#import "ICNoteUndoSupport.h"

@interface ICNote (UndoSupport) <ICNoteUndoSupport>
- (void)copyValuesToNote:(id)arg1;
- (void)undoablySetFolder:(id)arg1;
- (void)undoablyTrashOrDelete;
@end

