//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ICNoteEditorToolbarPlusView, UIImageView;

@interface ICNoteEditorToolbarDisclosureView : UIView
{
    _Bool _closeState;
    ICNoteEditorToolbarPlusView *_openView;
    UIImageView *_closeImageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *closeImageView; // @synthesize closeImageView=_closeImageView;
@property(nonatomic) _Bool closeState; // @synthesize closeState=_closeState;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
@property(retain, nonatomic) ICNoteEditorToolbarPlusView *openView; // @synthesize openView=_openView;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

