//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAEAGLLayer, ICDrawingView;

@interface ICOpenGLESView : UIView
{
    ICDrawingView *_drawingView;
}

+ (Class)layerClass;
- (void).cxx_destruct;
@property(nonatomic) __weak ICDrawingView *drawingView; // @synthesize drawingView=_drawingView;
@property(readonly, nonatomic) CAEAGLLayer *glLayer;
- (void)initLayer;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;

@end

