//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICPeerInputStream, NSData;

@protocol ICPeerInputStreamDelegate <NSObject>
- (void)didDisconnectInputStream:(ICPeerInputStream *)arg1;
- (void)handleMessage:(NSData *)arg1 fromInputStream:(ICPeerInputStream *)arg2;
@end

