//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICDDevice, ICMedia, NSData;

@protocol ICPeerMessageControllerDelegate <NSObject>
- (void)sendMedia:(ICMedia *)arg1 toSource:(id <NSCopying>)arg2;
- (_Bool)sendMessage:(NSData *)arg1 toSource:(id <NSCopying>)arg2 error:(id *)arg3;
- (void)setDevice:(ICDDevice *)arg1 forSource:(id <NSCopying>)arg2;
@end

