//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ICPeerMessageController : NSObject
{
    NSMutableDictionary *_deviceRequests;
    NSMutableDictionary *_sourceToDevices;
    NSMutableDictionary *_deviceUUIDToSource;
    id <ICPeerMessageControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)connectedToDevice:(id)arg1;
@property(nonatomic) __weak id <ICPeerMessageControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)deviceRequestsForUUID:(id)arg1;
- (void)didFinishReceivingResourceWithName:(id)arg1 fromSource:(id)arg2 atURL:(id)arg3 withError:(id)arg4;
- (void)disconnectedFromSource:(id)arg1;
- (void)handleAttachment:(const struct Attachment *)arg1 fromDevice:(id)arg2;
- (id)handleIdentity:(const struct Identity *)arg1 fromSource:(id)arg2;
- (void)handleInviteMessage:(const struct Invite *)arg1 fromDevice:(id)arg2;
- (void)handleInviteReplyMessage:(const struct InviteReply *)arg1 fromDevice:(id)arg2;
- (void)handleKeepAliveMessage:(const struct KeepAlive *)arg1 fromDevice:(id)arg2;
- (void)handleMediaMessage:(const struct Media *)arg1 fromDevice:(id)arg2;
- (void)handleMessage:(id)arg1 fromSource:(id)arg2;
- (void)handleNoteMessage:(const struct Note *)arg1 fromDevice:(id)arg2 data:(id)arg3;
- (void)handleRequestAttachment:(const struct RequestAttachment *)arg1 fromDevice:(id)arg2;
- (void)handleRequestMedia:(const struct RequestMedia *)arg1 fromDevice:(id)arg2;
- (void)handleRequestNoteMessage:(const struct RequestNote *)arg1 fromDevice:(id)arg2;
- (void)handleShareInfoMessage:(const struct ShareInfo *)arg1 fromDevice:(id)arg2 data:(id)arg3;
- (void)handleUnavailableMediaMessage:(const struct UnavailableMedia *)arg1 fromDevice:(id)arg2;
- (id)init;
- (void)invite:(id)arg1 toNote:(id)arg2;
- (id)mediaRequestForDevice:(id)arg1 withIdentifier:(id)arg2;
- (_Bool)note:(id)arg1 canCollaborateWithDevice:(id)arg2;
- (void)replyToInvite:(id)arg1 accept:(_Bool)arg2;
- (void)requestAttachment:(id)arg1;
- (void)requestMedia:(id)arg1;
- (void)requestNote:(id)arg1 from:(id)arg2;
- (id)sendDeltas:(id)arg1;
- (void)sendIdentityToSource:(id)arg1;
- (void)sendKeepAlive;
- (void)sendMediaURL:(id)arg1 toSource:(id)arg2;
- (id)sendMessage:(struct PeerNetworkMessage *)arg1 toDevices:(id)arg2;
- (id)sendMessage:(struct PeerNetworkMessage *)arg1 toSource:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)sendMessage:(struct PeerNetworkMessage *)arg1 toSources:(id)arg2;
- (id)sendNote:(id)arg1 toDevices:(id)arg2 saveDeltas:(_Bool)arg3;
- (void)sendNoteShareInfo:(id)arg1;
- (void)sendNoteShareInfo:(id)arg1 toDevices:(id)arg2;

@end

