//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UISearchBarDelegate.h"

@class MKLocalSearch, NSArray, NSString, UISearchBar;

@interface ICPickLocationViewController : UITableViewController <UISearchBarDelegate>
{
    CDUnknownBlockType _completionHandler;
    MKLocalSearch *_localSearch;
    NSArray *_mapItems;
    UISearchBar *_searchBar;
}

- (void).cxx_destruct;
- (void)cancelAction:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void)didReceiveMemoryWarning;
- (void)executeSearch;
- (id)initWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) MKLocalSearch *localSearch; // @synthesize localSearch=_localSearch;
@property(copy, nonatomic) NSArray *mapItems; // @synthesize mapItems=_mapItems;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

