//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICSelectorDelayer, NSDate;

@interface ICProgressIndicatorTracker : NSObject
{
    _Bool _progressIndicatorShouldAnimate;
    _Bool _cloudContextFetchOperationsPending;
    _Bool _migrating;
    _Bool _makingProgress;
    id <ICProgressIndicatorTrackerDelegate> _delegate;
    ICSelectorDelayer *_progressIndicatorShouldStartDelayer;
    ICSelectorDelayer *_progressIndicatorShouldStopDelayer;
    NSDate *_progressIndicatorStartDate;
}

+ (_Bool)isMigratingLocalAccount;
- (void).cxx_destruct;
@property(nonatomic) _Bool cloudContextFetchOperationsPending; // @synthesize cloudContextFetchOperationsPending=_cloudContextFetchOperationsPending;
- (void)cloudContextFetchOperationsPendingNotification:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <ICProgressIndicatorTrackerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (id)initWithDelegate:(id)arg1;
- (void)invalidate;
- (void)legacyImportOperationsDidChange:(id)arg1;
@property(nonatomic) _Bool makingProgress; // @synthesize makingProgress=_makingProgress;
@property(nonatomic) _Bool migrating; // @synthesize migrating=_migrating;
- (void)migrationStateDidChange:(id)arg1;
@property(nonatomic) _Bool progressIndicatorShouldAnimate; // @synthesize progressIndicatorShouldAnimate=_progressIndicatorShouldAnimate;
@property(retain, nonatomic) ICSelectorDelayer *progressIndicatorShouldStartDelayer; // @synthesize progressIndicatorShouldStartDelayer=_progressIndicatorShouldStartDelayer;
@property(retain, nonatomic) ICSelectorDelayer *progressIndicatorShouldStopDelayer; // @synthesize progressIndicatorShouldStopDelayer=_progressIndicatorShouldStopDelayer;
- (void)progressIndicatorShouldUpdate;
@property(retain, nonatomic) NSDate *progressIndicatorStartDate; // @synthesize progressIndicatorStartDate=_progressIndicatorStartDate;
- (void)reachabilityChanged:(id)arg1;
- (void)updateMakingProgress;

@end

