//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class ICDrawingView;

@interface ICRulerLayer : CALayer
{
    ICDrawingView *_drawingView;
}

- (void).cxx_destruct;
- (id)accessibilityCustomActions;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (id)accessibilityLabel;
- (id)accessibilityPath;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
@property(nonatomic) __weak ICDrawingView *drawingView; // @synthesize drawingView=_drawingView;
- (_Bool)isAccessibilityElement;
- (id)locationDescriptionForSpeaking;
- (_Bool)makeHorizontal;
- (_Bool)makeVertical;
@property(readonly, nonatomic) long long userAngle;

@end

