//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CIDetector.h"

@interface ICSalienceDetector : CIDetector
{
    double _blurMultiplier1;
    double _blurMultiplier2;
    double _contrast;
    double _brightness;
}

+ (id)CIImageByFilteringImageCustom:(id)arg1;
+ (id)CIImageByFilteringImageLineOverlay:(id)arg1;
+ (id)CIImageByFilteringImageSobel:(id)arg1;
+ (id)CIImageByResizingImage:(id)arg1 withScale:(double)arg2;
+ (id)CIImageFromImage:(struct UIImage *)arg1;
+ (id)arrayOfPointsWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2;
+ (struct CGRect)boundingRectFromEdgeFeatures:(id)arg1;
+ (id)filterForNormalizingAlpha;
+ (struct UIImage *)imageByEdgeFilteringImage:(struct UIImage *)arg1;
+ (struct UIImage *)imageFromCIImage:(id)arg1;
- (id)CIImageByFilteringImage:(id)arg1;
- (id)CIImageByFilteringImageGaussian:(id)arg1;
@property double blurMultiplier1; // @synthesize blurMultiplier1=_blurMultiplier1;
@property double blurMultiplier2; // @synthesize blurMultiplier2=_blurMultiplier2;
@property double brightness; // @synthesize brightness=_brightness;
@property double contrast; // @synthesize contrast=_contrast;
- (id)featuresInImage:(id)arg1;
- (id)featuresInImage:(id)arg1 options:(id)arg2;
- (id)featuresInImageNaive:(id)arg1;
- (struct UIImage *)imageByEdgeFilteringImage:(struct UIImage *)arg1;
- (struct UIImage *)imageByEdgeFilteringImage:(struct UIImage *)arg1 initialScale:(double)arg2;
- (id)init;

@end

