//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ICSearchViewController, UISegmentedControl;

@interface ICSearchViewControllerScopeBar : UIView
{
    UISegmentedControl *_scopeBar;
    ICSearchViewController *_delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak ICSearchViewController *delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(retain, nonatomic) UISegmentedControl *scopeBar; // @synthesize scopeBar=_scopeBar;
- (void)scopeChanged:(id)arg1;
@property(readonly, nonatomic) long long searchScope;

@end

