//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ICSearchResult, ICSearchViewController;

@protocol ICSearchViewControllerDelegate
- (void)didDismissSearchViewController:(ICSearchViewController *)arg1;
- (void)didPresentSearchViewController:(ICSearchViewController *)arg1;
- (void)searchViewController:(ICSearchViewController *)arg1 didDeleteSearchResult:(ICSearchResult *)arg2;
- (void)willDismissSearchViewController:(ICSearchViewController *)arg1;
- (void)willPresentSearchViewController:(ICSearchViewController *)arg1;
@end

