//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICSearchIndexable.h"

@class ICSearchIndexerContext, NSArray, NSNumber, NSString, NSURL;

@protocol ICSearchIndexableNote <ICSearchIndexable>
- (NSURL *)appURLForIndexerContext:(ICSearchIndexerContext *)arg1;
- (NSString *)contentInfoText;
- (NSNumber *)integerId;
- (NSString *)noteAsPlainTextWithoutTitle;
- (NSArray *)searchableContentKeyPaths;
- (NSString *)title;
@end

