//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICNotesListCellHandler.h"

@interface ICSearchCellHandler : ICNotesListCellHandler
{
}

- (void)addIdentifierNibToDictionary:(id)arg1;
- (id)cellForAttachment:(id)arg1 searchResult:(id)arg2 atIndexPath:(id)arg3;
- (Class)uniformRowHeightCellClass;

@end

