//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UISearchBarDelegate.h"
#import "UISearchControllerDelegate.h"
#import "UISearchResultsUpdating.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIViewControllerPreviewingDelegate_Deprecated.h"

@class ICSearchCellHandler, ICSearchController, ICSearchResultsTableView, ICSearchViewControllerScopeBar, ICSectionedSearchResults, ICSelectorDelayer, NSArray, NSString, NotesTextureBackgroundView, UISearchBar, UISearchController;

@interface ICSearchViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UISearchControllerDelegate, UISearchResultsUpdating, UIViewControllerPreviewingDelegate_Deprecated>
{
    _Bool _showSearchResults;
    _Bool _searchBarWasFirstResponderOnSuspend;
    id <ICSearchViewControllerDelegate> _delegate;
    id <ICNoteVisibilityTesting> _noteVisibilityTesting;
    UIViewController *_contentsController;
    ICSearchResultsTableView *_tableView;
    UISearchController *_searchController;
    ICSearchViewControllerScopeBar *_scopeBar;
    NSString *_searchString;
    NSArray *_recentSearches;
    ICSearchCellHandler *_notesCellHandler;
    ICSearchController *_noteSearchController;
    NotesTextureBackgroundView *_backgroundView;
    ICSelectorDelayer *_updateSearchResultsFromSearchControllerDelayer;
}

- (void).cxx_destruct;
- (void)addSearchResults:(id)arg1 removingFoundIdentifiers:(id)arg2 searchString:(id)arg3 isClearedForNewSearch:(_Bool)arg4;
@property(retain, nonatomic) NotesTextureBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (id)cellForBrowseAttachments;
- (id)cellForRecentSearchAtIndexPath:(id)arg1;
- (void)clearAllRecentSearches;
- (void)commitPreviewViewController:(id)arg1 committedViewController:(id)arg2;
- (void)configureTableView:(id)arg1;
- (void)contentSizeCategoryDidChange:(id)arg1;
@property(nonatomic) __weak UIViewController *contentsController; // @synthesize contentsController=_contentsController;
- (id)currentVisibilityTesting;
- (void)dealloc;
@property(nonatomic) __weak id <ICSearchViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (void)didDismissSearchController:(id)arg1;
- (void)didPresentSearchController:(id)arg1;
- (_Bool)hasSearchString;
- (struct UIFont *)headerViewCellLabelFont;
- (id)initWithContentsController:(id)arg1;
@property(nonatomic, getter=isActive) _Bool active;
- (_Bool)isHeaderFooterViewForPosition:(struct CGPoint)arg1 inTableView:(id)arg2;
- (id)newHeaderViewWithPaperTexture;
@property(retain, nonatomic) ICSearchController *noteSearchController; // @synthesize noteSearchController=_noteSearchController;
@property(retain, nonatomic) id <ICNoteVisibilityTesting> noteVisibilityTesting; // @synthesize noteVisibilityTesting=_noteVisibilityTesting;
@property(retain, nonatomic) ICSearchCellHandler *notesCellHandler; // @synthesize notesCellHandler=_notesCellHandler;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)prepareForSuspend;
- (id)previewViewControllerForLocation:(struct CGPoint)arg1 inSourceView:(id)arg2;
- (id)recentSearchAtIndex:(long long)arg1;
@property(copy, nonatomic) NSArray *recentSearches; // @synthesize recentSearches=_recentSearches;
- (id)recentSearchesFromDefaults;
- (void)resumeAfterSuspend;
- (void)saveCurrentSearchStringAsRecentSearch;
- (void)saveRecentSearchString:(id)arg1;
@property(retain, nonatomic) ICSearchViewControllerScopeBar *scopeBar; // @synthesize scopeBar=_scopeBar;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(readonly, nonatomic) UISearchBar *searchBar;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
@property(nonatomic) _Bool searchBarWasFirstResponderOnSuspend; // @synthesize searchBarWasFirstResponderOnSuspend=_searchBarWasFirstResponderOnSuspend;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
- (id)searchResultForIndexPath:(id)arg1;
- (void)searchResultsDidUpdate:(id)arg1;
- (void)searchScopeChanged:(id)arg1;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(readonly, nonatomic) ICSectionedSearchResults *sectionedSearchResults;
@property(nonatomic) _Bool showSearchResults; // @synthesize showSearchResults=_showSearchResults;
@property(retain, nonatomic) ICSearchResultsTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) ICSelectorDelayer *updateSearchResultsFromSearchControllerDelayer; // @synthesize updateSearchResultsFromSearchControllerDelayer=_updateSearchResultsFromSearchControllerDelayer;
- (void)showSearchIndexableObjectForSelectSearchResult:(id)arg1;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableViewForSourceView:(id)arg1;
- (void)updateForContentSizeCategoryChange;
- (_Bool)updateNavigationTitle;
- (void)updateScopeBarForSearch:(_Bool)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)updateSearchResultsFromSearchController;
- (void)updateViewHiddenState;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)viewForRecentSearchesHeader;
- (id)viewForSearchResultsHeaderInSection:(unsigned long long)arg1;
- (void)willDismissSearchController:(id)arg1;
- (void)willPresentPreviewViewController:(id)arg1 forLocation:(struct CGPoint)arg2 inSourceView:(id)arg3;
- (void)willPresentSearchController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

