//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISplitViewController.h"

#import "UISplitViewControllerDelegate.h"

@class NSArray, NSMutableArray, UILabel, UINavigationController, UIView, UIViewController;

@interface ICSplitViewController : UISplitViewController <UISplitViewControllerDelegate>
{
    _Bool _detailDimmed;
    UINavigationController *_masterNavigationController;
    UINavigationController *_detailNavigationController;
    id <ICSplitViewControllerDelegate> _icSplitViewControllerDelegate;
    UIView *_detailDimmingView;
    UILabel *_dimViewTitleLabel;
    NSArray *_dimmedRightBarButtonItems;
    NSArray *_dimmedToolbarItems;
    NSMutableArray *_dismissDetailDimmingBlocks;
    NSMutableArray *_dimViewTitles;
}

- (void).cxx_destruct;
- (_Bool)_splitViewControllerIsPrimaryVisible:(id)arg1;
- (_Bool)allowsLandscapeOrientation;
- (void)cancelDetailDimmingIfNecessary;
@property(readonly, nonatomic) UIViewController *currentNoteEditorController;
@property(retain, nonatomic) UIView *detailDimmingView; // @synthesize detailDimmingView=_detailDimmingView;
@property(retain, nonatomic) UINavigationController *detailNavigationController; // @synthesize detailNavigationController=_detailNavigationController;
- (void)dimDetailViewWithTitle:(id)arg1 dismissBlock:(CDUnknownBlockType)arg2 animated:(_Bool)arg3;
@property(retain, nonatomic) UILabel *dimViewTitleLabel; // @synthesize dimViewTitleLabel=_dimViewTitleLabel;
@property(retain, nonatomic) NSMutableArray *dimViewTitles; // @synthesize dimViewTitles=_dimViewTitles;
@property(copy, nonatomic) NSArray *dimmedRightBarButtonItems; // @synthesize dimmedRightBarButtonItems=_dimmedRightBarButtonItems;
@property(copy, nonatomic) NSArray *dimmedToolbarItems; // @synthesize dimmedToolbarItems=_dimmedToolbarItems;
@property(retain, nonatomic) NSMutableArray *dismissDetailDimmingBlocks; // @synthesize dismissDetailDimmingBlocks=_dismissDetailDimmingBlocks;
- (void)dismissPrimaryControllerAnimated:(_Bool)arg1;
- (_Bool)hasLegacyNoteEditorController;
@property(nonatomic) __weak id <ICSplitViewControllerDelegate> icSplitViewControllerDelegate; // @synthesize icSplitViewControllerDelegate=_icSplitViewControllerDelegate;
@property(nonatomic, getter=isDetailDimmed) _Bool detailDimmed; // @synthesize detailDimmed=_detailDimmed;
@property(readonly, nonatomic) _Bool isDisplayingOverlayOnPad;
- (_Bool)isNoteEditorControllerVisible;
- (id)legacyNoteEditorController;
- (id)listControllerForCurrentNoteEditor;
@property(retain, nonatomic) UINavigationController *masterNavigationController; // @synthesize masterNavigationController=_masterNavigationController;
- (id)noteEditorController;
- (void)setDetailDimmed:(_Bool)arg1 animated:(_Bool)arg2 title:(id)arg3;
- (void)setDimViewTitle:(id)arg1 animated:(_Bool)arg2;
- (_Bool)shouldAutorotate;
- (void)showDetailViewController:(id)arg1 animated:(_Bool)arg2 sender:(id)arg3;
- (void)showDetailViewControllerAnimated:(_Bool)arg1 sender:(id)arg2;
- (void)showPrimaryControllerAnimated:(_Bool)arg1;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)switchToLegacyNoteEditorController;
- (void)switchToNoteEditorController;
- (void)switchToNoteEditorControllerIfNecessary:(id)arg1;
- (long long)targetDisplayModeForActionInSplitViewController:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)undimDetailViewAnimated:(_Bool)arg1;
- (void)updateDetailDimmingViewFrame;
- (void)updateNoteEditorNavigation;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

