//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICStartupBaseViewController.h"

#import "ICStartupDeviceCheckIndicator.h"

@class NSLayoutConstraint, UIActivityIndicatorView, UILabel, UITextView;

@interface ICStartupMovingViewController : ICStartupBaseViewController <ICStartupDeviceCheckIndicator>
{
    UILabel *_importantLabel;
    NSLayoutConstraint *_titleToImportantLabelConstraint;
    NSLayoutConstraint *_leftMarginConstraint;
    NSLayoutConstraint *_rightMarginConstraint;
    NSLayoutConstraint *_importantLabelLeadingConstraint;
    NSLayoutConstraint *_importantLabelTrailingConstraint;
    UILabel *_cantBeUpgradedLabel;
    UITextView *_deviceListView;
    UIActivityIndicatorView *_activityIndicatorView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
- (void)applyAccessibilityInfo;
@property(retain, nonatomic) UILabel *cantBeUpgradedLabel; // @synthesize cantBeUpgradedLabel=_cantBeUpgradedLabel;
- (id)choiceLabels;
- (void)choiceSelected:(unsigned long long)arg1;
- (_Bool)choicesShouldAlignVertically;
@property(retain, nonatomic) UITextView *deviceListView; // @synthesize deviceListView=_deviceListView;
- (void)didCompleteAction;
- (void)didReceiveMemoryWarning;
- (id)disclaimerStringForCurrentDevice;
- (void)ensureControlsAreConnected;
@property(retain, nonatomic) UILabel *importantLabel; // @synthesize importantLabel=_importantLabel;
@property(retain, nonatomic) NSLayoutConstraint *importantLabelLeadingConstraint; // @synthesize importantLabelLeadingConstraint=_importantLabelLeadingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *importantLabelTrailingConstraint; // @synthesize importantLabelTrailingConstraint=_importantLabelTrailingConstraint;
- (_Bool)isExtraSmallDevice;
@property(retain, nonatomic) NSLayoutConstraint *leftMarginConstraint; // @synthesize leftMarginConstraint=_leftMarginConstraint;
- (id)redAsteriskAttributedString;
- (id)redColor;
@property(retain, nonatomic) NSLayoutConstraint *rightMarginConstraint; // @synthesize rightMarginConstraint=_rightMarginConstraint;
@property(retain, nonatomic) NSLayoutConstraint *titleToImportantLabelConstraint; // @synthesize titleToImportantLabelConstraint=_titleToImportantLabelConstraint;
- (void)setupUIForIPadWithViewSize:(struct CGSize)arg1;
- (void)setupUIForIPhoneOrCompactWidth;
- (void)setupUIForViewSize:(struct CGSize)arg1;
- (double)smallFontSize;
- (double)standardFontSize;
- (void)startIndicatorAnimation;
- (void)stopIndicatorAnimation;
- (void)updateDeviceList;
- (void)updateDeviceListContentOffset;
- (void)updateImportantLabelFont;
- (void)upgradeToiCloudDrive:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

@end

