//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class ICLearnMoreTextView, ICStartupNavigationController, NSArray, NSLayoutConstraint, UILabel;

@interface ICStartupBaseViewController : UIViewController
{
    NSLayoutConstraint *_learnMoreViewHeightConstraint;
    ICLearnMoreTextView *_disclaimerLabel;
    UILabel *_titleLabel;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_bottomLeadingMargin;
    NSLayoutConstraint *_bottomTrailingMargin;
    NSLayoutConstraint *_firstBaselineDisclaimerLabelConstraint;
    double _cellHeight;
    NSLayoutConstraint *_horizontalButtonsSpaceConstraint;
    NSLayoutConstraint *_verticalButtonsSpaceConstraint;
    NSArray *_choiceButtons;
    double _bottomMargin;
    NSArray *_layoutGuides;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *bottomLeadingMargin; // @synthesize bottomLeadingMargin=_bottomLeadingMargin;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(retain, nonatomic) NSLayoutConstraint *bottomTrailingMargin; // @synthesize bottomTrailingMargin=_bottomTrailingMargin;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
- (void)choiceButtonTapped:(id)arg1;
@property(copy, nonatomic) NSArray *choiceButtons; // @synthesize choiceButtons=_choiceButtons;
- (void)choicesUpdated;
- (void)createButtons;
@property(retain, nonatomic) ICLearnMoreTextView *disclaimerLabel; // @synthesize disclaimerLabel=_disclaimerLabel;
@property(retain, nonatomic) NSLayoutConstraint *firstBaselineDisclaimerLabelConstraint; // @synthesize firstBaselineDisclaimerLabelConstraint=_firstBaselineDisclaimerLabelConstraint;
- (void)hideChoices;
@property(retain, nonatomic) NSLayoutConstraint *horizontalButtonsSpaceConstraint; // @synthesize horizontalButtonsSpaceConstraint=_horizontalButtonsSpaceConstraint;
@property(copy, nonatomic) NSArray *layoutGuides; // @synthesize layoutGuides=_layoutGuides;
@property(retain, nonatomic) NSLayoutConstraint *learnMoreViewHeightConstraint; // @synthesize learnMoreViewHeightConstraint=_learnMoreViewHeightConstraint;
- (void)setTitleDistanceToBaseline:(double)arg1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(retain, nonatomic) NSLayoutConstraint *verticalButtonsSpaceConstraint; // @synthesize verticalButtonsSpaceConstraint=_verticalButtonsSpaceConstraint;
- (id)sortedChoiceButtons;
@property(readonly, nonatomic) ICStartupNavigationController *startupNavigationController;
- (void)updateChoiceButtonsConstraintsForViewSize:(struct CGSize)arg1;
- (void)updateChoiceButtonsFonts;
- (void)updateConstraintsBasedOnViewSize:(struct CGSize)arg1 margin:(double)arg2;
- (void)updateDisclaimerViewBasedOnViewSize:(struct CGSize)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

