//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface ICStyleSelectorCell : UITableViewCell
{
    UILabel *_styleLabel;
    UIImageView *_styleActiveImage;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIImageView *styleActiveImage; // @synthesize styleActiveImage=_styleActiveImage;
@property(nonatomic) __weak UILabel *styleLabel; // @synthesize styleLabel=_styleLabel;

@end

