//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICDeviceListRequest, ICMutableBool, NSTimer, NSURLSessionDataTask;

@interface ICStartupController : NSObject
{
    _Bool _movingViewOnly;
    _Bool _isElCapitanAvailable;
    _Bool _showMovingViewWhenStateIsDoNotMigrate;
    _Bool _userDidContinue;
    _Bool _isModal;
    _Bool _didAddReachabilityObserver;
    ICDeviceListRequest *_deviceListRequest;
    unsigned long long _deviceCheckIndicatorAnimationLevel;
    NSTimer *_timeoutTimer;
    id <ICStartupControllerDelegate> _delegate;
    ICMutableBool *_previousCheckStatusCancellationObject;
    NSURLSessionDataTask *_elCapitanURLSessionDataTask;
}

+ (_Bool)consumeShouldResetMigrationStateInternalSetting;
+ (id)copyExchangeAccountAlertMessage;
+ (id)copyIMAPAccountAlertMessage;
+ (_Bool)hasAccountForMigration;
+ (_Bool)hasSetValueForFirstLaunchMigration;
+ (_Bool)hasShownWelcomeScreen;
+ (id)importantDisclaimerAttributedString;
+ (id)moveLocalNotesAlertMessage;
+ (id)noDeviceListDisclaimerAttributedString;
+ (void)setHasShownWelcomeScreen:(_Bool)arg1;
+ (_Bool)shouldShowUpdateICloudAccountView;
+ (_Bool)shouldShowWelcomeScreen;
+ (void)showStartupViewIfNecessaryWithShowStartupBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)checkStatusIfNecessaryWithDeviceCheckIndicator:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <ICStartupControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long deviceCheckIndicatorAnimationLevel; // @synthesize deviceCheckIndicatorAnimationLevel=_deviceCheckIndicatorAnimationLevel;
- (void)deviceCheckTimeout:(id)arg1;
@property(retain, nonatomic) ICDeviceListRequest *deviceListRequest; // @synthesize deviceListRequest=_deviceListRequest;
@property(nonatomic) _Bool didAddReachabilityObserver; // @synthesize didAddReachabilityObserver=_didAddReachabilityObserver;
- (void)didContinueFromStartupView;
- (void)didUpgradeFromStartupView:(_Bool)arg1;
@property(retain, nonatomic) NSURLSessionDataTask *elCapitanURLSessionDataTask; // @synthesize elCapitanURLSessionDataTask=_elCapitanURLSessionDataTask;
- (int)getStartupMigrationTypeWithTimeout:(double)arg1;
@property(readonly, nonatomic) _Bool hasAnyViewToShow;
- (id)initWithMovingViewOnly:(_Bool)arg1 isModal:(_Bool)arg2 delegate:(id)arg3;
@property(nonatomic) _Bool isElCapitanAvailable; // @synthesize isElCapitanAvailable=_isElCapitanAvailable;
@property(nonatomic) _Bool isModal; // @synthesize isModal=_isModal;
- (void)migrationStateDidChange:(id)arg1;
@property(nonatomic) _Bool movingViewOnly; // @synthesize movingViewOnly=_movingViewOnly;
@property(retain, nonatomic) ICMutableBool *previousCheckStatusCancellationObject; // @synthesize previousCheckStatusCancellationObject=_previousCheckStatusCancellationObject;
- (void)reachabilityChanged:(id)arg1;
@property(nonatomic) _Bool showMovingViewWhenStateIsDoNotMigrate; // @synthesize showMovingViewWhenStateIsDoNotMigrate=_showMovingViewWhenStateIsDoNotMigrate;
@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(nonatomic) _Bool userDidContinue; // @synthesize userDidContinue=_userDidContinue;
@property(readonly, nonatomic) _Bool shouldShowStartupMovingView;
- (void)startIndicatorAnimationIfNecessaryForDeviceCheckIndicator:(id)arg1;
- (void)startTimeoutTimerIfNecessaryWithDeviceCheckIndicator:(id)arg1;
- (void)stopIndicatorAnimationIfNecessaryForDeviceCheckIndicator:(id)arg1;
- (id)timerRunLoopMode;
- (void)upgradeEmptyLocalLegacyAccountIfNecessary;

@end

