//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "ICStartupControllerDelegate.h"

@class ICDeviceListRequest, ICStartupController, ICStartupMovingViewController, ICStartupViewController;

@interface ICStartupNavigationController : UINavigationController <ICStartupControllerDelegate>
{
    ICStartupViewController *_startupViewController;
    ICStartupMovingViewController *_startupMovingViewController;
    ICStartupController *_startupController;
    CDUnknownBlockType _dismissBlock;
}

+ (id)allLabelsUnderView:(id)arg1;
+ (_Bool)checkIfExtraSmallDeviceFromView:(id)arg1;
+ (id)defaultColorLetterpressedString:(id)arg1 font:(id)arg2;
+ (id)defaultLabelColor;
+ (id)letterpressedString:(id)arg1 withColor:(id)arg2 font:(id)arg3;
+ (void)setColorAndLetterpressForAllLabelsInView:(id)arg1;
+ (void)setColorAndLetterpressForLabel:(id)arg1;
- (void).cxx_destruct;
- (void)continueAction;
@property(readonly, nonatomic) ICDeviceListRequest *deviceListRequest;
- (void)dismiss;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
- (void)dismissWithCompletionBlock:(CDUnknownBlockType)arg1;
- (int)getStartupMigrationTypeWithTimeout:(double)arg1;
@property(readonly, nonatomic) _Bool hasAnyViewToShow;
- (id)initWithMovingViewOnly:(_Bool)arg1 dismissBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool isElCapitanAvailable;
- (void)noUpgradeAction;
- (void)noUpgradeActionAndDismiss;
@property(retain, nonatomic) ICStartupController *startupController; // @synthesize startupController=_startupController;
@property(retain, nonatomic) ICStartupMovingViewController *startupMovingViewController; // @synthesize startupMovingViewController=_startupMovingViewController;
@property(retain, nonatomic) ICStartupViewController *startupViewController; // @synthesize startupViewController=_startupViewController;
@property(readonly, nonatomic) _Bool shouldSwapChoices;
- (void)startupControllerShouldCloseMovingView;
- (void)startupMigrationTypeMightHaveChanged;
- (unsigned long long)supportedInterfaceOrientations;
- (void)upgradeAction;
- (void)viewWillAppear:(_Bool)arg1;

@end

