//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICStyleSelectorViewController, ICTextStyle;

@protocol ICStyleSelectorDelegate <NSObject>
- (void)styleSelector:(ICStyleSelectorViewController *)arg1 didSelectStyle:(ICTextStyle *)arg2;
- (void)styleSelector:(ICStyleSelectorViewController *)arg1 toggleBIU:(unsigned long long)arg2;
- (void)styleSelectorDidCancel:(ICStyleSelectorViewController *)arg1;
@end

