//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICTextView.h"

@interface ICTextView (ICAccessibility_iOS)
- (id)_accessibilityAttributedValueForRange:(struct _NSRange *)arg1;
- (struct CGRect)_accessibilityBoundsForRange:(struct _NSRange)arg1;
- (_Bool)_accessibilityHasTextOperations;
- (long long)_accessibilityLineEndPosition;
- (id)_accessibilityLineNumberAndColumnForPoint:(struct CGPoint)arg1;
- (struct _NSRange)_accessibilityLineRangeForPosition:(unsigned long long)arg1;
- (long long)_accessibilityLineStartPosition;
- (struct _NSRange)_accessibilityRangeForLineNumberAndColumn:(id)arg1;
- (struct _NSRange)_accessibilitySelectedTextRange;
- (void)_accessibilitySetSelectedTextRange:(struct _NSRange)arg1;
- (_Bool)_accessibilityTextOperationAction:(id)arg1;
- (id)_accessibilityTextOperations;
- (id)_accessibilityUserTestingChildren;
- (id)_accessibilityValueForRange:(struct _NSRange *)arg1;
- (id)_icaxAttachmentElements;
- (id)_icaxAttributedStringForRange:(struct _NSRange *)arg1;
- (id)_icaxCurrentParagraph;
- (unsigned long long)_icaxLinePositionForPosition:(unsigned long long)arg1 start:(_Bool)arg2;
- (id)_icaxLinkElements;
- (void)_icaxMarkTodoCompleteForCurrentSelection;
- (void)_icaxMarkTodoIncompleteForCurrentSelection;
- (id)_icaxModifiedAttributedStorageString;
- (struct _NSRange)_icaxRangeInModifiedAttributedString:(id)arg1 forRange:(struct _NSRange)arg2;
- (struct _NSRange)_icaxRangeInTextStorageForRange:(struct _NSRange)arg1 fromModifiedString:(id)arg2;
- (struct _NSRange)_icaxRangeOfAttachment:(id)arg1;
- (id)_icaxStyleNameForParagraphStyle:(id)arg1;
- (id)_icaxTodoElements;
- (void)_icaxUpdateFakeTextSelectionRange;
- (_Bool)accessibilityActivate;
- (struct CGPoint)accessibilityActivationPoint;
- (id)accessibilityCustomActions;
- (id)accessibilityCustomRotorItemsAtIndex:(long long)arg1;
- (id)accessibilityCustomRotorTitles;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (void)icaxBeginEditingAtAttachment:(id)arg1;
- (void)icaxBeginEditingInStorageRange:(struct _NSRange)arg1;
- (void)icaxTextDidChange;
- (void)icaxTextDidChangeSelection;
@end

