//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ICSelectorDelayer;

@interface ICTextViewDelegateHelper : NSObject
{
    _Bool _didPauseIndexingForEditing;
    _Bool _textViewDidChange;
    ICSelectorDelayer *_unpauseIndexingForEditingDelayer;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) _Bool didPauseIndexingForEditing; // @synthesize didPauseIndexingForEditing=_didPauseIndexingForEditing;
- (void)pauseIndexingForEditing;
- (void)setEditing:(_Bool)arg1 note:(id)arg2 animated:(_Bool)arg3;
@property(nonatomic) _Bool textViewDidChange; // @synthesize textViewDidChange=_textViewDidChange;
@property(retain, nonatomic) ICSelectorDelayer *unpauseIndexingForEditingDelayer; // @synthesize unpauseIndexingForEditingDelayer=_unpauseIndexingForEditingDelayer;
- (void)textViewDidChange:(id)arg1;
- (void)unpauseIndexingForEditing;

@end

