//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class UITextView;

@interface ICTextViewSplitLayer : CALayer
{
    UITextView *_textView;
}

- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;

@end

