//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class ICTrackedParagraph, UIImageView;

@interface ICTodoButton : UIButton
{
    _Bool _done;
    ICTrackedParagraph *_trackedParagraph;
    struct UIImageView *_undoneImageView;
    struct UIImageView *_doneImageView;
}

- (void).cxx_destruct;
- (void)applyImageNamed:(id)arg1 withTint:(struct UIColor *)arg2 forImageView:(struct UIImageView *)arg3;
@property(retain) UIImageView *doneImageView; // @synthesize doneImageView=_doneImageView;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isDone) _Bool done; // @synthesize done=_done;
- (void)setFrame:(struct CGRect)arg1 leftToRight:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1;
@property(nonatomic) __weak ICTrackedParagraph *trackedParagraph; // @synthesize trackedParagraph=_trackedParagraph;
@property(retain) UIImageView *undoneImageView; // @synthesize undoneImageView=_undoneImageView;
- (struct CGSize)sizeForLetterpressedImage;
- (void)updateImagesAnimated:(_Bool)arg1;

@end

