//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICTodoButton.h"

@interface ICTodoButton (ICAccessibility_iOS)
- (_Bool)_accessibilitySupportsActivateAction;
- (_Bool)_icaxBeginEditingAtEndOfCorrespondingParagraph;
- (id)_icaxCorrespondingParagraphText;
- (id)_icaxParentTextView;
- (_Bool)accessibilityActivate;
- (id)accessibilityCustomActions;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
@end

