//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAccessibilityElement.h"

@class ICTextView, ICTodoButton;

@interface ICTodoButtonProxyElement : UIAccessibilityElement
{
    ICTodoButton *_todoButton;
    ICTextView *_textView;
    struct _NSRange _textRange;
}

- (void).cxx_destruct;
- (_Bool)accessibilityActivate;
- (struct CGRect)accessibilityFrame;
- (id)accessibilityLabel;
- (id)accessibilityValue;
- (id)initWithTodoButton:(id)arg1 inTextRange:(struct _NSRange)arg2 textView:(id)arg3;
- (_Bool)isAccessibilityElement;
@property(nonatomic) struct _NSRange textRange; // @synthesize textRange=_textRange;
@property(nonatomic) __weak ICTextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak ICTodoButton *todoButton; // @synthesize todoButton=_todoButton;

@end

