//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NoteTextViewActionDelegate.h"
#import "NoteTextViewLayoutDelegate.h"
#import "UITextViewDelegate.h"

@class DOMHTMLDocument, ICTextViewDelegateHelper, NSArray, NSLayoutConstraint, NSString, NoteDateLabel, NoteTextView, NotesScrollView, UIScrollView, _UICompatibilityTextView;

@interface NoteContentLayer : UIView <NoteTextViewActionDelegate, NoteTextViewLayoutDelegate, UITextViewDelegate>
{
    _Bool _containsCJK;
    _Bool _tracksMaximumContentLength;
    _Bool _updatedTitleRange;
    id <NoteContentLayerDelegate> _delegate;
    NSLayoutConstraint *_bottomMarginConstraint;
    NSLayoutConstraint *_dateTopMarginConstraint;
    NSLayoutConstraint *_dateHorizontalContraint;
    NSLayoutConstraint *_textTopMarginConstraint;
    NSLayoutConstraint *_leftConstraint;
    NSLayoutConstraint *_rightConstraint;
    NotesScrollView *_scrollView;
    NoteTextView *_textView;
    UIView *_horizontalLayoutGuide;
    NoteDateLabel *_dateLabel;
    ICTextViewDelegateHelper *_textViewDelegateHelper;
}

- (void).cxx_destruct;
- (void)addSubWebResourcesObject:(id)arg1;
- (_Bool)allowsAttachmentsInTextView:(id)arg1;
- (_Bool)becomeFirstResponder;
@property(retain, nonatomic) NSLayoutConstraint *bottomMarginConstraint; // @synthesize bottomMarginConstraint=_bottomMarginConstraint;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canInsertImagesInTextView:(id)arg1;
- (_Bool)canResignFirstResponder;
@property(nonatomic) _Bool containsCJK; // @synthesize containsCJK=_containsCJK;
- (id)contentAsPasteboardItems;
- (id)contentAsPlainText:(_Bool)arg1;
@property(readonly, nonatomic) _Bool contentContainsValuableContent;
@property(nonatomic) struct CGPoint contentOffset;
@property(readonly, nonatomic) UIScrollView *contentScrollView;
@property(readonly, nonatomic) _UICompatibilityTextView *contentTextView;
@property(retain, nonatomic) NSLayoutConstraint *dateHorizontalContraint; // @synthesize dateHorizontalContraint=_dateHorizontalContraint;
@property(retain, nonatomic) NoteDateLabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) NSLayoutConstraint *dateTopMarginConstraint; // @synthesize dateTopMarginConstraint=_dateTopMarginConstraint;
- (void)dealloc;
@property(nonatomic) __weak id <NoteContentLayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didChangeFullSizeClass;
- (void)editorWillSetEditing:(_Bool)arg1 note:(id)arg2 animated:(_Bool)arg3;
- (void)flashScrollIndicators;
- (void)forcedSetContainsCJK:(_Bool)arg1;
@property(readonly, nonatomic) _Bool hasFullHeight;
@property(readonly, nonatomic) _Bool hasFullWidth;
@property(retain, nonatomic) UIView *horizontalLayoutGuide; // @synthesize horizontalLayoutGuide=_horizontalLayoutGuide;
@property(readonly, nonatomic) DOMHTMLDocument *htmlDocument;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)insertImageInTextView:(id)arg1;
- (void)invalidateSizeRelatedConstraints;
@property(nonatomic, getter=isEditable) _Bool editable;
- (_Bool)isFirstResponder;
- (_Bool)isNoteTextViewVisible:(id)arg1;
- (id)keyCommands;
- (void)layoutSubviews;
@property(retain, nonatomic) NSLayoutConstraint *leftConstraint; // @synthesize leftConstraint=_leftConstraint;
- (_Bool)noteTextView:(id)arg1 acceptContentsFromPasteboard:(id)arg2;
- (_Bool)noteTextView:(id)arg1 canHandleLongPressOnElement:(id)arg2;
- (void)noteTextView:(id)arg1 didChangeContentSize:(struct CGSize)arg2;
- (void)noteTextView:(id)arg1 handleLongPressOnElement:(id)arg2 atPoint:(struct CGPoint)arg3;
- (struct CGRect)rectForDOMNode:(id)arg1;
- (struct CGRect)rectForSelection;
- (void)reloadInterface;
- (void)replaceSelectionWithNode:(id)arg1;
- (_Bool)resignFirstResponder;
@property(retain, nonatomic) NSLayoutConstraint *rightConstraint; // @synthesize rightConstraint=_rightConstraint;
- (void)scrollSelectionToVisible:(_Bool)arg1;
- (void)scrollToTopAnimated:(_Bool)arg1;
@property(retain, nonatomic) NotesScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)selectedDOMRange;
- (void)setBounds:(struct CGRect)arg1;
- (void)setContent:(id)arg1 isPlainText:(_Bool)arg2 isCJK:(_Bool)arg3;
- (void)setFrame:(struct CGRect)arg1;
- (void)setNotesWebPreferencesOnWebView:(id)arg1;
- (void)setScrollIndicatorInsets:(struct UIEdgeInsets)arg1;
- (void)setSelectedDOMRange:(id)arg1 affinity:(int)arg2;
- (void)setSelectionToStart;
@property(retain, nonatomic) NSLayoutConstraint *textTopMarginConstraint; // @synthesize textTopMarginConstraint=_textTopMarginConstraint;
@property(retain, nonatomic) NoteTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) ICTextViewDelegateHelper *textViewDelegateHelper; // @synthesize textViewDelegateHelper=_textViewDelegateHelper;
@property(nonatomic) __weak id <NotesTextureScrolling> textureScrollingDelegate;
- (void)setTimestampDate:(id)arg1;
@property(nonatomic) _Bool tracksMaximumContentLength; // @synthesize tracksMaximumContentLength=_tracksMaximumContentLength;
@property(nonatomic) _Bool updatedTitleRange; // @synthesize updatedTitleRange=_updatedTitleRange;
- (void)setupDateHorizontalConstraint;
@property(readonly, nonatomic) NSArray *subWebResources;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
@property(readonly, nonatomic) NSString *title;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateConstraints;
- (void)updateDateLabel;
- (void)updateHorizontalConstraints;
- (void)updateMarginConstraints;
- (id)viewPrintFormatter;
- (id)webArchive;
- (void)webViewDidChangeNotification:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

