//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NotesDisplayControllerDelegate.h"
#import "NotesListControllerDelegate.h"
#import "NotesSearchResultListControllerDelegate.h"
#import "UIApplicationDelegate.h"

@class ICSplitViewController, NSManagedObjectID, NSMutableSet, NSString, NSTimer, NSUserActivity, NoteCollectionListController, NoteCollectionObject, NoteContext, NoteObject, NotesDisplayController, UINavigationController, UIWindow;

@interface NotesApp : NSObject <NotesDisplayControllerDelegate, NotesListControllerDelegate, NotesSearchResultListControllerDelegate, UIApplicationDelegate>
{
    unsigned int _isBackgrounding:1;
    unsigned int _shouldHandleExternalChangeOnResume:1;
    unsigned int _refreshIsPendingForStoresList:1;
    unsigned int _refreshIsPendingForAllNotes:1;
    NSMutableSet *_collectionIDsPendingRefresh;
    _Bool _didSetupApplication;
    _Bool _pendingUserActivityContinuation;
    _Bool _shouldSetupApplicationWhenEnteringForeground;
    NotesDisplayController *_displayController;
    NoteCollectionListController *_listController;
    NoteContext *_noteContext;
    NSManagedObjectID *_displayedNoteID;
    NSManagedObjectID *_displayedCollectionID;
    NSTimer *_pendingUserActivityContinuationTimer;
    NSUserActivity *_userActivityPendingContinuation;
}

+ (id)sharedNotesApp;
- (void).cxx_destruct;
- (void)_cancelAllPendingRefreshes;
- (void)_markRefreshAsPendingForCollectionWithId:(id)arg1;
- (void)_markRefreshAsPendingForStoresList;
- (void)_performRefreshIfNeededForCollectionWithId:(id)arg1;
- (void)_performRefreshIfNeededForOrphanedAccounts;
- (void)_performRefreshIfNeededForStoresList;
- (_Bool)_refreshIsPendingForCollectionWithId:(id)arg1;
- (_Bool)_refreshIsPendingForStoresList;
- (void)_saveState;
- (void)_unmarkRefreshAsPendingForCollectionWithId:(id)arg1;
- (void)_unmarkRefreshAsPendingForStoresList;
- (void)abortUserActivityContinuation;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationSignificantTimeChange:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillSuspendForEventsOnly;
- (void)applicationWillTerminate:(id)arg1;
- (id)archivedConfiguration;
- (void)attemptToContinuePendingUserActivity;
- (void)createAndDisplayNewNoteAnimated:(_Bool)arg1;
- (id)defaultNoteToDisplay;
- (void)deleteNote:(id)arg1 consequentAction:(long long)arg2;
- (long long)deleteNoteConsequentActionForActionOrigin:(long long)arg1;
@property(readonly, nonatomic) UINavigationController *detailNavigationController;
- (void)didDeleteNote:(id)arg1 consequentAction:(long long)arg2;
- (void)didReceiveTouchAffectingPendingActivityContinuation:(id)arg1;
@property(readonly, nonatomic) _Bool didSetupApplication;
- (void)didShowDisplayController;
- (void)displayCollection:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NotesDisplayController *displayController; // @synthesize displayController=_displayController;
- (void)displayNoNoteAnimated:(_Bool)arg1;
- (void)displayNote:(id)arg1 animated:(_Bool)arg2;
- (void)displayNote:(id)arg1 animated:(_Bool)arg2 showListControllerIfNecessary:(_Bool)arg3;
@property(readonly, nonatomic) NoteCollectionObject *displayedCollection;
@property(retain, nonatomic) NSManagedObjectID *displayedCollectionID; // @synthesize displayedCollectionID=_displayedCollectionID;
@property(readonly, nonatomic) NoteObject *displayedNote;
@property(retain, nonatomic) NSManagedObjectID *displayedNoteID; // @synthesize displayedNoteID=_displayedNoteID;
- (void)finishActivityContinuation;
- (void)importWillDeleteNote:(id)arg1;
- (_Bool)interfaceRequiresDetailController;
- (_Bool)isDisplayControllerVisible;
@property(nonatomic, getter=isPendingUserActivityContinuation) _Bool pendingUserActivityContinuation; // @synthesize pendingUserActivityContinuation=_pendingUserActivityContinuation;
- (void)launchSearchIndexableObjectFromCoreSpotlight:(id)arg1;
@property(retain, nonatomic) NoteCollectionListController *listController; // @synthesize listController=_listController;
- (void)localeChanged:(id)arg1;
@property(readonly, nonatomic) UINavigationController *masterNavigationController;
- (id)nameOfDefaultImageToUpdateAtSuspension;
- (id)newlyCreatedNote;
- (id)newlyCreatedNoteReadyForDisplay;
@property(retain, nonatomic) NoteContext *noteContext; // @synthesize noteContext=_noteContext;
- (void)noteDisplayController:(id)arg1 beginDisplayingNote:(id)arg2 animated:(_Bool)arg3;
- (void)noteDisplayController:(id)arg1 beginEditingNote:(id)arg2 animated:(_Bool)arg3;
- (void)noteDisplayController:(id)arg1 deleteNote:(id)arg2 actionOrigin:(long long)arg3;
- (void)noteDisplayController:(id)arg1 endDisplayingNote:(id)arg2 animated:(_Bool)arg3;
- (void)noteDisplayController:(id)arg1 noteWasDeletedFromSearchResult:(id)arg2;
- (void)notesChangedExternally:(id)arg1;
- (void)notesListController:(id)arg1 deleteNote:(id)arg2;
- (void)notesListController:(id)arg1 didSelectNote:(id)arg2;
- (void)notesListController:(id)arg1 willMoveNotes:(id)arg2;
- (void)notesSearchResultListControllerDidDismiss:(id)arg1;
@property(retain, nonatomic) NSTimer *pendingUserActivityContinuationTimer; // @synthesize pendingUserActivityContinuationTimer=_pendingUserActivityContinuationTimer;
- (void)prepareForDefaultImageSnapshotForScreen:(id)arg1;
- (void)refreshDatesAndTimes;
- (void)refreshNotesIfNeededForCollection:(id)arg1;
- (void)refreshOrphanedAccountsIfNeeded;
- (void)refreshStoresListIfNeeded;
- (void)sendEvent:(id)arg1;
- (void)setDisplayedCollectionIDFromRestoredID:(id)arg1;
- (void)setDisplayedNoteIDForNote:(id)arg1;
@property(nonatomic) _Bool shouldSetupApplicationWhenEnteringForeground; // @synthesize shouldSetupApplicationWhenEnteringForeground=_shouldSetupApplicationWhenEnteringForeground;
@property(retain, nonatomic) NSUserActivity *userActivityPendingContinuation; // @synthesize userActivityPendingContinuation=_userActivityPendingContinuation;
- (void)setupApplication;
- (void)setupApplicationIfNecessary;
- (void)showCurrentNoteAfterLaunching;
- (void)showDisplayControllerAnimated:(_Bool)arg1 showListControllerIfNecessary:(_Bool)arg2;
- (void)showListControllerAnimated:(_Bool)arg1;
@property(readonly, nonatomic) ICSplitViewController *splitViewController;
- (void)timeZoneChanged:(id)arg1;
- (void)updateControllersForDisplayedContentAnimated:(_Bool)arg1;
- (void)updateListControllerForContentAnimated:(_Bool)arg1;
- (void)updateStateToDisplayCollection:(id)arg1 animated:(_Bool)arg2;
- (void)updateStateToDisplayNote:(id)arg1 animated:(_Bool)arg2;
- (void)userActivityContinuationTimedOut:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

