//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QLPreviewItem.h"

@class DOMHTMLElement, NSString, NSURL, NoteAttachmentPresentation;

@interface NoteAttachmentPresentationOccurence : NSObject <QLPreviewItem>
{
    NoteAttachmentPresentation *_presentation;
    DOMHTMLElement *_element;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) DOMHTMLElement *element; // @synthesize element=_element;
- (id)init;
- (id)initWithPresentation:(id)arg1 element:(id)arg2;
@property(readonly, nonatomic) NoteAttachmentPresentation *presentation; // @synthesize presentation=_presentation;
@property(readonly, nonatomic) NSURL *previewItemURL;
- (_Bool)showsUpInRange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *previewItemTitle;
@property(readonly) Class superclass;

@end

