//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UISearchBarDelegate.h"
#import "UIWebFindOnPageHighlighterDelegate.h"

@class NSString, NotesFindOnPageHighlighter;

@interface NotesFindViewController : UIViewController <UISearchBarDelegate, UIWebFindOnPageHighlighterDelegate>
{
    id <NotesFindViewControllerDelegate> _findDelegate;
    NotesFindOnPageHighlighter *_highlighter;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)doneButtonTapped;
- (void)findOnPageHighlighterDidHighlightMatch:(id)arg1;
- (_Bool)hasActiveHighlights;
- (id)initWithContentLayer:(id)arg1;
- (void)keyboardDidHide;
- (void)loadView;
- (void)nextPreviousControlValueChanged:(id)arg1;
- (void)resetSearch;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)setDelegate:(id)arg1;
- (void)setSearchTerm:(id)arg1;
- (void)stopFind:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateUI;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

