//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableDictionary;

@interface NotesRefreshController : NSObject
{
    NSMutableDictionary *_lastNotesRefreshDates;
    NSDate *_lastStoresListRefreshDate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_accountStore;
- (_Bool)notesNeedRefresh;
- (_Bool)notesNeedRefreshForCollectionWithId:(id)arg1;
- (void)refreshAllNotesIfNeeded;
- (void)refreshNotesForCollectionWithId:(id)arg1;
- (void)refreshOrphanedAccounts;
- (void)refreshStoresList;
- (_Bool)storesListNeedsRefresh;

@end

