//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

@interface NotesCIDURLProtocol : NSURLProtocol
{
}

+ (_Bool)canInitWithRequest:(id)arg1;
+ (id)canonicalRequestForRequest:(id)arg1;
+ (void)registerDataProvider:(id)arg1 forCIDURL:(id)arg2;
+ (void)unregisterDataProviderForCIDURL:(id)arg1;
- (void)startLoading;
- (void)stopLoading;

@end

