//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface NotesFindHighlightBubbleView : UIView
{
    struct CGImage *_highlightedContent;
    struct CGPoint _highlightedContentOrigin;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)setHighlightedContent:(struct CGImage *)arg1 withOrigin:(struct CGPoint)arg2;

@end

