//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NoteObject.h"

@interface NoteObject (ExperimentalUndoSupport)
- (void)undoablyMoveToTrashWithActionName:(id)arg1;
- (void)undoablyUndeleteTo:(id)arg1 actionName:(id)arg2;
@end

