//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NoteObject.h"

@interface NoteObject (AirDropDocument)
+ (void)importLegacyNoteFromWebArchive:(id)arg1 withContent:(id)arg2 intoLegacyNote:(id)arg3 context:(struct NoteContext *)arg4;
+ (id)newNoteForAirDropDocument:(id)arg1 inApp:(id)arg2;
+ (id)noteByImportingLegacyNoteFromWebArchive:(id)arg1 withContent:(id)arg2 context:(struct NoteContext *)arg3;
@end

