//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NotesManageableAccountActivityViewController.h"

@class NotesDisplayController;

@interface NotesActivityViewController : NotesManageableAccountActivityViewController
{
    NotesDisplayController *_displayController;
}

- (void).cxx_destruct;
- (void)_prepareActivity:(id)arg1;
- (_Bool)_shouldShowSystemActivity:(id)arg1;
@property(retain, nonatomic) NotesDisplayController *displayController; // @synthesize displayController=_displayController;

@end

