//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCache;

@interface NoteDateStringCache : NSObject
{
    NSCache *_cache;
}

+ (id)cache;
- (void).cxx_destruct;
@property(retain, nonatomic) NSCache *cache; // @synthesize cache=_cache;
- (void)dealloc;
- (id)init;
- (void)rebuildCacheInBackground;
- (void)significantTimeChange:(id)arg1;
- (id)stringForDate:(id)arg1;

@end

