//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NotesQuickLookActivityItem, QLPreviewController, UIImage;

@protocol NotesQuickLookActivityItemDelegate <NSObject>
- (struct CGRect)notesQuickLookActivityItem:(NotesQuickLookActivityItem *)arg1 rectForPreviewItem:(id <QLPreviewItem>)arg2 inView:(id *)arg3 previewController:(QLPreviewController *)arg4;
- (UIImage *)notesQuickLookActivityItem:(NotesQuickLookActivityItem *)arg1 transitionImageForPreviewItem:(id <QLPreviewItem>)arg2 previewController:(QLPreviewController *)arg3;
@end

