//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NoteObject, NotesListController;

@protocol NotesListControllerDelegate <NSObject>
- (void)notesListController:(NotesListController *)arg1 deleteNote:(NoteObject *)arg2;
- (void)notesListController:(NotesListController *)arg1 didSelectNote:(NoteObject *)arg2;
- (void)notesListController:(NotesListController *)arg1 willMoveNotes:(NSArray *)arg2;
@end

