//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NotesCIDDataProvider.h"

@class NSData, NSError, NSString, NSURL;

@interface NoteAttachmentPresentation : NSObject <NotesCIDDataProvider>
{
    _Bool _sourceIsManaged;
    _Bool _image;
    NSString *_contentID;
    NSURL *_contentIDURL;
    NSURL *_dataFileURL;
    NSString *_mimeType;
    NSString *_filename;
    NSError *_dataFileURLError;
    NSString *_contentIDURLAbsoluteString;
    NSData *_data;
    CDUnknownBlockType _iconPNGDataProvider;
    struct CGSize _iconSize;
}

+ (id)attachmentPresentationsForAttachments:(id)arg1;
+ (id)attachmentResourceURLsMentionedByPresentationDOMDocument:(id)arg1;
+ (void)clearDOMDocumentAttachments:(id)arg1;
+ (void)prepareDOMDocumentForPresentation:(id)arg1 withAttachmentPresentations:(id)arg2 occurences:(id *)arg3;
+ (void)prepareDOMDocumentForSerialization:(id)arg1 withAttachmentPresentations:(id)arg2 newPresentationProvider:(CDUnknownBlockType)arg3 leftoverPresentations:(id *)arg4;
+ (id)presentationSelector;
+ (id)sourceURLForElement:(id)arg1;
- (void).cxx_destruct;
- (void)clearCache;
@property(copy, nonatomic) NSString *contentID; // @synthesize contentID=_contentID;
@property(copy, nonatomic) NSURL *contentIDURL; // @synthesize contentIDURL=_contentIDURL;
@property(copy, nonatomic) NSString *contentIDURLAbsoluteString; // @synthesize contentIDURLAbsoluteString=_contentIDURLAbsoluteString;
- (id)createPresentationNodeForDOMDocument:(id)arg1;
- (id)createSerializationNodeForDOMDocument:(id)arg1;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(copy, nonatomic) NSURL *dataFileURL; // @synthesize dataFileURL=_dataFileURL;
@property(retain, nonatomic) NSError *dataFileURLError; // @synthesize dataFileURLError=_dataFileURLError;
@property(readonly, copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
- (_Bool)getData:(id *)arg1 mimeType:(id *)arg2 error:(id *)arg3;
- (_Bool)getPresentationData:(id *)arg1 mimeType:(id *)arg2 error:(id *)arg3;
@property(copy, nonatomic) CDUnknownBlockType iconPNGDataProvider; // @synthesize iconPNGDataProvider=_iconPNGDataProvider;
@property(nonatomic) struct CGSize iconSize; // @synthesize iconSize=_iconSize;
- (id)initWithData:(id)arg1 contentID:(id)arg2 mimeType:(id)arg3 filename:(id)arg4;
- (id)initWithNoteAttachmentObject:(id)arg1;
@property(nonatomic, getter=isImage) _Bool image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(readonly, nonatomic) _Bool sourceIsManaged; // @synthesize sourceIsManaged=_sourceIsManaged;
- (id)transformNodeForPresentation:(id)arg1;
- (void)transformNodeForSerialization:(id)arg1;
- (void)updateContentIDURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

