//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

#import "QLPreviewControllerDataSource.h"
#import "QLPreviewControllerDelegate.h"

@class NSString, NotesQuickLookActivityItem;

@interface NotesQuickLookActivity : UIActivity <QLPreviewControllerDataSource, QLPreviewControllerDelegate>
{
    _Bool _sourceIsManaged;
    NotesQuickLookActivityItem *_item;
}

- (void).cxx_destruct;
- (id)_beforeActivity;
- (void)_cleanup;
- (id)activityImage;
- (id)activityTitle;
- (id)activityType;
- (_Bool)canPerformWithActivityItems:(id)arg1;
@property(retain, nonatomic) NotesQuickLookActivityItem *item; // @synthesize item=_item;
- (long long)numberOfPreviewItemsInPreviewController:(id)arg1;
- (void)performActivity;
- (void)prepareWithActivityItems:(id)arg1;
- (void)presentPreviewController;
- (struct CGRect)previewController:(id)arg1 frameForPreviewItem:(id)arg2 inSourceView:(id *)arg3;
- (id)previewController:(id)arg1 previewItemAtIndex:(long long)arg2;
- (id)previewController:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(struct CGRect *)arg3;
@property(nonatomic) _Bool sourceIsManaged; // @synthesize sourceIsManaged=_sourceIsManaged;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

