//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NoteObject, NotesDisplayController;

@protocol NotesDisplayControllerDelegate <NSObject>
- (void)noteDisplayController:(NotesDisplayController *)arg1 beginDisplayingNote:(NoteObject *)arg2 animated:(_Bool)arg3;
- (void)noteDisplayController:(NotesDisplayController *)arg1 beginEditingNote:(NoteObject *)arg2 animated:(_Bool)arg3;
- (void)noteDisplayController:(NotesDisplayController *)arg1 deleteNote:(NoteObject *)arg2 actionOrigin:(long long)arg3;
- (void)noteDisplayController:(NotesDisplayController *)arg1 endDisplayingNote:(NoteObject *)arg2 animated:(_Bool)arg3;
- (void)noteDisplayController:(NotesDisplayController *)arg1 noteWasDeletedFromSearchResult:(NoteObject *)arg2;
@end

