//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AFContextProvider.h"
#import "NSUserActivityDelegate.h"
#import "NoteContentLayerDelegate.h"
#import "NotesQuickLookActivityItemDelegate.h"
#import "NotesStateArchiving.h"
#import "ScrollViewKeyboardResizerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class NSArray, NSDate, NSManagedObjectID, NSNumber, NSString, NSTimer, NSUserActivity, NoteAttachmentPresentationOccurence, NoteContentLayer, NoteObject, NoteUserActivityState, NotesBackgroundView, NotesFindViewController, ScrollViewKeyboardResizer, UIBarButtonItem, UIImagePickerController, UIPresentationController, UITapGestureRecognizer;

@interface NotesDisplayController : UIViewController <NoteContentLayerDelegate, UIActionSheetDelegate, AFContextProvider, UIPopoverPresentationControllerDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, NotesQuickLookActivityItemDelegate, ScrollViewKeyboardResizerDelegate, NSUserActivityDelegate, NotesStateArchiving>
{
    NotesBackgroundView *_backgroundView;
    _Bool _delayingSetContent;
    unsigned int _didSetContentFromNote:1;
    NSTimer *_autosaveTimer;
    NotesFindViewController *_findViewController;
    NSArray *_nonManagedAttachmentPresentationOccurences;
    _Bool _contentHasUnsavedChanges;
    _Bool _pickingAttachment;
    _Bool _pendingArchivedEditingState;
    _Bool _canProvideNote;
    _Bool _visible;
    _Bool _changingTraitCollection;
    id <NotesDisplayControllerDelegate> _delegate;
    NoteObject *_note;
    NoteContentLayer *_contentLayer;
    NSArray *_attachmentPresentations;
    NSArray *_allAttachmentPresentationOccurences;
    UIImagePickerController *_pickerController;
    UIPresentationController *_activityPresentationController;
    UIPresentationController *_deletePresentationController;
    NoteAttachmentPresentationOccurence *_occurenceShowingActivity;
    UIBarButtonItem *_doneButtonItem;
    NSArray *_actionButtonItemsForToolbar;
    NSArray *_actionButtonItemsForNavBar;
    UITapGestureRecognizer *_tapContentGestureRecognizer;
    NSNumber *_pendingArchivedNoteID;
    ScrollViewKeyboardResizer *_scrollViewResizer;
    NSString *_searchTermPendingHighlight;
    NSDate *_displayedNoteVersionTimestamp;
    NSManagedObjectID *_displayedNoteVersionObjectID;
    NSUserActivity *_noteUserActivity;
    NoteUserActivityState *_noteUserActivityState;
    UIBarButtonItem *_createNavBarButtonItem;
    UIBarButtonItem *_shareNavBarButtonItem;
    UIBarButtonItem *_deleteNavBarButtonItem;
    UIBarButtonItem *_createBarButtonItem;
    UIBarButtonItem *_shareBarButtonItem;
    UIBarButtonItem *_deleteBarButtonItem;
    struct CGPoint _inOccurenceActivityOrigin;
    struct CGPoint _pendingArchivedContentOffset;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
- (void).cxx_destruct;
- (void)_autosaveTimerFired:(id)arg1;
- (void)_invalidateAutosaveTimer;
- (void)_resetAutosaveTimer;
- (void)_userFontSizeUpdated:(id)arg1;
- (_Bool)acceptNewSize:(unsigned long long)arg1;
- (void)accessibilityLargeTextDidChange;
@property(retain, nonatomic) NSArray *actionButtonItemsForNavBar; // @synthesize actionButtonItemsForNavBar=_actionButtonItemsForNavBar;
@property(retain, nonatomic) NSArray *actionButtonItemsForToolbar; // @synthesize actionButtonItemsForToolbar=_actionButtonItemsForToolbar;
- (struct CGRect)activityPopoverSourceRect;
@property(retain, nonatomic) UIPresentationController *activityPresentationController; // @synthesize activityPresentationController=_activityPresentationController;
- (void)addButtonClicked:(id)arg1;
- (id)addButtonItem;
@property(copy, nonatomic) NSArray *allAttachmentPresentationOccurences; // @synthesize allAttachmentPresentationOccurences=_allAttachmentPresentationOccurences;
- (_Bool)allowContextProvider:(id)arg1;
- (_Bool)allowsAttachments;
- (_Bool)allowsAttachmentsInNoteContentLayer:(id)arg1;
- (void)animateDeleteTransitionWithCompletion:(CDUnknownBlockType)arg1;
- (void)applyAccessibilityInfo;
- (id)archivedConfiguration;
- (id)attachmentPresentationOccurencesForPreviewingWithManagedInterface:(_Bool)arg1;
@property(copy, nonatomic) NSArray *attachmentPresentations; // @synthesize attachmentPresentations=_attachmentPresentations;
- (_Bool)canInsertImagesInNoteContentLayer:(id)arg1;
@property(nonatomic) _Bool canProvideNote; // @synthesize canProvideNote=_canProvideNote;
- (void)captureDisplayedNoteVersion;
- (void)cleanupAfterBarSourcedPopoverPresentation;
- (double)consumedBottomAreaForResizer:(id)arg1;
- (id)contentAsPasteboardItems;
@property(nonatomic) _Bool contentHasUnsavedChanges; // @synthesize contentHasUnsavedChanges=_contentHasUnsavedChanges;
@property(retain, nonatomic) NoteContentLayer *contentLayer; // @synthesize contentLayer=_contentLayer;
- (struct CGPoint)contentLayerPointFromPoint:(struct CGPoint)arg1 relativeToRect:(struct CGRect)arg2;
- (id)contentScrollView;
- (id)contextManager;
@property(retain, nonatomic) UIBarButtonItem *createBarButtonItem; // @synthesize createBarButtonItem=_createBarButtonItem;
- (id)createButtonItemWithSystemItem:(long long)arg1 action:(SEL)arg2 backgroundVerticalAdjustment:(double)arg3 tag:(long long)arg4;
@property(retain, nonatomic) UIBarButtonItem *createNavBarButtonItem; // @synthesize createNavBarButtonItem=_createNavBarButtonItem;
- (void)dealloc;
@property(nonatomic) __weak id <NotesDisplayControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIBarButtonItem *deleteBarButtonItem; // @synthesize deleteBarButtonItem=_deleteBarButtonItem;
- (void)deleteButtonClicked:(id)arg1;
- (id)deleteButtonItem;
@property(retain, nonatomic) UIBarButtonItem *deleteNavBarButtonItem; // @synthesize deleteNavBarButtonItem=_deleteNavBarButtonItem;
@property(retain, nonatomic) UIPresentationController *deletePresentationController; // @synthesize deletePresentationController=_deletePresentationController;
- (void)didChangeNoteProviderStatus;
- (void)didDismissActivityController;
- (void)didDismissDeleteAlertController;
- (void)didDismissPickerController;
- (void)didReceiveMemoryWarning;
- (void)dismissPickerControllerWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)displayNote:(id)arg1;
- (id)displayedActionButtonItemsWithTag:(long long)arg1;
@property(retain, nonatomic) NSManagedObjectID *displayedNoteVersionObjectID; // @synthesize displayedNoteVersionObjectID=_displayedNoteVersionObjectID;
@property(retain, nonatomic) NSDate *displayedNoteVersionTimestamp; // @synthesize displayedNoteVersionTimestamp=_displayedNoteVersionTimestamp;
- (void)doneButtonClicked:(id)arg1;
@property(retain, nonatomic) UIBarButtonItem *doneButtonItem; // @synthesize doneButtonItem=_doneButtonItem;
- (unsigned long long)estimatedSizeOfDisplayedContent;
- (id)getCurrentContext;
- (void)handleTapOnContent:(id)arg1;
- (void)highlightTermString:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
@property(nonatomic) struct CGPoint inOccurenceActivityOrigin; // @synthesize inOccurenceActivityOrigin=_inOccurenceActivityOrigin;
- (id)initWithArchivedConfiguration:(id)arg1;
- (void)insertImageAttachmentWithData:(id)arg1 mimeType:(id)arg2;
- (void)insertImageInNoteContentLayer:(id)arg1;
@property(nonatomic, getter=isChangingTraitCollection) _Bool changingTraitCollection; // @synthesize changingTraitCollection=_changingTraitCollection;
- (_Bool)isEndingNoteDisplay;
- (_Bool)isNoteContentLayerVisible:(id)arg1;
@property(nonatomic, getter=isPickingAttachment) _Bool pickingAttachment; // @synthesize pickingAttachment=_pickingAttachment;
@property(nonatomic, getter=isVisible) _Bool visible; // @synthesize visible=_visible;
- (void)loadView;
@property(retain, nonatomic) NoteObject *note; // @synthesize note=_note;
- (_Bool)noteCanBeSaved;
- (_Bool)noteContainsValuableContent;
- (_Bool)noteContentLayer:(id)arg1 acceptContentsFromPasteboard:(id)arg2;
- (_Bool)noteContentLayer:(id)arg1 acceptStringIncreasingContentLength:(id)arg2;
- (_Bool)noteContentLayer:(id)arg1 canHandleLongPressOnElement:(id)arg2;
- (void)noteContentLayer:(id)arg1 containsCJK:(_Bool)arg2;
- (void)noteContentLayer:(id)arg1 contentScrollViewWillBeginDragging:(id)arg2;
- (void)noteContentLayer:(id)arg1 didChangeContentSize:(struct CGSize)arg2;
- (void)noteContentLayer:(id)arg1 handleLongPressOnElement:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)noteContentLayer:(id)arg1 setEditing:(_Bool)arg2 animated:(_Bool)arg3;
- (void)noteContentLayerContentDidChange:(id)arg1 updatedTitle:(_Bool)arg2;
- (void)noteContentLayerKeyboardDidHide:(id)arg1;
- (_Bool)noteContentLayerShouldBeginEditing:(id)arg1;
- (_Bool)noteHasSizeLimit;
- (_Bool)noteMatchesDisplayedContent:(id)arg1;
- (_Bool)noteShouldBeDiscarded;
@property(retain) NSUserActivity *noteUserActivity; // @synthesize noteUserActivity=_noteUserActivity;
@property(retain) NoteUserActivityState *noteUserActivityState; // @synthesize noteUserActivityState=_noteUserActivityState;
- (void)noteWasDeletedFromSearchResult:(id)arg1;
- (struct CGRect)notesQuickLookActivityItem:(id)arg1 rectForPreviewItem:(id)arg2 inView:(id *)arg3 previewController:(id)arg4;
- (id)notesQuickLookActivityItem:(id)arg1 transitionImageForPreviewItem:(id)arg2 previewController:(id)arg3;
- (id)occurenceForPreviewItem:(id)arg1 hintIndex:(long long)arg2;
@property(retain, nonatomic) NoteAttachmentPresentationOccurence *occurenceShowingActivity; // @synthesize occurenceShowingActivity=_occurenceShowingActivity;
@property(nonatomic) struct CGPoint pendingArchivedContentOffset; // @synthesize pendingArchivedContentOffset=_pendingArchivedContentOffset;
@property(nonatomic) _Bool pendingArchivedEditingState; // @synthesize pendingArchivedEditingState=_pendingArchivedEditingState;
@property(retain, nonatomic) NSNumber *pendingArchivedNoteID; // @synthesize pendingArchivedNoteID=_pendingArchivedNoteID;
@property(retain, nonatomic) UIImagePickerController *pickerController; // @synthesize pickerController=_pickerController;
- (struct CGRect)pickerPopoverSourceRect;
- (struct CGPoint)pointRelativeToRect:(struct CGRect)arg1 fromContentLayerPoint:(struct CGPoint)arg2;
- (void)popoverPresentationController:(id)arg1 willRepositionPopoverToRect:(inout struct CGRect *)arg2 inView:(inout id *)arg3;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (void)prepareDOMForPresentation;
- (void)prepareDOMForSerializationWithLeftoverPresentations:(id *)arg1 createdAttachments:(id *)arg2;
- (void)prepareForBarSourcedPopoverPresentation;
- (void)prepareForDefaultImageSnapshotForScreen:(id)arg1;
- (void)prepareForReuse;
- (struct CGRect)rectForAttachmentPresentationOccurence:(id)arg1 inView:(id *)arg2;
- (void)refreshAttachmentPresentations;
- (void)reloadContentLayer;
- (void)reloadSearchedTermHighlight;
- (void)resetFontOnResume;
- (void)restoreState;
- (void)runScrollPerformanceTest:(id)arg1 iterations:(int)arg2;
- (void)saveNote;
@property(retain, nonatomic) ScrollViewKeyboardResizer *scrollViewResizer; // @synthesize scrollViewResizer=_scrollViewResizer;
@property(retain, nonatomic) NSString *searchTermPendingHighlight; // @synthesize searchTermPendingHighlight=_searchTermPendingHighlight;
- (void)setContentFromNote;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIBarButtonItem *shareBarButtonItem; // @synthesize shareBarButtonItem=_shareBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *shareNavBarButtonItem; // @synthesize shareNavBarButtonItem=_shareNavBarButtonItem;
@property(retain, nonatomic) UITapGestureRecognizer *tapContentGestureRecognizer; // @synthesize tapContentGestureRecognizer=_tapContentGestureRecognizer;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)shareButtonClicked:(id)arg1;
- (id)shareButtonItem;
- (void)showActionsForAttachmentWithOccurence:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)significantTimeChange;
- (void)terminateFindSessionAnimated:(_Bool)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)turnOnContentLengthTrackingIfNeeded;
- (void)updateBarButtonItemsAnimated:(_Bool)arg1;
- (void)updateBarsVisibilityAnimated:(_Bool)arg1;
- (void)updateContentInteractivity;
- (void)updateContextProviderStatus;
- (void)updateDate;
- (void)updateDateLabel;
- (void)updateNavigationBarRightButtonItemsAnimated:(_Bool)arg1;
- (void)updateNote:(id)arg1;
- (void)updateNoteFromInterface;
- (void)updateNoteProviderStatus;
- (void)updateNoteTitle;
- (void)updateNoteUserActivityState;
- (void)updateToolbarButtonItemsAnimated:(_Bool)arg1;
- (void)updateUserActivityStatus;
- (void)userActivityWasContinued:(id)arg1;
- (void)userActivityWillSave:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)warnUserAboutNoteSizeLimitExceeded;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

