//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIInputView.h"

@class UIBarButtonItem, UILabel, UISearchBar, UISegmentedControl;

@interface NotesFindInputView : UIInputView
{
    UILabel *_resultsLabel;
    UISegmentedControl *_nextPreviousControl;
    UISearchBar *_searchBar;
    UIBarButtonItem *_controlBarButtonItem;
    UIBarButtonItem *_labelBarButtonItem;
    UIBarButtonItem *_doneBarButtonItem;
    UIBarButtonItem *_searchBarButtonItem;
    UIBarButtonItem *_leftFixedSpaceBarButtonItem;
}

+ (id)toolbarWithItems:(id)arg1;
- (void).cxx_destruct;
- (void)didEndSplitTransition;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void)setDoneButtonTarget:(id)arg1 action:(SEL)arg2;
- (void)setLabelText:(id)arg1;
- (void)setSegmentedControlEnabled:(_Bool)arg1;
- (void)setSegmentedControlTarget:(id)arg1 action:(SEL)arg2;

@end

