//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICScrollViewDelegateViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIViewControllerPreviewingDelegate_Deprecated.h"

@class NSString, NoteObject, NotesBackgroundView, ScrollViewKeyboardResizer, UIBarButtonItem, UITableView;

@interface NotesListController : ICScrollViewDelegateViewController <UITableViewDataSource, UITableViewDelegate, UIViewControllerPreviewingDelegate_Deprecated>
{
    _Bool _adjacentToDisplayController;
    NotesBackgroundView *_backgroundView;
    UITableView *_tableView;
    NoteObject *_selectedNote;
    id <NotesListControllerDelegate> _delegate;
    UIBarButtonItem *_cancelButtonItem;
    ScrollViewKeyboardResizer *_scrollViewResizer;
    id <UIViewControllerPreviewing> _previewer;
}

+ (Class)tableViewClass;
- (void).cxx_destruct;
@property(retain, nonatomic) NotesBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIBarButtonItem *cancelButtonItem; // @synthesize cancelButtonItem=_cancelButtonItem;
- (void)cancelEditing:(id)arg1;
- (void)commitPreviewViewController:(id)arg1 committedViewController:(id)arg2;
- (id)contentScrollView;
- (void)dataSourceDidChange;
- (void)dealloc;
@property(nonatomic) __weak id <NotesListControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (id)indexPathForNote:(id)arg1;
@property(nonatomic, getter=isAdjacentToDisplayController) _Bool adjacentToDisplayController; // @synthesize adjacentToDisplayController=_adjacentToDisplayController;
- (_Bool)isDisplayed;
- (void)loadView;
- (id)noteForIndexPath:(id)arg1;
- (unsigned long long)numberOfNotes;
- (void)prepareForDeselection;
- (id)previewViewControllerForLocation:(struct CGPoint)arg1 inSourceView:(id)arg2;
@property(retain, nonatomic) id <UIViewControllerPreviewing> previewer; // @synthesize previewer=_previewer;
- (void)reloadTable;
- (id)rightBarButtonItemForEditingTableView:(_Bool)arg1;
- (void)scrollToSelectedNoteAnimated:(_Bool)arg1;
@property(retain, nonatomic) ScrollViewKeyboardResizer *scrollViewResizer; // @synthesize scrollViewResizer=_scrollViewResizer;
- (void)selectRowForSelectedNoteAnimated:(_Bool)arg1;
@property(retain, nonatomic) NoteObject *selectedNote; // @synthesize selectedNote=_selectedNote;
- (void)setAdjacentToDisplayController:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelectedNote:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)systemFontSizeChanged:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateCell:(id)arg1 withNote:(id)arg2;
- (void)updateCell:(id)arg1 withNote:(id)arg2 animated:(_Bool)arg3;
- (void)updateCellMargins:(id)arg1;
- (void)updateNavigationBarRightButtonItemForEditingTableView:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateVisibleRowsAnimated:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)willPresentPreviewViewController:(id)arg1 forLocation:(struct CGPoint)arg2 inSourceView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

