//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumberFormatter.h"

@interface NSNumberFormatter (ICAccessibility)
+ (id)icaxLocalizedDouble:(double)arg1;
+ (id)icaxLocalizedDouble:(double)arg1 maximumNumberOfDigitsAfterDecimalSeparator:(unsigned long long)arg2;
+ (id)icaxLocalizedNumber:(id)arg1;
+ (id)icaxLocalizedNumber:(id)arg1 maximumNumberOfDigitsAfterDecimalSeparator:(unsigned long long)arg2;
+ (id)icaxLocalizedNumber:(id)arg1 numberStyle:(unsigned long long)arg2;
+ (id)icaxLocalizedNumber:(id)arg1 numberStyle:(unsigned long long)arg2 maximumNumberOfDigitsAfterDecimalSeparator:(unsigned long long)arg3;
+ (id)icaxLocalizedPercentage:(double)arg1;
+ (id)icaxLocalizedPercentage:(double)arg1 maximumNumberOfDigitsAfterDecimalSeparator:(unsigned long long)arg2;
+ (id)icaxLocalizedUnsignedInteger:(unsigned long long)arg1;
@end

