//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray, NSString;

@interface TSDGLFrameBuffer : NSObject
{
    NSArray *_textureConfigs;
    NSDictionary *_namesToTextureDict;
    NSMutableArray *_currentTextureLookupInfoByAttachment;
    NSMutableArray *_desiredTextureLookupInfoByAttachment;
    NSArray *_textureConfigsByAttachment;
    NSArray *_textureLookupInfosByAttachment;
    long long _currentBindingOption;
    unsigned int _currentDrawBuffers[1];
    int _currentDrawBufferCount;
    unsigned int _currentReadBuffer;
    unsigned int _framebuffer;
    _Bool _isUsingNonDefaultAttachments;
    struct __CVOpenGLESTextureCache *_textureCache;
    _Bool _isBound;
    _Bool _shouldDeleteTexturesOnTeardown;
    NSString *_name;
    struct CGSize _size;
}

+ (int)currentGLFramebuffer;
+ (int)currentGLFramebufferWithBindingOption:(long long)arg1;
+ (void)setCurrentGLFramebuffer:(int)arg1;
+ (void)setCurrentGLFramebuffer:(int)arg1 withBindingOption:(long long)arg2;
- (unsigned int)GLTextureAtIndex:(unsigned long long)arg1;
- (unsigned int)GLTextureAtIndex:(unsigned long long)arg1 attachment:(unsigned int)arg2;
- (unsigned int)GLTextureNamed:(id)arg1;
- (void)bindFramebuffer;
- (void)bindFramebufferWithBindingOption:(long long)arg1;
- (struct __CVBuffer *)createTextureCacheTextureWithSize:(struct CGSize)arg1 pixelBufferOut:(struct __CVBuffer **)arg2;
- (unsigned int)currentGLTexture;
- (unsigned int)currentGLTextureAtAttachment:(unsigned int)arg1;
- (long long)currentTextureIndexAtAttachment:(unsigned int)arg1;
- (void)dealloc;
- (id)description;
- (id)initWithSize:(struct CGSize)arg1;
- (id)initWithSize:(struct CGSize)arg1 textureConfigs:(id)arg2;
- (id)initWithSize:(struct CGSize)arg1 textureConfigs:(id)arg2 textureCache:(struct __CVOpenGLESTextureCache *)arg3;
- (id)initWithSize:(struct CGSize)arg1 textureCount:(unsigned long long)arg2;
@property(readonly, nonatomic) _Bool isBound; // @synthesize isBound=_isBound;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (_Bool)p_isCurrentDrawBuffersEqualToDrawbuffers:(unsigned int *)arg1 count:(long long)arg2;
- (void)p_setDrawBuffersAndReadBuffer;
- (void)p_setFramebufferTextureAtAttachmentIndex:(long long)arg1 bindingOption:(long long)arg2;
- (struct __CVBuffer *)pixelBufferAtIndex:(unsigned long long)arg1 attachment:(unsigned int)arg2;
- (void)setCurrentTextureIndex:(unsigned long long)arg1;
- (void)setCurrentTextureIndex:(unsigned long long)arg1 atAttachment:(unsigned int)arg2;
- (void)setCurrentTextureNamed:(id)arg1;
- (void)setCurrentTextureNamed:(id)arg1 atAttachment:(unsigned int)arg2;
- (void)setCurrentTextureToNextAtAttachment:(unsigned int)arg1;
- (void)setCurrentTexturesToNext;
@property(nonatomic) _Bool shouldDeleteTexturesOnTeardown; // @synthesize shouldDeleteTexturesOnTeardown=_shouldDeleteTexturesOnTeardown;
- (void)setupFramebufferIfNecessary;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
- (struct CGSize)sizeOfGLTextureNamed:(id)arg1;
- (void)teardown;
- (void)unbindFramebufferAndBindGLFramebuffer:(int)arg1;
- (void)unbindFramebufferAndBindGLFramebuffer:(int)arg1 withBindingOption:(long long)arg2;

@end

