//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface UIButton (IC)
- (void)addButtonFrame;
- (void)enableLetterpressOnImageView;
- (void)enableLetterpressOnTitleLabel;
- (void)setLetterpressTitleText:(id)arg1 color:(id)arg2 font:(id)arg3 forState:(unsigned long long)arg4;
- (void)setLetterpressTitleText:(id)arg1 forState:(unsigned long long)arg2;
@end

