//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@class NSString;

@interface UIColor (ICAccessibility)
+ (id)icaxHueNameForValue:(double)arg1;
- (id)_icaxColorDescriptionForAttributes:(id)arg1;
@property(readonly, nonatomic) NSString *icaxApproximateColorDescription;
@property(readonly, nonatomic) NSString *icaxDescriptionWithLuma;
- (double)icaxHue;
- (id)icaxHueName;
- (id)icaxLightnessModifier;
@property(readonly, nonatomic) double icaxLuma;
- (double)icaxSaturation;
- (id)icaxSaturationModifier;
@end

