//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (Salience)
+ (struct CGRect)bounds:(struct CGRect)arg1 paddedForImageSize:(struct CGSize)arg2 paddingMultiplier:(double)arg3;
+ (id)edgeDetector;
+ (id)faceDetector;
+ (struct UIImage *)imageByEdgeFilteringImage:(struct UIImage *)arg1;
- (struct CGRect)boundsOfSalience;
@end

