//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class UIColor;

@interface UIScrollView (IC)
@property(retain, nonatomic) UIColor *bottomExtensionViewColor;
- (void)scrollRectToVisible:(struct CGRect)arg1 animated:(_Bool)arg2 consideringInsets:(_Bool)arg3;
@property(retain, nonatomic) UIColor *topExtensionViewColor;
- (struct CGRect)visibleRectConsideringInsets:(_Bool)arg1;
@end

