//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (NotesUtilities)
+ (void)enableUIViewAnimations:(_Bool)arg1 forBlock:(CDUnknownBlockType)arg2;
- (void)showViewController:(id)arg1 animated:(_Bool)arg2 sender:(id)arg3;
@end

