//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebDocumentView.h"

@interface UIWebDocumentView (Summarization)
- (_Bool)_appendTextContentsOfNode:(id)arg1 maxLength:(int)arg2 skippingFirstLine:(_Bool *)arg3 toString:(id)arg4;
- (_Bool)containsValuableContent;
- (id)firstLine;
@end

