#! /bin/sh
if [[ -n "$1" ]]
then
    file="$1"
    if [[ -f $file ]]
    then
        file_name="${file%.*}_de"
        echo $file_name
        if [ -d $file_name ]
        then
            echo "$file_name exists"
        else
            apktool d "$1" -o $file_name
            unzip $file -d $file_name/dex/
            mkdir -p $(PWD)/$file_name/jar && cd $(PWD)/$file_name/jar
            d2j-dex2jar.sh ../dex/classes*.dex
            java -jar ~/data/bin/procyon.jar -o ../src -ss ./classes*-dex2jar.jar
        fi
    else
        echo "$file not exists"
    fi
else
    echo "[+]Usage: ./prep_android YOUR_FILE.apk"
fi